#!/usr/bin/env python3
"""
Build conferences_2026-07-05.tsv  and  conferences_2026-07-05.xlsx
for AG Schuck quantum-photonics conference tracker.
"""

import csv, os
from datetime import date, timedelta
from openpyxl import Workbook
from openpyxl.styles import PatternFill, Font, Alignment, Border, Side, PatternFill
from openpyxl.utils import get_column_letter

TODAY     = date(2026, 7, 5)
SNAPSHOT  = "2026-07-05"
OUTDIR    = "/home/user/conferences"

COLS = [
    "id", "name", "acronym", "type", "topic_tags",
    "start_date", "end_date", "location",
    "abstract_deadline", "paper_deadline",
    "registration_deadline", "early_bird_deadline",
    "website", "relevance_score", "relevance_note",
    "status", "last_verified", "last_change", "source_urls",
]
DEADLINE_COLS = ["abstract_deadline", "paper_deadline",
                 "registration_deadline", "early_bird_deadline"]

def ev(id, name, acronym, typ, tags, sd, ed, loc,
       abs_dl, pap_dl, reg_dl, eb_dl,
       url, score, note, status, change, srcs):
    return {
        "id": id, "name": name, "acronym": acronym, "type": typ,
        "topic_tags": tags, "start_date": sd, "end_date": ed,
        "location": loc,
        "abstract_deadline": abs_dl, "paper_deadline": pap_dl,
        "registration_deadline": reg_dl, "early_bird_deadline": eb_dl,
        "website": url, "relevance_score": score,
        "relevance_note": note, "status": status,
        "last_verified": SNAPSHOT, "last_change": change,
        "source_urls": srcs,
    }

LV = SNAPSHOT  # last_verified = today for all rows

EVENTS = [

ev('opon-2025',
   'OPON 2025 — Optical Properties of Nanostructures',
   'OPON 2025',
   'Conference',
   'integrated quantum photonics;nanophotonics',
   '2025-02-12',
   '2025-02-14',
   'Münster, Germany',
   'TBA',
   'TBA',
   'TBA',
   'TBA',
   'https://www.uni-muenster.de/Physik.FT/en/opon2025/index.html',
   2,
   'Invite-only theory workshop (AG Kuhn, not AG Schuck) that happens to rotate through Münster periodically',
   'archived',
   'actual dates found: Feb 12-14 2025, Münster; organized by AG Kuhn (theory group)/Wrocław linkage grant, invite-only — not organized by AG Schuck; series rotates cities (Wrocław/Münster/Bayreuth/Warsaw), next Münster date unpredictable',
   'original list'),
ev('benasque-qnp-2025',
   'Quantum Nanophotonics 2025',
   'Benasque QNP',
   'Workshop',
   'nanophotonics;quantum optics;single-photon sources',
   '2025-03-16',
   '2025-03-22',
   'Benasque, Spain',
   '2025-01-17',
   'n/a',
   'TBA',
   'n/a',
   'https://benasque.org/2025quantumnanophotonics/',
   5,
   'Directly on nanophotonics and single-photon sources',
   'archived',
   'year roll-over from 2025 edition',
   'https://benasque.org/2025quantumnanophotonics/'),
ev('photonics-north-2025',
   'Photonics North 2025',
   'PN 2025',
   'Conference',
   'silicon photonics;integrated quantum photonics;quantum communication',
   '2025-05-20',
   '2025-05-23',
   'Ottawa, Canada',
   'TBA',
   'TBA',
   'TBA',
   'TBA',
   'TBA',
   3,
   'Canadian photonics flagship with PIC and quantum sessions',
   'archived',
   'year roll-over from 2025 edition',
   'original list'),
ev('benasque-sqt-2025',
   'Spring School on Superconducting Qubit Technology 2025',
   'Benasque SQT',
   'Summer School',
   'quantum computing hardware;cryogenic electronics',
   '2025-05-21',
   '2025-05-30',
   'Benasque, Spain',
   'TBA',
   'n/a',
   'TBA',
   'n/a',
   'https://benasque.org/2025sqt/',
   3,
   'Cryogenic electronics for qubit control, adjacent to photonic detector systems',
   'archived',
   'year roll-over from 2025 edition',
   'https://benasque.org/2025sqt/'),
ev('optica-quantum-2025',
   'Optica Quantum 2.0 Conference and Exhibition 2025',
   'Optica Quantum 2025',
   'Conference',
   'integrated quantum photonics;quantum optics;single-photon sources;quantum communication',
   '2025-06-01',
   '2025-06-05',
   'San Francisco, CA, USA',
   'TBA',
   'TBA',
   'TBA',
   'TBA',
   'https://optica.org/events/topical_meetings/quantum/',
   5,
   'Premier global quantum photonics conference covering PICs, single photons, QKD',
   'archived',
   'year roll-over from 2025 edition',
   'https://optica.org/events/topical_meetings/quantum/'),
ev('icols-2025',
   '26th International Conference on Laser Spectroscopy',
   'ICOLS 2025',
   'Conference',
   'quantum optics;nonlinear optics',
   '2025-06-02',
   '2025-06-07',
   'Elba Island, Italy',
   '2025-01-17',
   'TBA',
   'TBA',
   'TBA',
   'https://icols2025.it/',
   3,
   'Laser spectroscopy with quantum optics relevance',
   'archived',
   'year roll-over from 2025 edition',
   'https://icols2025.it/'),
ev('ecio-2025',
   'European Conference on Integrated Optics 2025',
   'ECIO 2025',
   'Conference',
   'integrated quantum photonics;photonic integrated circuits;silicon photonics',
   '2025-06-10',
   '2025-06-12',
   'Cardiff, Wales, UK',
   'TBA',
   'TBA',
   'TBA',
   'TBA',
   'https://ecio-conference.org/',
   5,
   'Largest European dedicated integrated optics conference',
   'archived',
   'year roll-over from 2025 edition',
   'https://ecio-conference.org/'),
ev('benasque-qi-2025',
   'Quantum Information 2025',
   'Benasque QI',
   'Workshop',
   'quantum communication;quantum optics',
   '2025-06-15',
   '2025-07-04',
   'Benasque, Spain',
   'TBA',
   'n/a',
   'TBA',
   'n/a',
   'https://benasque.org/',
   3,
   'Quantum information including QKD and networking',
   'archived',
   'year roll-over from 2025 edition',
   'https://benasque.org/'),
ev('damop-2025',
   '56th APS Division of Atomic, Molecular and Optical Physics Meeting',
   'DAMOP 2025',
   'Conference',
   'quantum optics;nonlinear optics',
   '2025-06-16',
   '2025-06-20',
   'Portland, OR, USA',
   '2025-01-31',
   '2025-01-31',
   'TBA',
   'TBA',
   'https://aps.org/events/2025/atomic-molecular-optical-physics',
   3,
   'AMO physics flagship with quantum optics sessions',
   'archived',
   'year roll-over from 2025 edition',
   'https://aps.org/events/2025/atomic-molecular-optical-physics'),
ev('cewqo-2025',
   '29th Central European Workshop on Quantum Optics',
   'CEWQO 2025',
   'Workshop',
   'quantum optics;single-photon sources;quantum communication',
   '2025-06-23',
   '2025-06-27',
   'Vilnius, Lithuania',
   'TBA',
   'n/a',
   'TBA',
   'n/a',
   'https://ucan.physics.utoronto.ca/conferences/cewqo29/',
   4,
   'Dedicated European workshop on quantum optics and single-photon physics',
   'archived',
   'year roll-over from 2025 edition',
   'https://ucan.physics.utoronto.ca/conferences/cewqo29/'),
ev('cleo-europe-2025',
   'CLEO/Europe-EQEC 2025',
   'CLEO/Europe 2025',
   'Conference',
   'integrated quantum photonics;quantum optics;nonlinear optics;nanophotonics',
   '2025-06-23',
   '2025-06-27',
   'Munich, Germany',
   '2025-01-27',
   '2025-01-27',
   'TBA',
   'TBA',
   'https://cleoeurope.org/',
   5,
   'Flagship European photonics and quantum optics conference (biennial)',
   'archived',
   'year roll-over from 2025 edition',
   'https://cleoeurope.org/'),
ev('icton-2025',
   '25th International Conference on Transparent Optical Networks',
   'ICTON 2025',
   'Conference',
   'photonic integrated circuits;silicon photonics;quantum communication',
   '2025-07-06',
   '2025-07-10',
   'Barcelona, Spain',
   'TBA',
   'TBA',
   'TBA',
   'TBA',
   'https://icton2025.upc.edu/',
   3,
   'Transparent optical networks with PIC and quantum photonics tracks',
   'archived',
   'year roll-over from 2025 edition',
   'https://icton2025.upc.edu/'),
ev('ieee-sum-2025',
   'IEEE Summer Topicals Meeting Series 2025',
   'IEEE SUM 2025',
   'Conference',
   'integrated quantum photonics;silicon photonics',
   '2025-07-21',
   '2025-07-23',
   'Berlin, Germany',
   'TBA',
   'TBA',
   'TBA',
   'TBA',
   'https://ieee-sum.org/',
   3,
   'IEEE topical photonics sessions including PICs',
   'archived',
   'year roll-over from 2025 edition',
   'https://ieee-sum.org/'),
ev('qcrypt-2025',
   'QCrypt 2025',
   'QCrypt 2025',
   'Conference',
   'quantum communication;QKD;quantum networking',
   '2025-08-25',
   '2025-08-29',
   'Sanya, China',
   'TBA',
   'TBA',
   'TBA',
   'TBA',
   'https://qcrypt.net/',
   4,
   'Premier annual quantum cryptography and QKD conference',
   'archived',
   'year roll-over from 2025 edition',
   'https://qcrypt.net/'),
ev('ecoc-2025',
   '51st European Conference on Optical Communication',
   'ECOC 2025',
   'Conference',
   'photonic integrated circuits;silicon photonics;quantum communication',
   '2025-09-28',
   '2025-10-02',
   'Copenhagen, Denmark',
   'TBA',
   'TBA',
   'TBA',
   'TBA',
   'https://ecoc2025.org/',
   4,
   "Europe's biggest optical comms conference with PIC and quantum tracks",
   'archived',
   'year roll-over from 2025 edition',
   'https://ecoc2025.org/'),
ev('moc-2025',
   '30th Microoptics Conference',
   'MOC 2025',
   'Conference',
   'photonic integrated circuits;nanophotonics',
   '2025-10-12',
   '2025-10-15',
   'Tochigi, Japan',
   '2025-05-16',
   'TBA',
   'TBA',
   'TBA',
   'TBA',
   3,
   'Micro- and nano-optics with PIC sessions',
   'archived',
   'year roll-over from 2025 edition',
   'original list'),
ev('fio-2025',
   'Frontiers in Optics + Laser Science 2025',
   'FiO+LS 2025',
   'Conference',
   'quantum optics;nonlinear optics;nanophotonics',
   '2025-10-27',
   '2025-10-30',
   'Denver, CO, USA',
   'TBA',
   'TBA',
   'TBA',
   'TBA',
   'https://frontiersinoptics.com/',
   3,
   'Broad US optics conference with quantum photonics components',
   'archived',
   'year roll-over from 2025 edition',
   'https://frontiersinoptics.com/'),
ev('piers-fall-2025',
   'Photonics & Electromagnetics Research Symposium — Fall 2025',
   'PIERS Fall 2025',
   'Symposium',
   'photonic integrated circuits;nanophotonics',
   '2025-11-04',
   '2025-11-08',
   'Chiba, Japan',
   'TBA',
   'TBA',
   'TBA',
   'TBA',
   'TBA',
   2,
   'General EM/photonics symposium; peripherally relevant',
   'archived',
   'year roll-over from 2025 edition',
   'original list'),
ev('acp-2025',
   'Asia Communications and Photonics Conference 2025',
   'ACP 2025',
   'Conference',
   'photonic integrated circuits;quantum communication',
   '2025-11-05',
   '2025-11-08',
   'Jiangsu, China',
   '2025-08-01',
   'TBA',
   'TBA',
   'TBA',
   'TBA',
   3,
   'Asia-Pacific photonics flagship with quantum sessions',
   'archived',
   'year roll-over from 2025 edition',
   'original list'),
ev('ipc-2025',
   'IEEE Photonics Conference 2025',
   'IPC 2025',
   'Conference',
   'integrated quantum photonics;photonic integrated circuits;silicon photonics',
   '2025-11-09',
   '2025-11-13',
   'Singapore',
   'TBA',
   'TBA',
   'TBA',
   'TBA',
   'https://ieee-ipc.org/',
   4,
   'IEEE flagship photonics devices and integrated systems conference',
   'archived',
   'year roll-over from 2025 edition',
   'https://ieee-ipc.org/'),
ev('optima-2025',
   'Optical Communication, Photonics, Telecommunications, and Intelligent Machine Applications',
   'OPTIMA 2025',
   'Conference',
   'photonic integrated circuits',
   '2025-12-04',
   '2025-12-05',
   'Tashkent, Uzbekistan',
   'TBA',
   'TBA',
   'TBA',
   'TBA',
   'TBA',
   2,
   'Regional optics/photonics conference; limited quantum scope',
   'archived',
   'year roll-over from 2025 edition',
   'original list'),
ev('pgc-2025',
   'Photonics Global Conference 2025',
   'PGC 2025',
   'Conference',
   'photonic integrated circuits;nanophotonics',
   '2025-12-05',
   '2025-12-08',
   'Sanya, China',
   'TBA',
   'TBA',
   'TBA',
   'TBA',
   'TBA',
   2,
   'Asia-Pacific photonics conference; some PIC tracks',
   'archived',
   'year roll-over from 2025 edition',
   'original list'),
ev('icisct-2025',
   'International Conference on Information Science and Communications Technologies',
   'ICISCT 2025',
   'Conference',
   'quantum communication',
   '2025-12-26',
   '2025-12-27',
   'Kathmandu, Nepal',
   'TBA',
   'TBA',
   'TBA',
   'TBA',
   'TBA',
   2,
   'Broad ICT conference; limited photonics scope',
   'archived',
   'year roll-over from 2025 edition',
   'original list'),
ev('photonics-west-2026',
   'SPIE Photonics West 2026',
   'PW 2026',
   'Conference',
   'integrated quantum photonics;silicon photonics;nonlinear optics;single-photon sources',
   '2026-01-17',
   '2026-01-22',
   'San Francisco, CA, USA',
   '2025-07-09',
   'TBA',
   'TBA',
   'TBA',
   'https://spie.org/photonics-west',
   5,
   'SPIE flagship with Quantum West and Si-photonics tracks',
   'archived',
   'year roll-over; Photonics West 2027 now announced (Jan 30–Feb 4)',
   'https://spie.org/photonics-west'),
ev('grc-mech-quant-2026',
   'Gordon Research Conference — Mechanical Systems in the Quantum Regime 2026',
   'GRC MSQR 2026',
   'Conference',
   'optomechanics;quantum computing hardware',
   '2026-01-18',
   '2026-01-23',
   'Lucca (Barga), Italy',
   'TBA',
   'n/a',
   'TBA',
   'n/a',
   'https://www.grc.org/mechanical-systems-in-the-quantum-regime-conference/2026/',
   4,
   'Optomechanics GRC — relevant to cavity-optomechanical quantum transducers',
   'archived',
   'MAJOR CORRECTION: actual GRC dates were Jan 18-23, 2026 (not Jul 26-31 as previously recorded) — already passed; confirmed via Rakich Lab blog post',
   'https://www.grc.org/mechanical-systems-in-the-quantum-regime-conference/2026/'),
ev('qip-2026',
   '29th Quantum Information Processing Conference',
   'QIP 2026',
   'Conference',
   'quantum communication;quantum computing hardware;quantum networking',
   '2026-01-26',
   '2026-01-30',
   'Riga, Latvia',
   '2025-09-12',
   '2025-10-10',
   'TBA',
   'TBA',
   'https://qip2026.lu.lv/',
   4,
   'Premier quantum information conference; networking and photonic hardware sessions',
   'archived',
   'year roll-over; QIP 2027 Singapore announced',
   'https://qip2026.lu.lv/'),
ev('dpg-samop-2026',
   'DPG Frühjahrstagung SAMOP 2026',
   'DPG SAMOP 2026',
   'Conference',
   'quantum optics;nanophotonics;integrated quantum photonics',
   '2026-03-01',
   '2026-03-06',
   'Mainz, Germany',
   'TBA',
   'TBA',
   'TBA',
   'TBA',
   'https://mainz26.dpg-tagungen.de',
   4,
   'German physics society AMO/photonics spring meeting — easily accessible from Münster',
   'archived',
   'year roll-over; DPG SAMOP 2027 Hannover announced',
   'https://mainz26.dpg-tagungen.de'),
ev('nanolight-2026',
   'Nanolight Conference 2026',
   'Nanolight 2026',
   'Conference',
   'nanophotonics;2D-material photonics;quantum optics;plasmonics',
   '2026-03-02',
   '2026-03-06',
   'Benasque, Spain',
   '2025-12-15',
   'n/a',
   '2026-02-15',
   'n/a',
   'https://benasque.org/2026nanolight/',
   5,
   'European nanophotonics / near-field / 2D-material flagship',
   'archived',
   'year roll-over',
   'https://benasque.org/2026nanolight/'),
ev('dpg-skm-2026',
   'DPG Frühjahrstagung SKM 2026',
   'DPG SKM 2026',
   'Conference',
   'silicon photonics;nanophotonics;2D-material photonics',
   '2026-03-08',
   '2026-03-13',
   'Dresden, Germany',
   'TBA',
   'TBA',
   'TBA',
   'TBA',
   'https://dresden26.dpg-tagungen.de',
   3,
   'Condensed matter sessions on photonics materials and devices',
   'archived',
   'year roll-over',
   'https://dresden26.dpg-tagungen.de'),
ev('ofc-2026',
   'Optical Fiber Communication Conference 2026',
   'OFC 2026',
   'Conference',
   'photonic integrated circuits;silicon photonics;quantum communication',
   '2026-03-15',
   '2026-03-19',
   'Los Angeles, CA, USA',
   'TBA',
   'TBA',
   'TBA',
   'TBA',
   'https://ofcconference.org/',
   4,
   "World's largest optical comms conference with PIC and quantum networking sessions",
   'archived',
   'year roll-over; OFC 2027 Los Angeles Mar 7-11 announced',
   'https://ofcconference.org/'),
ev('aps-march-2026',
   'APS Global Physics Summit 2026',
   'APS 2026',
   'Conference',
   'quantum optics;quantum computing hardware;integrated quantum photonics',
   '2026-03-16',
   '2026-03-20',
   'Denver, CO, USA',
   '2025-10-31',
   '2025-10-31',
   'TBA',
   'TBA',
   'https://summit.aps.org/',
   4,
   'Largest physics meeting; major quantum photonics and computing sessions',
   'archived',
   'year roll-over; confirmed as joint March+April Global Physics Summit; APS 2027 Atlanta Apr 11-16',
   'https://summit.aps.org/; https://march.aps.org/'),
ev('owtnm',
   '32nd OWTNM — Optical Wave & Waveguide Theory and Modelling Workshop',
   'OWTNM',
   'Workshop',
   'photonic integrated circuits;nanophotonics',
   '2026-04-08',
   '2026-04-10',
   'Lausanne, Switzerland',
   'TBA',
   'n/a',
   'TBA',
   'n/a',
   'https://owtnm26.epfl.ch/',
   3,
   'Waveguide modelling workshop relevant to PIC simulation',
   'archived',
   'OWTNM 32nd ed. actual dates found (Apr 8-10, Lausanne/EPFL) — already passed; annual series, 2027 not yet announced',
   'original list'),
ev('spie-pe-2026',
   'SPIE Photonics Europe 2026',
   'SPIE PE 2026',
   'Conference',
   'integrated quantum photonics;silicon photonics;nanophotonics',
   '2026-04-12',
   '2026-04-16',
   'Strasbourg, France',
   'TBA',
   'TBA',
   'TBA',
   'TBA',
   'https://spie.org/photonics-europe',
   5,
   'Major European SPIE photonics conference with quantum integrated sessions',
   'archived',
   'year roll-over',
   'https://spie.org/photonics-europe'),
ev('ieee-siphotonics-2026',
   'IEEE Silicon Photonics Conference 2026',
   'IEEE SiPho 2026',
   'Conference',
   'silicon photonics;photonic integrated circuits;III-V on Si',
   '2026-04-13',
   '2026-04-15',
   'Ottawa, ON, Canada',
   '2025-10-03',
   'TBA',
   'TBA',
   'TBA',
   'https://ieee-siphotonics.org/',
   5,
   'Dedicated silicon photonics conference — direct relevance to PICs',
   'archived',
   'year roll-over',
   'https://ieee-siphotonics.org/'),
ev('ieee-qpain-2026',
   'IEEE 2nd International Conference on Quantum Photonics, AI & Networking',
   'IEEE QPAIN 2026',
   'Conference',
   'integrated quantum photonics;quantum networking',
   '2026-04-16',
   '2026-04-18',
   'Chattogram, Bangladesh',
   'TBA',
   'TBA',
   'TBA',
   'TBA',
   'https://qpain.org/',
   3,
   'Quantum photonics and networking conference (IEEE-sponsored)',
   'archived',
   'year roll-over',
   'https://qpain.org/'),
ev('inp-webinar-2026',
   'Webinar on InP platform for NIR and MIR applications',
   'InP Webinar',
   'Seminar',
   'photonic integrated circuits;III-V on Si',
   '2026-04-17',
   '2026-04-17',
   'Online',
   'TBA',
   'n/a',
   'TBA',
   'n/a',
   'https://inphomir.eu/1st-webinar/',
   4,
   'III-V InP PIC platform — directly relevant to quantum light-source integration',
   'archived',
   'year roll-over',
   'https://inphomir.eu/1st-webinar/'),
ev('eftf-2026',
   'European Frequency and Time Forum 2026',
   'EFTF 2026',
   'Conference',
   'quantum optics;quantum communication',
   '2026-04-20',
   '2026-04-23',
   'Noordwijk, The Netherlands',
   'TBA',
   'TBA',
   'TBA',
   'TBA',
   'https://www.eftf.org/home',
   2,
   'Frequency/time standards; quantum photonic metrology peripherally relevant',
   'archived',
   'year roll-over',
   'https://www.eftf.org/home'),
ev('opic',
   'OPIC 2026 — Optics & Photonics International Congress',
   'OPIC',
   'Conference',
   'integrated quantum photonics;quantum optics;nanophotonics',
   '2026-04-20',
   '2026-04-24',
   'Yokohama (Pacifico Yokohama), Japan',
   'TBA',
   'TBA',
   'TBA',
   'TBA',
   'https://opicon.jp/',
   3,
   'Japanese international photonics congress with quantum tracks',
   'archived',
   'OPIC 2026 actual dates found (Apr 20-24, Yokohama) — already passed; annual series, 2027 not yet announced',
   'original list'),
ev('pic-international-2026',
   'PIC International 2026',
   'PIC International',
   'Conference',
   'photonic integrated circuits;silicon photonics',
   '2026-04-20',
   '2026-04-22',
   'Brussels, Belgium',
   'n/a',
   'n/a',
   'TBA',
   'TBA',
   'https://picinternational.net/',
   4,
   'Leading PIC industry conference (11th ed.), distinct from IEEE Photonics Conference, includes a quantum-technologies theme track',
   'archived',
   'new entry (already passed at time of discovery, Apr 2026); PIC industry conference, next edition already tracked as pic-international-2027',
   'https://picinternational.net/; https://picmagazine.net/article/123844/PIC_International_2026_agenda_announced'),
ev('spie-ds-2026',
   'SPIE Defense + Security 2026',
   'SPIE D+S 2026',
   'Conference',
   'single-photon sources;quantum communication',
   '2026-04-26',
   '2026-04-30',
   'National Harbor, MD, USA',
   'TBA',
   'TBA',
   'TBA',
   'TBA',
   'https://spie.org/defense-and-commercial-sensing',
   2,
   'Defense photonics with some single-photon sensing sessions',
   'archived',
   'year roll-over',
   'https://spie.org/defense-and-commercial-sensing'),
ev('bqit-2026',
   'Bristol Quantum Information Technologies Workshop 2026',
   'BQIT 2026',
   'Workshop',
   'integrated quantum photonics;quantum communication;quantum computing hardware',
   '2026-04-27',
   '2026-04-29',
   'Bristol, UK',
   'TBA',
   'n/a',
   'TBA',
   'n/a',
   'https://www.bristol.ac.uk/qet-labs/events/bqit-workshop/',
   5,
   'UK quantum photonics workshop — PICs, single photons, quantum networking',
   'archived',
   'year roll-over',
   'https://www.bristol.ac.uk/qet-labs/events/bqit-workshop/'),
ev('quantumatter-2026',
   'QUANTUMatter 2026',
   'QUANTU 2026',
   'Conference',
   'quantum computing hardware;quantum optics;nanophotonics',
   '2026-04-27',
   '2026-04-30',
   'Barcelona, Spain',
   '2026-02-11',
   'n/a',
   '2026-03-06',
   '2026-02-23',
   'https://www.quantumconf.eu/2026/',
   3,
   'Quantum materials and devices, including photonic quantum systems',
   'archived',
   'year roll-over',
   'https://www.quantumconf.eu/2026/'),
ev('ampd-2026',
   'Annual Meeting Photonic Devices 2026',
   'AMPD 2026',
   'Conference',
   'photonic integrated circuits;nanophotonics',
   '2026-04-28',
   '2026-04-30',
   'TBA',
   'TBA',
   'TBA',
   'TBA',
   'TBA',
   'https://www.zib.de/workshop-photonic-devices/',
   4,
   "German photonic devices annual meeting — directly relevant to group's fabrication work",
   'archived',
   'year roll-over',
   'https://www.zib.de/workshop-photonic-devices/'),
ev('cleo-2026',
   'Conference on Lasers and Electro-Optics 2026',
   'CLEO 2026',
   'Conference',
   'integrated quantum photonics;quantum optics;nonlinear optics;silicon photonics;single-photon sources',
   '2026-05-17',
   '2026-05-21',
   'Charlotte, NC, USA',
   '2025-11-18',
   'n/a',
   'TBA',
   'TBA',
   'https://cleoconference.org/',
   5,
   'Premier US laser/photonics conference; major IQP, Si-PIC and quantum optics sessions',
   'archived',
   'year roll-over; CLEO 2027 confirmed May 2-6, Long Beach CA',
   'https://cleoconference.org/; https://cleoconference.org/registration-2026/'),
ev('damop-2026',
   '57th APS Division of Atomic, Molecular and Optical Physics Meeting',
   'DAMOP 2026',
   'Conference',
   'quantum optics;nonlinear optics;single-photon sources',
   '2026-06-01',
   '2026-06-05',
   'Providence, RI, USA',
   'TBA',
   'TBA',
   'TBA',
   'TBA',
   'https://aps.org/events/2026/damop-meeting-2026',
   3,
   'AMO physics flagship with quantum optics and single-photon sessions',
   'archived',
   'year roll-over; DAMOP 2027 (58th) confirmed Chicago, IL, exact dates TBA',
   'https://aps.org/events/2026/damop-meeting-2026'),
ev('issw-2026',
   'International SPAD Sensor Workshop 2026',
   'ISSW 2026',
   'Workshop',
   'single-photon sources;nanophotonics',
   '2026-06-01',
   '2026-06-04',
   'Seoul, South Korea',
   'TBA',
   'TBA',
   'TBA',
   'TBA',
   'https://issw2026.yonsei.ac.kr/',
   2,
   'Biennial workshop on SPAD single-photon detectors and imaging sensors — adjacent detector-technology community, more industrial-imaging focused',
   'archived',
   'new entry (already passed at time of discovery, Jun 2026); biennial SPAD workshop, next edition (2028) not yet announced',
   'https://issw2026.yonsei.ac.kr/; https://imagesensors.org/call-for-papers-for-the-2026-international-spad-sensor-workshop/'),
ev('photonics-north-2026',
   'Photonics North 2026',
   'PN 2026',
   'Conference',
   'silicon photonics;integrated quantum photonics;quantum communication',
   '2026-06-02',
   '2026-06-05',
   'Québec City, QC, Canada',
   'TBA',
   'TBA',
   'TBA',
   'TBA',
   'TBA',
   3,
   'Canadian national photonics conference with PIC and quantum sessions',
   'archived',
   'year roll-over; 2026 host confirmed as Québec City (Jun 2-5); series now appears annual not biennial',
   'original list'),
ev('cargese-qt-2026',
   'Summer School on Quantum Technologies for Computation and Communication',
   'QT4CC 2026',
   'Summer School',
   'quantum communication;quantum computing hardware;quantum networking',
   '2026-06-08',
   '2026-06-20',
   'Cargèse (Corsica), France',
   'TBA',
   'n/a',
   'TBA',
   'n/a',
   'https://qt4cc.sciencesconf.org/',
   4,
   "PhD summer school on quantum computation and communication — ideal for group's PhD students",
   'archived',
   'year roll-over; inaugural GdR TeQ school, no confirmed recurring cadence yet',
   'https://qt4cc.sciencesconf.org/; https://gdr-teq.cnrs.fr/cevent/629/'),
ev('spie-pfq-2026',
   'SPIE Photonics for Quantum 2026',
   'PfQ 2026',
   'Conference',
   'integrated quantum photonics;single-photon sources;quantum communication;quantum computing hardware',
   '2026-06-08',
   '2026-06-11',
   'Waterloo, ON, Canada',
   '2026-03-01',
   'n/a',
   'TBA',
   'TBA',
   'https://spie.org/conferences-and-exhibitions/photonics-for-quantum',
   5,
   'Dedicated quantum photonics conference — bullseye for AG Schuck',
   'archived',
   'year roll-over; PfQ 2027 not yet announced (confirmed annual series, Waterloo)',
   'https://spie.org/PFQ26/conferencedetails/photonics-for-quantum'),
ev('grc-quantum-science-2026',
   'Gordon Research Conference — Quantum Science 2026',
   'GRC QS 2026',
   'Conference',
   'quantum optics;quantum computing hardware;quantum communication;integrated quantum photonics',
   '2026-06-14',
   '2026-06-19',
   'Easton, MA, USA',
   'TBA',
   'n/a',
   '2026-06-28',
   'n/a',
   'https://www.grc.org/quantum-science-conference/2026/',
   4,
   'GRC on quantum science covering photonic quantum systems and quantum information',
   'archived',
   'year roll-over; GRC Quantum Science is biennial (even years), 2028 page not yet published',
   'https://www.grc.org/quantum-science-conference/2026/'),
ev('icap-2026',
   '29th International Conference on Atomic Physics',
   'ICAP 2026',
   'Conference',
   'quantum optics;nonlinear optics',
   '2026-06-14',
   '2026-06-19',
   'Wuhan, China',
   'TBA',
   'TBA',
   'TBA',
   'TBA',
   'https://www.icap29.com/home.html',
   3,
   'Atomic physics conference with quantum optics and light-matter interaction sessions',
   'archived',
   'year roll-over; ICAP is triennial, ICAP30 (~2029) not yet announced',
   'https://www.icap29.com/home.html'),
ev('islc-2026',
   '30th International Semiconductor Laser Conference',
   'ISLC 2026',
   'Conference',
   'single-photon sources;III-V on Si;photonic integrated circuits',
   '2026-06-14',
   '2026-06-17',
   'Tampere, Finland',
   '2026-02-05',
   'TBA',
   'TBA',
   'TBA',
   'https://events.tuni.fi/islc2026/',
   4,
   'III-V semiconductor laser conference — key for quantum light source development',
   'archived',
   'year roll-over; ISLC is biennial, next (31st, 2028) not yet announced',
   'https://events.tuni.fi/islc2026/; https://ieeephotonics.org/event/2026-30th-international-semiconductor-laser-conference-islc/'),
ev('ecio-2026',
   'European Conference on Integrated Optics 2026',
   'ECIO 2026',
   'Conference',
   'integrated quantum photonics;photonic integrated circuits;silicon photonics;nanophotonics',
   '2026-06-15',
   '2026-06-17',
   'Zürich, Switzerland',
   'TBA',
   'TBA',
   '2026-06-01',
   '2026-05-11',
   'https://ecio-conference.org/',
   5,
   'Largest European integrated optics conference — core relevance for AG Schuck',
   'archived',
   'year roll-over; ECIO confirmed annual (4 consecutive yearly editions); ECIO 2027 not yet announced',
   'https://www.ecio-conference.org/; https://www.ecio-conference.org/deadlines/'),
ev('icop-2026',
   'Italian Conference on Optics and Photonics 2026',
   'ICOP 2026',
   'Conference',
   'integrated quantum photonics;quantum optics;nanophotonics',
   '2026-06-15',
   '2026-06-17',
   "L'Aquila, Italy",
   'TBA',
   'TBA',
   'TBA',
   'TBA',
   'https://www.icop2026.it/',
   3,
   'Italian national photonics conference with quantum tracks',
   'archived',
   'year roll-over; ICOP is biennial (SIOF), next edition (~2028) not yet announced',
   'https://www.icop2026.it/'),
ev('optica-quantum-2026',
   'Optica Quantum 2.0 Conference and Exhibition 2026',
   'Optica Quantum 2026',
   'Conference',
   'integrated quantum photonics;quantum optics;single-photon sources;quantum communication;quantum computing hardware',
   '2026-06-15',
   '2026-06-18',
   'Glasgow, UK',
   '2026-02-10',
   'n/a',
   '2026-05-29',
   'n/a',
   'https://www.optica.org/events/topical_meetings/quantum/',
   5,
   'Premier quantum photonics conference spanning PICs, detectors, QKD, and hardware',
   'archived',
   'year roll-over; confirmed biennial (2022/2024/2026); Optica Quantum 2028 not yet announced',
   'https://www.optica.org/events/topical_meetings/quantum/; https://www.optica.org/events/topical_meetings/quantum/registration/'),
ev('ccw-london-2026',
   'Critical Communications World London 2026',
   'CCW 2026',
   'Conference',
   'quantum communication;quantum networking',
   '2026-06-16',
   '2026-06-18',
   'London, UK',
   'TBA',
   'TBA',
   'TBA',
   'TBA',
   'https://www.critical-communications-world.com/',
   2,
   'Critical comms industry event; QKD sessions of marginal relevance',
   'archived',
   'year roll-over; CCW 2027 confirmed May 11-13, RAI Amsterdam',
   'https://www.critical-communications-world.com/call-for-content'),
ev('benasque-qsi-2026',
   'Quantum Science: Implementations 2026',
   'Benasque QSI',
   'Workshop',
   'integrated quantum photonics;quantum computing hardware;quantum communication',
   '2026-06-21',
   '2026-07-04',
   'Benasque, Spain',
   'TBA',
   'n/a',
   'TBA',
   'n/a',
   'https://benasque.org/',
   4,
   'Benasque workshop on quantum implementations including photonic platforms',
   'archived',
   'year roll-over; Benasque QSI is biennial (2020/2022/2024/2026), 2028 not yet announced',
   'https://benasque.org/; https://www.benasque.org/new_general/cgi-bin/years.pl?ano=2026'),
ev('egas-2026',
   '57th Conference of the European Group on Atomic Systems',
   'EGAS 2026',
   'Conference',
   'quantum optics;nonlinear optics',
   '2026-06-21',
   '2026-06-25',
   'Toruń, Poland',
   'TBA',
   'TBA',
   'TBA',
   'TBA',
   'https://egas57.org/',
   3,
   'European atomic systems conference with quantum optics and light-matter sessions',
   'archived',
   'year roll-over; EGAS is annual, EGAS 58 (2027) host not yet announced',
   'https://egas57.org/'),
ev('iqt-nordics-2026',
   'IQT Nordics 2026 — Quantum Technology in a Changing World',
   'IQT Nordics 2026',
   'Conference',
   'quantum communication;quantum computing hardware;integrated quantum photonics',
   '2026-06-22',
   '2026-06-24',
   'Oslo, Norway',
   'TBA',
   'n/a',
   'TBA',
   'TBA',
   'https://iqtevent.com/nordics/',
   3,
   'Nordic quantum industry conference with hardware and QKD sessions',
   'archived',
   'year roll-over; IQT Nordics 2027 confirmed to return to Copenhagen, exact dates TBA',
   'https://iqtevent.com/nordics/; https://www.oslomet.no/en/about/events/iqt-nordics-2026'),
ev('les-houches-pa-2026',
   'Photons & Atoms 2026 — Les Houches Doctoral School',
   'Les Houches PA 2026',
   'Summer School',
   'quantum optics;nonlinear optics;integrated quantum photonics;single-photon sources',
   '2026-06-22',
   '2026-07-03',
   'Les Houches, France',
   'TBA',
   'n/a',
   'TBA',
   'n/a',
   'https://photon-atoms-26.leshouches.science/',
   5,
   'Leading European doctoral school on photons, quantum gases and quantum technologies',
   'archived',
   "year roll-over; cadence irregular (~3yr, not a fixed annual series); 2027 Les Houches program has no 'Photons & Atoms'-branded session",
   'https://photon-atoms-26.leshouches.science/; https://first-tf.com/doctoral-training-on-atoms-and-photons-ecole-de-physique-des-houches-france-june-22nd-to-july-3rd-2026/'),
ev('quantum-tech-world-2026',
   'Quantum.Tech World 2026',
   'Q.Tech World 2026',
   'Conference',
   'quantum computing hardware;quantum communication;integrated quantum photonics',
   '2026-06-25',
   '2026-06-26',
   'Boston, MA, USA',
   'TBA',
   'n/a',
   'TBA',
   'TBA',
   'https://www.alphaevents.com/events-quantumtechus',
   2,
   'Industry quantum technology event; limited deep-science content',
   'archived',
   'year roll-over; Quantum.Tech World 2027 confirmed May 25-26, Boston (8th ed., co-located with Compute.Tech 2027)',
   'https://www.alphaevents.com/events-quantumtechus'),
ev('oecc-2026',
   '31st OptoElectronics and Communications Conference',
   'OECC 2026',
   'Conference',
   'photonic integrated circuits;silicon photonics;quantum communication',
   '2026-06-28',
   '2026-07-02',
   'Busan, South Korea',
   'TBA',
   'TBA',
   'TBA',
   'TBA',
   'TBA',
   3,
   'Asia-Pacific optoelectronics and comms conference with PIC sessions',
   'archived',
   'year roll-over; OECC is annual, rotates Asia-Pacific hosts; 2027 host not yet announced',
   'original list'),
ev('quantum-korea-2026',
   'Quantum Korea 2026',
   'Quantum Korea 2026',
   'Conference',
   'quantum computing hardware;quantum communication;integrated quantum photonics',
   '2026-07-02',
   '2026-07-04',
   'Seoul, South Korea',
   'TBA',
   'n/a',
   'TBA',
   'TBA',
   'https://quantum-korea.kr/en/main',
   2,
   'Government-organised Korean quantum technology showcase',
   'archived',
   'year roll-over; Quantum Korea is annual (MSIT-organized), 2027 not yet announced',
   'https://quantum-korea.kr/en/main'),
ev('spw-2026',
   '12th Single Photon Workshop',
   'SPW 2026',
   'Workshop',
   'single-photon sources;SNSPDs;quantum optics;quantum communication',
   '2026-07-06',
   '2026-07-10',
   'Naples, Italy',
   '2026-03-25',
   'n/a',
   'TBA',
   '2026-06-28',
   'https://spw2026.org/',
   5,
   "THE dedicated single-photon workshop — central to AG Schuck's detector and source work",
   'cfp_closed',
   'abstract deadline confirmed 2026-03-25 (passed); early-bird registration confirmed 2026-06-28 (passed)',
   'https://spw2026.org/; https://iqnhub.org/2026-single-photon-workshop-registration-open/'),
ev('icton-2026',
   '26th International Conference on Transparent Optical Networks',
   'ICTON 2026',
   'Conference',
   'photonic integrated circuits;silicon photonics;quantum communication',
   '2026-07-12',
   '2026-07-16',
   'Prague, Czech Republic',
   'TBA',
   '2026-03-31',
   '2026-06-30',
   '2026-05-31',
   'https://icton2026.ufe.cz/',
   3,
   'Transparent optical networks with PIC and quantum photonics tracks',
   'cfp_closed',
   'corrected official website to icton2026.ufe.cz (file had co-organizer institutional page); paper deadline 2026-03-31 passed, CFP closed; registration late/onsite window closes 2026-06-30',
   'https://icton2026.ufe.cz/; https://www.gov.pl/web/instytut-lacznosci/icton-2026'),
ev('ieee-sum-2026',
   'IEEE Summer Topicals Meeting Series 2026',
   'IEEE SUM 2026',
   'Conference',
   'photonic integrated circuits;silicon photonics;integrated quantum photonics',
   '2026-07-13',
   '2026-07-15',
   'Tulum, Mexico',
   '2026-02-23',
   '2026-02-23',
   'TBA',
   'TBA',
   'https://ieee-sum.org/',
   3,
   'IEEE focused topical photonics sessions',
   'cfp_closed',
   'submission deadline confirmed 2026-02-23 (passed) — conference program already finalized',
   'https://ieee-sum.org/'),
ev('meta-2026-dublin',
   'META 2026 — 16th International Conference on Metamaterials, Photonic Crystals and Plasmonics',
   'META 2026',
   'Conference',
   'nanophotonics;plasmonics',
   '2026-07-14',
   '2026-07-17',
   'Dublin, Ireland',
   '2026-02-13',
   'n/a',
   'TBA',
   '2026-04-24',
   'https://metaconferences.org/META26/',
   4,
   'Major long-running metamaterials/plasmonics/nanophotonics conference with dedicated quantum-photonics sessions',
   'cfp_closed',
   'new entry',
   'https://metaconferences.org/META26/index.php/META/dates'),
ev('grc-plasmonics-nano-2026',
   'Gordon Research Conference — Plasmonics and Nanophotonics 2026',
   'GRC PNP 2026',
   'Conference',
   'nanophotonics;plasmonics;quantum optics;2D-material photonics',
   '2026-07-19',
   '2026-07-24',
   'Newry, ME, USA',
   'TBA',
   'n/a',
   '2026-06-21',
   'n/a',
   'https://www.grc.org/plasmonics-and-nanophotonics-conference/2026/',
   5,
   'GRC on quantum nanophotonics, plasmonics and 2D photonics — highly relevant to AG Schuck',
   'cfp_closed',
   'application deadline 2026-06-21 has passed; late applicants only via chair approval/waitlist',
   'https://www.grc.org/plasmonics-and-nanophotonics-conference/2026/'),
ev('cewqo-2026',
   '30th Central European Workshop on Quantum Optics',
   'CEWQO30 2026',
   'Workshop',
   'quantum optics;single-photon sources;nonlinear optics;integrated quantum photonics',
   '2026-07-20',
   '2026-07-24',
   'Erlangen, Germany',
   'TBA',
   'n/a',
   'TBA',
   'n/a',
   'https://www.lightmatter.fau.de/2026/04/cewqo30-the-30th-central-european-workshop-on-quantum-optics-2026/',
   5,
   'European quantum optics workshop co-hosted by FAU/MPL Erlangen — close to Münster',
   'upcoming',
   'new entry; Jul 20-24 Erlangen, hosted by Chekhova/Marquardt groups',
   'https://www.lightmatter.fau.de/2026/04/cewqo30-the-30th-central-european-workshop-on-quantum-optics-2026/; https://www.oqt.nat.fau.de/events/'),
ev('apc-2026',
   'Optica Advanced Photonics Congress 2026',
   'APC 2026',
   'Conference',
   'integrated quantum photonics;nonlinear optics;nanophotonics',
   '2026-07-26',
   '2026-07-30',
   'Long Beach, CA, USA',
   'TBA',
   '2026-07-07',
   'TBA',
   'TBA',
   'https://www.optica.org/events/congress/advanced_photonics_congress/',
   4,
   'Optica congress including nonlinear photonics, waveguides and integrated circuits',
   'cfp_open',
   'venue confirmed: Long Beach, CA (Hilton Long Beach); regular CFP closed, postdeadline paper window open through 2026-07-07',
   'https://www.optica.org/events/congress/advanced_photonics_congress/'),
ev('ipr-2026',
   'Integrated Photonics Research, Silicon and Nanophotonics 2026',
   'IPR 2026',
   'Conference',
   'integrated quantum photonics;photonic integrated circuits;silicon photonics;nanophotonics',
   '2026-07-26',
   '2026-07-30',
   'Long Beach, CA, USA',
   'TBA',
   '2026-07-07',
   'TBA',
   'TBA',
   'https://www.optica.org/events/congress/advanced_photonics_congress/program/integrated_photonics_research_silicon_and_nanophot/',
   5,
   "Optica's dedicated integrated/nanophotonics topical meeting, with an explicit integrated nonlinear-and-quantum-optics track; co-located with APC 2026",
   'cfp_open',
   'new entry; co-located with apc-2026, distinct topical track',
   'https://www.optica.org/events/congress/advanced_photonics_congress/program/integrated_photonics_research_silicon_and_nanophot/'),
ev('mpi-frontiers-light-matter-2026',
   'Workshop on the Frontiers in Light-Matter Interactions 2026',
   'MPI FLMI',
   'Workshop',
   'nanophotonics;plasmonics',
   '2026-07-26',
   '2026-08-01',
   'Germany (Max Planck Institute)',
   'n/a',
   'n/a',
   'TBA',
   'TBA',
   'https://plan.events.mpg.de/event/676/',
   4,
   "MPI-hosted workshop on nanophotonics/metasurfaces/near-field nano-optics, directly overlapping the group's nanophotonics interests",
   'upcoming',
   'new entry',
   'https://plan.events.mpg.de/event/676/'),
ev('lake-como-ufqp-2026',
   'New Frontiers in Ultrafast Quantum Optics — Lake Como School',
   'UFQP 2026',
   'Summer School',
   'quantum optics;nonlinear optics;single-photon sources',
   '2026-07-27',
   '2026-07-31',
   'Como, Italy',
   '2026-05-31',
   'n/a',
   'TBA',
   'n/a',
   'https://ufqp.lakecomoschool.org/',
   4,
   'Summer school on ultrafast quantum optics — photon correlations and time-frequency entanglement',
   'cfp_closed',
   'application deadline 2026-05-31 confirmed passed; school (max 40 participants) still listed as scheduled, no cancellation signal',
   'https://ufqp.lakecomoschool.org/; https://www.quantiki.org/conference/summer-school-new-frontiers-ultrafast-quantum-optics'),
ev('benasque-ftqt-2026',
   'Fault-Tolerant Quantum Technologies 2026',
   'Benasque FTQT',
   'Workshop',
   'quantum computing hardware;quantum optics',
   '2026-08-03',
   '2026-08-14',
   'Benasque, Spain',
   'TBA',
   'n/a',
   'TBA',
   'n/a',
   'https://www.benasque.org/2026ftqt/',
   2,
   'Biennial QEC/fault-tolerance workshop sponsored by photonic-quantum-computing firms (PsiQuantum, Xanadu)',
   'upcoming',
   'new entry',
   'https://www.benasque.org/2026ftqt/'),
ev('cargese-topfrac-2026',
   'Topology and Fractionalisation in Quantum Matter and Synthetic Platforms',
   'TopFrac 2026',
   'Summer School',
   'nanophotonics;quantum optics',
   '2026-08-03',
   '2026-08-15',
   'Cargèse, France',
   '2026-04-28',
   'n/a',
   '2026-06-26',
   'n/a',
   'https://topfrac-cargese.sciencesconf.org/',
   3,
   'CECAM/IESC school on topological and synthetic quantum platforms, incl. photonic/synthetic-dimension simulators',
   'upcoming',
   'new entry',
   'https://topfrac-cargese.sciencesconf.org/'),
ev('ieee-rapid-2026',
   'IEEE Research and Applications of Photonics in Defense 2026',
   'IEEE RAPID 2026',
   'Conference',
   'single-photon sources;quantum communication',
   '2026-08-05',
   '2026-08-07',
   'Miramar Beach, FL, USA',
   'TBA',
   '2026-02-16',
   'TBA',
   'TBA',
   'https://ieee-rapid.org/',
   2,
   'Defense photonics; some single-photon sensing sessions',
   'cfp_closed',
   'paper submission deadline confirmed 2026-02-16 (passed)',
   'https://ieee-rapid.org/'),
ev('benasque-qels-2026',
   'Quantum Engineering of Levitated Systems 2026',
   'Benasque QELS',
   'Workshop',
   'optomechanics;nanophotonics;quantum optics',
   '2026-08-16',
   '2026-08-22',
   'Benasque, Spain',
   'TBA',
   'n/a',
   'TBA',
   'n/a',
   'https://www.benasque.org/2026qels/',
   3,
   '10th-anniversary workshop at the interface of quantum optics and nanophotonics (levitated optomechanics)',
   'upcoming',
   'new entry',
   'https://www.benasque.org/2026qels/; https://www.quantiki.org/conference/quantum-engineering-levitated-systems'),
ev('cargese-metaquantm-2026',
   'MetaQuantM 2026: Creation and Manipulation of New States of Metastable Quantum Matter',
   'MetaQuantM 2026',
   'Summer School',
   'quantum optics;nanophotonics',
   '2026-08-17',
   '2026-08-29',
   'Cargèse, France',
   'TBA',
   'n/a',
   'TBA',
   'n/a',
   'https://metaquantm.ijs.si/',
   3,
   'Covers polariton condensates, strong light-matter coupling and non-Hermitian quantum-optical dynamics',
   'upcoming',
   'new entry',
   'https://metaquantm.ijs.si/'),
ev('spie-op-2026',
   'SPIE Optics + Photonics 2026',
   'SPIE O+P 2026',
   'Conference',
   'integrated quantum photonics;nanophotonics;quantum optics;single-photon sources',
   '2026-08-23',
   '2026-08-27',
   'San Diego, CA, USA',
   'TBA',
   'TBA',
   'TBA',
   'TBA',
   'https://spie.org/optics-and-photonics',
   4,
   'SPIE major annual meeting with quantum nanophotonics and quantum technologies tracks',
   'upcoming',
   'no change',
   'https://spie.org/optics-and-photonics'),
ev('eosam-2026',
   'European Optical Society Annual Meeting 2026',
   'EOSAM 2026',
   'Conference',
   'integrated quantum photonics;nanophotonics;nonlinear optics',
   '2026-08-24',
   '2026-08-28',
   'Tampere, Finland',
   '2026-04-14',
   'TBA',
   'TBA',
   '2026-06-15',
   'https://www.europeanoptics.org/events/eos/eosam2026.html',
   4,
   'EOS flagship European photonics meeting with strong quantum photonics programme',
   'cfp_closed',
   'main abstract deadline 2026-04-14 and early-bird 2026-06-15 both passed; late/post-deadline poster window remains open through 2026-07-15',
   'https://www.europeanoptics.org/events/eos/eosam2026.html'),
ev('qcrypt-2026',
   'QCrypt 2026',
   'QCrypt 2026',
   'Conference',
   'quantum communication;QKD;quantum networking',
   '2026-08-24',
   '2026-08-28',
   'Ottawa, Canada',
   'TBA',
   '2026-03-13',
   'TBA',
   'TBA',
   'https://qcrypt.net/2026/',
   4,
   'Premier annual QKD and quantum cryptography conference',
   'cfp_closed',
   'talk submission deadline 2026-03-13 and poster deadline 2026-05-01 both confirmed passed; venue: Learning Crossroads (CRX), University of Ottawa',
   'https://qcrypt.net/2026/'),
ev('isopc-erice-2026',
   'International School on Physical Computing — Metaphotonics and Optical Neural Networks',
   'ISOPC 2026',
   'Summer School',
   'integrated quantum photonics;nanophotonics;photonic integrated circuits',
   '2026-08-27',
   '2026-08-30',
   'Erice, Italy',
   '2026-05-31',
   'n/a',
   'TBA',
   'n/a',
   'https://www.lso.uni-hannover.de/en/isopc',
   5,
   'Ettore Majorana Foundation school directed by Calà Lesina & Pernice, directly on metaphotonics, integrated photonic platforms and optical neural networks',
   'upcoming',
   'new entry',
   'https://www.lso.uni-hannover.de/en/isopc; https://konferenz.uni-hannover.de/event/222/'),
ev('tqc-2026',
   'Theory of Quantum Computation, Communication and Cryptography 2026',
   'TQC 2026',
   'Conference',
   'quantum communication;quantum computing hardware;quantum networking',
   '2026-08-31',
   '2026-09-04',
   'Sherbrooke, QC, Canada',
   '2026-02-01',
   '2026-02-01',
   'TBA',
   '2026-06-28',
   'https://tqc-conference.org/2026/',
   3,
   'Theory conference for quantum communication, computation and cryptography',
   'cfp_closed',
   'main submission deadline 2026-02-01 (AoE) and early-bird registration 2026-06-28 both confirmed passed; poster-only track closed 2026-04-20',
   'https://tqc-conference.org/2026/'),
ev('photon-2026-iop',
   'Photon 2026',
   'Photon 2026',
   'Conference',
   'quantum optics;nonlinear optics;quantum communication',
   '2026-09-01',
   '2026-09-04',
   'Newcastle upon Tyne, UK',
   '2026-05-15',
   'n/a',
   '2026-08-27',
   '2026-06-30',
   'https://www.photon.org.uk/',
   4,
   'Biennial IOP conference jointly run by the Quantum Optics, Quantum Electronics & Photonics, and Quantum Information groups',
   'cfp_closed',
   'new entry',
   'https://www.photon.org.uk/; https://www.iop.org/events/photon-2026'),
ev('asc-2026',
   'Applied Superconductivity Conference 2026',
   'ASC 2026',
   'Conference',
   'SNSPDs;cryogenic electronics;single-photon sources',
   '2026-09-06',
   '2026-09-11',
   'Pittsburgh, PA, USA',
   '2026-02-02',
   'TBA',
   '2026-07-31',
   '2026-07-31',
   'https://appliedsuperconductivity.org/asc2026/',
   4,
   'Premier superconductivity conference with major SNSPD and cryogenic electronics sessions',
   'cfp_closed',
   'abstract deadline (extended) 2026-02-02 confirmed passed; early/advance registration deadline confirmed 2026-07-31 (upcoming)',
   'https://appliedsuperconductivity.org/asc2026/'),
ev('inphomir-school-2026',
   'INPHOMIR Photonics School 2026',
   'INPHOMIR School',
   'Summer School',
   'photonic integrated circuits;III-V on Si',
   '2026-09-07',
   '2026-09-11',
   'Bari, Italy',
   'TBA',
   'n/a',
   'TBA',
   'n/a',
   'https://inphomir.eu/inphomir-school-program/',
   4,
   'Dedicated InP/III-V photonics school for NIR/MIR applications',
   'upcoming',
   'no change',
   'https://inphomir.eu/inphomir-school-program/'),
ev('ieee-qce26',
   'IEEE Quantum Week 2026',
   'QCE26',
   'Conference',
   'quantum computing hardware;quantum communication;integrated quantum photonics',
   '2026-09-13',
   '2026-09-18',
   'Toronto, ON, Canada',
   'TBA',
   '2026-04-27',
   'TBA',
   'TBA',
   'https://qce.quantum.ieee.org/2026/',
   3,
   'IEEE quantum week with photonic quantum computing and QKD sessions',
   'cfp_closed',
   'technical paper submission window (Apr 13-27 2026) confirmed passed; registration opened Apr 14 2026',
   'https://qce.quantum.ieee.org/2026/'),
ev('photonics-switching-2026',
   'PSC 2026 — Photonics in Switching and Computing',
   'PSC 2026',
   'Conference',
   'photonic integrated circuits;silicon photonics',
   '2026-09-15',
   '2026-09-18',
   'Valencia, Spain',
   'TBA',
   'TBA',
   'TBA',
   'TBA',
   'https://psc2026.org/',
   3,
   'Photonic switching and routing conference',
   'upcoming',
   'confirmed real event is PSC (Photonics in Switching and Computing) 2026; dates/location/website found',
   'https://psc2026.org/; https://ieeephotonics.org/event/2026-international-conference-on-photonics-in-switching-and-computing-psc/'),
ev('dpg-bad-honnef-applied-photonics-2026',
   'Bad Honnef Physics School: Applied Photonics',
   'DPG Bad Honnef AP',
   'Summer School',
   'nanophotonics;integrated quantum photonics',
   '2026-09-20',
   '2026-09-25',
   'Bad Honnef, Germany',
   'TBA',
   'n/a',
   'TBA',
   'TBA',
   'https://www.dpg-physik.de/veranstaltungen/2026/applied_photonics',
   4,
   'DPG physics school on photonics fundamentals incl. nanooptics/quantum photonic systems, open to PhD students',
   'upcoming',
   'new entry',
   'https://www.dpg-physik.de/veranstaltungen/2026/applied_photonics'),
ev('ecoc-2026',
   'European Conference on Optical Communication 2026',
   'ECOC 2026',
   'Conference',
   'photonic integrated circuits;silicon photonics;quantum communication;integrated quantum photonics',
   '2026-09-20',
   '2026-09-24',
   'Málaga, Spain',
   '2026-04-22',
   '2026-04-22',
   'TBA',
   'TBA',
   'https://ecoc2026.org/',
   4,
   "Europe's flagship optical comms conference with quantum technologies track",
   'cfp_closed',
   'paper submission deadline was 2026-04-22 (now closed); confirmed Sep 20-24 Málaga',
   'https://ecoc2026.org/; https://ecoc2026.org/ECOC2026/paper-submission'),
ev('mne-2026',
   'International Conference on Micro and Nano Engineering 2026',
   'MNE 2026',
   'Conference',
   'photonic integrated circuits;nanophotonics;2D-material photonics',
   '2026-09-21',
   '2026-09-24',
   'Interlaken, Switzerland',
   'TBA',
   'TBA',
   'TBA',
   'TBA',
   'https://mne2026.imnes.org/',
   3,
   'Nanofabrication conference relevant to photonic device processing',
   'cfp_closed',
   'main CFP confirmed closed (author notifications already sent); late-breaking poster track open through end-Aug-2026',
   'https://mne2026.imnes.org/'),
ev('fio-2026',
   'Frontiers in Optics + Laser Science 2026',
   'FiO+LS 2026',
   'Conference',
   'quantum optics;nonlinear optics;nanophotonics',
   '2026-09-27',
   '2026-10-01',
   'Rochester, NY, USA',
   '2026-07-07',
   '2026-07-07',
   'TBA',
   '2026-08-14',
   'https://frontiersinoptics.com/',
   3,
   'Broad US photonics conference with quantum optics tracks',
   'cfp_open',
   'CORRECTED end date to 2026-10-01 (was 2026-09-30); abstract deadline confirmed 2026-07-07 (imminent); advance registration deadline 2026-08-14',
   'https://frontiersinoptics.com/'),
ev('les-houches-focm-2026',
   'Les Houches Doctoral Training: Frontiers of Condensed Matter',
   'LH FOCM 2026',
   'Summer School',
   'optomechanics;nanophotonics',
   '2026-09-28',
   '2026-10-09',
   'Les Houches, France',
   'TBA',
   'n/a',
   'TBA',
   'n/a',
   'https://frontiers-les-houches.org/',
   3,
   'Session on strong coupling of photons with magnons/phonons/spins — adjacent to optomechanics and hybrid quantum systems',
   'upcoming',
   'new entry',
   'https://frontiers-les-houches.org/'),
ev('qps-paderborn-2026',
   'Quantum Photonics Spotlight 2026',
   'QPS2026',
   'Conference',
   'integrated quantum photonics;quantum communication;quantum computing hardware',
   '2026-09-28',
   '2026-10-02',
   'Paderborn, Germany',
   'TBA',
   'n/a',
   'TBA',
   'TBA',
   'https://phoqs.uni-paderborn.de/en/veranstaltungen/quantum-photonics-spotlight-2026',
   5,
   "Dedicated German quantum-photonics conference hosted by Paderborn's PhoQS institute — direct core-topic overlap, low travel cost",
   'upcoming',
   'new entry',
   'https://phoqs.uni-paderborn.de/en/veranstaltungen/quantum-photonics-spotlight-2026'),
ev('hdqs-2026',
   'High-Dimensional Quantum Systems Workshop 2026',
   'HDQS 2026',
   'Workshop',
   'quantum optics;quantum communication;integrated quantum photonics',
   '2026-10-04',
   '2026-10-09',
   'Benasque, Spain',
   'TBA',
   'n/a',
   'TBA',
   'n/a',
   'https://benasque.org/2026hdqs/',
   4,
   'Benasque workshop on high-dimensional quantum photonics and quantum information',
   'upcoming',
   'web search returned contradictory/unsourced date claims for this run; kept prior dates pending manual re-check of benasque.org/2026hdqs/',
   'https://benasque.org/2026hdqs/'),
ev('nanop-2026',
   'NANOP 2026 — 8th Nanophotonics and Micro/Nano Optics International Conference',
   'NANOP 2026',
   'Conference',
   'nanophotonics;optomechanics',
   '2026-10-05',
   '2026-10-07',
   'Rome, Italy',
   'TBA',
   'n/a',
   '2026-07-24',
   'TBA',
   'https://premc.org/conferences/nanop-nanophotonics-micro-nano-optics/',
   3,
   'Established nanophotonics conference series covering nano-optomechanics and functional nanophotonics',
   'cfp_open',
   'new entry',
   'https://premc.org/conferences/nanop-nanophotonics-micro-nano-optics/'),
ev('photonics-days-2026',
   'Photonics Days Berlin 2026',
   'PDB 2026',
   'Conference',
   'integrated quantum photonics;photonic integrated circuits;nanophotonics',
   '2026-10-07',
   '2026-10-08',
   'Berlin, Germany',
   'TBA',
   'TBA',
   'TBA',
   'TBA',
   'https://photonic-days-berlin.com/',
   3,
   'German photonics industry and research meeting',
   'upcoming',
   'dates/venue corroborated by 3 independent sources (WISTA Event Center, Adlershof); appears to be invited-speaker/exhibition event with no open CFP',
   'https://photonic-days-berlin.com/'),
ev('quest-cryo-2026',
   'QUEST 2026 — 2nd International Workshop on Quantum, Cryogenic and Superconductive Computing',
   'QUEST 2026',
   'Workshop',
   'cryogenic electronics;quantum computing hardware;SNSPDs',
   '2026-10-19',
   '2026-10-21',
   'Niigata, Japan',
   'TBA',
   'TBA',
   'TBA',
   'TBA',
   'https://ieeecsc.org/event/workshop/quantum-cryogenic-superconductive-computing-2026',
   3,
   'Co-organized by German Leibniz Institutes IPHT Jena and IHP; covers cryogenic electronics relevant to SNSPD/quantum-hardware readout',
   'cfp_open',
   'new entry',
   'https://ieeecsc.org/event/workshop/quantum-cryogenic-superconductive-computing-2026'),
ev('it-fab-school-2026',
   'It-fab Italian Network for Micro and Nano Fabrication School 2026',
   'It-fab School 2026',
   'Summer School',
   'photonic integrated circuits;nanophotonics',
   '2026-10-27',
   '2026-10-30',
   'Turin (INRiM), Italy',
   'TBA',
   'n/a',
   'TBA',
   'n/a',
   'https://itfab.bo.imm.cnr.it/',
   3,
   'Italian nanofabrication school relevant to photonic device processing',
   'upcoming',
   "confirmed real dates/location: Oct 27-30 2026, Turin (INRiM/STMicroelectronics), first 'traveling' edition",
   'https://itfab.bo.imm.cnr.it/; https://www.inrim.it/it/eventi/it-fab-hands-school-micro-and-nano-fabrication'),
ev('ipc-2026',
   'IEEE Photonics Conference 2026',
   'IPC 2026',
   'Conference',
   'integrated quantum photonics;photonic integrated circuits;silicon photonics',
   '2026-11-08',
   '2026-11-12',
   'Denver, CO, USA',
   'TBA',
   'TBA',
   'TBA',
   'TBA',
   'https://ieee-ipc.org/',
   4,
   'IEEE flagship photonics devices and integrated systems conference',
   'cfp_closed',
   'two-stage submission (abstract ~Jan/paper ~Mar-Apr 2026) confirmed already passed',
   'https://ieee-ipc.org/'),
ev('sensing-quantum-light-2026',
   'Sensing with Quantum Light 2026',
   'SQL26',
   'Conference',
   'quantum optics;squeezed light;nonlinear optics',
   '2026-11-09',
   '2026-11-13',
   'Cologne, Germany',
   'TBA',
   'n/a',
   'TBA',
   'TBA',
   'https://www.sqlkonferenz.com/',
   5,
   'Dedicated conference on quantum-light sensing incl. squeezed light and nonlinear interferometry — bullseye for quantum optics interests',
   'upcoming',
   'new entry',
   'https://www.sqlkonferenz.com/'),
ev('eqtc-2026',
   'European Quantum Technologies Conference 2026',
   'EQTC 2026',
   'Conference',
   'integrated quantum photonics;quantum communication;quantum computing hardware;quantum networking',
   '2026-11-29',
   '2026-12-03',
   'Dublin, Ireland',
   '2026-07-20',
   'TBA',
   'TBA',
   'TBA',
   'https://www.eqtc2026.eu/',
   5,
   'EU Quantum Flagship conference — all aspects of quantum technology, high visibility',
   'cfp_open',
   'Science & Technology track abstract deadline confirmed 2026-07-20 (notification ~Aug 14); updated to dedicated conference site eqtc2026.eu',
   'https://www.eqtc2026.eu/; https://qt.eu/events/eqtc-2026-european-quantum-technologies-conference'),
ev('photonics-west-2027',
   'SPIE Photonics West 2027',
   'PW 2027',
   'Conference',
   'integrated quantum photonics;silicon photonics;nonlinear optics;single-photon sources',
   '2027-01-30',
   '2027-02-04',
   'San Francisco, CA, USA',
   '2026-07-22',
   'TBA',
   'TBA',
   'TBA',
   'https://spie.org/conferences-and-exhibitions/photonics-west',
   5,
   'SPIE flagship with Quantum West and Si-photonics tracks — abstract deadline Jul 22 2026',
   'cfp_open',
   'abstract deadline 2026-07-22 reconfirmed unchanged and still open',
   'https://spie.org/conferences-and-exhibitions/photonics-west; https://spie.org/conferences-and-exhibitions/photonics-west/program/browse-program'),
ev('we-heraeus-quantum-entanglement-2027',
   '879th WE-Heraeus-Seminar: Quantum Entanglement — New Concepts and Opportunities',
   'WEH-879',
   'Seminar',
   'quantum optics;quantum communication',
   '2027-02-14',
   '2027-02-17',
   'Bad Honnef, Germany',
   'TBA',
   'n/a',
   'TBA',
   'TBA',
   'https://www.we-heraeus-stiftung.de/veranstaltungen/quantum-entanglement-new-concepts-and-opportunities',
   3,
   'Small WE-Heraeus seminar covering entanglement implementations incl. photonic-platform experiments',
   'upcoming',
   'new entry',
   'https://www.we-heraeus-stiftung.de/veranstaltungen/quantum-entanglement-new-concepts-and-opportunities'),
ev('qip-2027',
   '30th Quantum Information Processing Conference',
   'QIP 2027',
   'Conference',
   'quantum communication;quantum computing hardware;quantum networking',
   '2027-02-20',
   '2027-02-26',
   'Singapore',
   'TBA',
   'TBA',
   'TBA',
   'TBA',
   'https://qipconference.org/2027/',
   4,
   'Premier annual quantum information conference; quantum networking and hardware sessions',
   'upcoming',
   'dates/venue reconfirmed unchanged; CFP/deadlines not yet announced, expected ~Sep-Oct 2026',
   'https://qipconference.org/2027/; https://qip.iaqi.org/nextqip'),
ev('photoptics-nanoplasmeta-2027',
   'PHOTOPTICS 2027 Workshop on Nanophotonics, Plasmonics and Metamaterials',
   'NanoPlasMeta 2027',
   'Workshop',
   'nanophotonics;plasmonics',
   '2027-02-25',
   '2027-02-27',
   'Valletta, Malta',
   'n/a',
   '2026-12-03',
   'TBA',
   'TBA',
   'https://photoptics.scitevents.org/',
   3,
   'Workshop co-located with PHOTOPTICS specifically on nanophotonics/plasmonics/metamaterials',
   'cfp_open',
   'new entry',
   'https://photoptics.scitevents.org/NanoPlasMeta.aspx'),
ev('dpg-samop-2027',
   'DPG Frühjahrstagung SAMOP 2027',
   'DPG SAMOP 2027',
   'Conference',
   'quantum optics;nanophotonics;integrated quantum photonics',
   '2027-02-28',
   '2027-03-05',
   'Hannover, Germany',
   'TBA',
   'TBA',
   'TBA',
   'TBA',
   'https://www.dpg-physik.de/veranstaltungen/2027/dpg-fruehjahrstagung-hannover',
   4,
   'DPG spring meeting for quantum optics and photonics — easily accessible from Münster',
   'upcoming',
   'dates reconfirmed unchanged; updated to specific DPG event page (dedicated hannover-conference microsite not yet live, expected ~Sep 2026); an ambiguous/unverified cancellation signal was found in secondary search snippets — flagged for manual re-check, not acted on',
   'https://dpg-physik.de/'),
ev('ofc-2027',
   'Optical Fiber Communication Conference 2027',
   'OFC 2027',
   'Conference',
   'photonic integrated circuits;silicon photonics;quantum communication',
   '2027-03-07',
   '2027-03-11',
   'Los Angeles, CA, USA',
   'TBA',
   'TBA',
   'TBA',
   'TBA',
   'https://ofcconference.org/',
   4,
   "World's largest optical comms conference with PIC and quantum networking sessions",
   'upcoming',
   'dates/venue reconfirmed unchanged; deadlines not yet published',
   'https://ofcconference.org/'),
ev('les-houches-photonics-ai-2027',
   'Les Houches School: Photonics and Artificial Intelligence',
   'LH Photonics-AI 2027',
   'Summer School',
   'photonic integrated circuits;nanophotonics',
   '2027-04-04',
   '2027-04-09',
   'Les Houches, France',
   'TBA',
   'n/a',
   'TBA',
   'n/a',
   'https://www.houches-school-physics.com/program/program-2027/',
   5,
   'New 2027 Les Houches thematic school on integrated photonics and AI-assisted photonic design (organizers incl. C2N, FEMTO-ST)',
   'upcoming',
   'new entry',
   'https://www.sfoptique.org/pages/sfo/ecoles-thematiques/2027-artificial-intelligence-photonics/2027-photonics-artificial-intelligence.html'),
ev('spie-oo-2027',
   'SPIE Optics + Optoelectronics 2027',
   'SPIE O+O 2027',
   'Conference',
   'integrated quantum photonics;quantum optics;nanophotonics',
   '2027-04-05',
   '2027-04-08',
   'Prague, Czech Republic',
   'TBA',
   'TBA',
   'TBA',
   'TBA',
   'https://spie.org/conferences-and-exhibitions/optics-and-optoelectronics',
   4,
   'SPIE European conference with quantum photonics and nanophotonics tracks',
   'upcoming',
   'official website confirmed: spie.org/conferences-and-exhibitions/optics-and-optoelectronics (was unknown/TBA on file)',
   'original list'),
ev('quantum-networks-summit-2027',
   'Quantum Networks Summit 2027',
   'QNS 2027',
   'Conference',
   'quantum communication;quantum networking;QKD',
   '2027-04-07',
   '2027-04-08',
   'Paris, France',
   'n/a',
   'n/a',
   'TBA',
   'TBA',
   'https://www.uppersideconferences.com/quantum-networks/2027/index.html',
   4,
   'Industry/research summit on quantum communications and photonic secure networking',
   'upcoming',
   'new entry',
   'https://www.uppersideconferences.com/quantum-networks/2027/index.html'),
ev('qpain-2027',
   '3rd IEEE International Conference on Quantum Photonics, AI, and Networking',
   'IEEE QPAIN 2027',
   'Conference',
   'integrated quantum photonics;quantum networking',
   '2027-04-08',
   '2027-04-10',
   'Chattogram, Bangladesh',
   'TBA',
   'TBA',
   'TBA',
   'TBA',
   'https://qpain.org/',
   3,
   'Successor of the already-archived IEEE QPAIN 2026; regional IEEE conference on quantum photonics/networking',
   'upcoming',
   'new entry',
   'https://qpain.org/'),
ev('aps-summit-2027',
   'APS Global Physics Summit 2027',
   'APS Summit 2027',
   'Conference',
   'quantum optics;quantum computing hardware;integrated quantum photonics',
   '2027-04-11',
   '2027-04-16',
   'Atlanta, GA, USA',
   'TBA',
   'TBA',
   'TBA',
   'TBA',
   'https://www.aps.org/events/2027/summit',
   4,
   'Joint APS March+April meeting; major quantum photonics and computing sessions',
   'upcoming',
   'dates/venue reconfirmed unchanged; deadlines not yet published',
   'https://www.aps.org/events/2027/summit'),
ev('pic-international-2027',
   'PIC International 2027',
   'PIC International',
   'Conference',
   'photonic integrated circuits;silicon photonics',
   '2027-04-12',
   '2027-04-14',
   'Brussels, Belgium',
   'n/a',
   'n/a',
   'TBA',
   'TBA',
   'https://picinternational.net/',
   4,
   '12th edition of the PIC industry conference; useful for PIC industry contacts',
   'upcoming',
   'new entry',
   'https://picinternational.net/; https://10times.com/pic-international-conference'),
ev('cleo-2027',
   'Conference on Lasers and Electro-Optics 2027',
   'CLEO 2027',
   'Conference',
   'integrated quantum photonics;quantum optics;nonlinear optics;silicon photonics;single-photon sources',
   '2027-05-02',
   '2027-05-06',
   'Long Beach, CA, USA',
   'TBA',
   'n/a',
   'TBA',
   'TBA',
   'https://cleoconference.org/',
   5,
   'Premier US laser/photonics conference; major IQP, Si-PIC and quantum optics sessions',
   'upcoming',
   'new entry; year roll-over from 2026 edition (Charlotte)',
   'https://cleoconference.org/; https://www.optica.org/events/global_calendar/events/2027/conference_on_lasers_and_electro-optics_(1)/'),
ev('ccw-amsterdam-2027',
   'Critical Communications World Amsterdam 2027',
   'CCW 2027',
   'Conference',
   'quantum communication;quantum networking',
   '2027-05-11',
   '2027-05-13',
   'Amsterdam, Netherlands',
   'TBA',
   'TBA',
   'TBA',
   'TBA',
   'https://www.critical-communications-world.com/',
   2,
   'Critical comms industry event; QKD sessions of marginal relevance',
   'upcoming',
   "new entry; year roll-over; confirmed via organizer's exhibitor page",
   'https://www.critical-communications-world.com/exhibit-at-ccw'),
ev('quantum-tech-world-2027',
   'Quantum.Tech World 2027',
   'Q.Tech World 2027',
   'Conference',
   'quantum computing hardware;quantum communication;integrated quantum photonics',
   '2027-05-25',
   '2027-05-26',
   'Boston, MA, USA',
   'TBA',
   'n/a',
   'TBA',
   'TBA',
   'https://www.alphaevents.com/events-quantumtechus',
   2,
   'Industry quantum technology event; limited deep-science content',
   'upcoming',
   'new entry; year roll-over; 8th edition, Encore Boston Harbor, first year co-located with Compute.Tech',
   'https://www.alphaevents.com/events-quantumtechus'),
ev('cleo-europe-2027',
   'CLEO/Europe-EQEC 2027',
   'CLEO/Europe 2027',
   'Conference',
   'integrated quantum photonics;quantum optics;nonlinear optics;nanophotonics',
   '2027-06-20',
   '2027-06-25',
   'Munich, Germany',
   'TBA',
   'TBA',
   'TBA',
   'TBA',
   'https://cleoeurope.org/',
   5,
   'Flagship European photonics and quantum optics biennial conference',
   'upcoming',
   "dates/venue reconfirmed unchanged via World of Photonics Congress page; abstract deadline not yet announced (2025 cycle's was late Jan)",
   'https://cleoeurope.org/; https://www.photonics-congress.com/en/about/conferences/cleo-eqec/'),
ev('grc-quantum-sensing-2027',
   'Gordon Research Conference — Quantum Sensing 2027',
   'GRC QSe 2027',
   'Conference',
   'quantum optics;single-photon sources;quantum computing hardware',
   '2027-07-11',
   '2027-07-16',
   'Les Diablerets, Switzerland',
   'n/a',
   'n/a',
   '2027-06-13',
   'n/a',
   'https://www.grc.org/quantum-sensing-conference/2027/',
   3,
   'Covers photonic-platform quantum sensing (NV/atomic/solid-state), adjacent to single-photon and quantum-optics interests',
   'upcoming',
   'new entry',
   'https://www.grc.org/quantum-sensing-conference/2027/'),
ev('grc-qclm-2027',
   'Gordon Research Conference — Quantum Control of Light and Matter 2027',
   'GRC QCLM 2027',
   'Conference',
   'quantum optics;nonlinear optics',
   '2027-08-01',
   '2027-08-06',
   'Newport, RI, USA',
   'n/a',
   'n/a',
   'TBA',
   'n/a',
   'https://www.grc.org/quantum-control-of-light-and-matter-conference/',
   4,
   'Directly on quantum control of light-matter interaction, nonlinear optics and ultrafast laser technology',
   'upcoming',
   'new entry',
   'https://www.grc.org/quantum-control-of-light-and-matter-conference/'),
ev('ieee-rapid-2027',
   'IEEE Research and Applications of Photonics in Defense 2027',
   'IEEE RAPID 2027',
   'Conference',
   'single-photon sources;quantum communication',
   '2027-08-11',
   '2027-08-13',
   'Miramar Beach, FL, USA',
   'TBA',
   'TBA',
   'TBA',
   'TBA',
   'https://ieee-rapid.org/',
   2,
   'Defense photonics conference',
   'upcoming',
   'could not independently reconfirm this run (search results inconclusive); kept prior data',
   'https://ieee-rapid.org/'),
ev('ecoc-2027',
   'European Conference on Optical Communication 2027',
   'ECOC 2027',
   'Conference',
   'photonic integrated circuits;silicon photonics;quantum communication;integrated quantum photonics',
   '2027-10-10',
   '2027-10-14',
   'Milano, Italy',
   'TBA',
   'TBA',
   'TBA',
   'TBA',
   'https://ecoc2027.org/',
   4,
   "Europe's flagship optical comms conference with quantum technologies track",
   'upcoming',
   'new entry',
   'https://ecoc2027.org/; https://10times.com/e1hz-x284-kp7s-x-european-conference-optical-communication'),
ev('ipc-2027',
   'IEEE Photonics Conference 2027',
   'IPC 2027',
   'Conference',
   'integrated quantum photonics;photonic integrated circuits;silicon photonics',
   '2027-11-10',
   '2027-11-14',
   'Eindhoven, Netherlands',
   'TBA',
   'TBA',
   'TBA',
   'TBA',
   'https://ieee-ipc.org/',
   4,
   'IEEE photonics flagship; European edition in Eindhoven — low travel cost',
   'upcoming',
   'could not independently reconfirm Eindhoven location this run (no corroborating source found); kept prior data',
   'https://ieee-ipc.org/'),
ev('benasque-qsi-2028',
   'Quantum Science: Implementations 2028',
   'Benasque QSI 2028',
   'Workshop',
   'integrated quantum photonics;quantum computing hardware;quantum communication',
   'TBA',
   'TBA',
   'Benasque, Spain',
   'TBA',
   'n/a',
   'TBA',
   'n/a',
   'https://benasque.org/',
   4,
   'Benasque workshop on quantum implementations including photonic platforms',
   'upcoming',
   'new entry; year roll-over; biennial series, 2028 not yet announced',
   'https://benasque.org/'),
ev('damop-2027',
   '58th APS Division of Atomic, Molecular and Optical Physics Meeting',
   'DAMOP 2027',
   'Conference',
   'quantum optics;nonlinear optics;single-photon sources',
   'TBA',
   'TBA',
   'Chicago, IL, USA',
   'TBA',
   'TBA',
   'TBA',
   'TBA',
   'https://www.aps.org/events/2027/damop-2027',
   3,
   'AMO physics flagship with quantum optics and single-photon sessions',
   'upcoming',
   'new entry; year roll-over; Chicago confirmed, exact June dates not yet published',
   'https://www.aps.org/events/2027/damop-2027'),
ev('ecio-2027',
   'European Conference on Integrated Optics 2027',
   'ECIO 2027',
   'Conference',
   'integrated quantum photonics;photonic integrated circuits;silicon photonics;nanophotonics',
   'TBA',
   'TBA',
   'TBA',
   'TBA',
   'TBA',
   'TBA',
   'TBA',
   'https://ecio-conference.org/',
   5,
   'Largest European integrated optics conference — core relevance for AG Schuck',
   'upcoming',
   'new entry; year roll-over; annual series, 2027 host not yet announced',
   'https://ecio-conference.org/'),
ev('egas-2027',
   '58th Conference of the European Group on Atomic Systems',
   'EGAS 2027',
   'Conference',
   'quantum optics;nonlinear optics',
   'TBA',
   'TBA',
   'TBA',
   'TBA',
   'TBA',
   'TBA',
   'TBA',
   'https://www.eps-egas.org/',
   3,
   'European atomic systems conference with quantum optics and light-matter sessions',
   'upcoming',
   'new entry; year roll-over; annual series, host not yet announced (unverified rumor of Sweden discarded)',
   'https://www.eps-egas.org/'),
ev('erice-matter-photonics-2026',
   '40th Erice Workshop: Matter Physics and Photonics',
   'Erice MPP 2026',
   'Workshop',
   'nanophotonics;quantum optics',
   'TBA',
   'TBA',
   'Erice, Italy',
   'TBA',
   'n/a',
   'TBA',
   'n/a',
   'https://ettoremajoranafoundation.com/',
   4,
   'Erice workshop (director M. Cesaria) centered on photonics and its interplay with matter physics',
   'upcoming',
   'new entry; exact 2026 dates not yet published',
   'https://ettoremajoranafoundation.com/wp-content/uploads/2026/03/Summary-2026-1-1.pdf'),
ev('grc-comp-optics-photonics-2027',
   'Gordon Research Conference — Computational Optics and Intelligent Photonic Devices 2027',
   'GRC COIPD 2027',
   'Conference',
   'integrated quantum photonics;photonic integrated circuits;nanophotonics',
   'TBA',
   'TBA',
   'Manchester, NH, USA',
   'n/a',
   'n/a',
   '2027-06-27',
   'n/a',
   'https://www.grc.org/computational-optics-and-intelligent-photonic-devices-conference/2027/',
   3,
   'New GRC series on integrated photonic platforms, metasurfaces and photonic inverse design',
   'upcoming',
   'new entry; inaugural/new series, exact dates not yet posted',
   'https://www.grc.org/computational-optics-and-intelligent-photonic-devices-conference/2027/'),
ev('grc-quantum-science-2028',
   'Gordon Research Conference — Quantum Science 2028',
   'GRC QS 2028',
   'Conference',
   'quantum optics;quantum computing hardware;quantum communication;integrated quantum photonics',
   'TBA',
   'TBA',
   'TBA',
   'TBA',
   'n/a',
   'TBA',
   'n/a',
   'https://www.grc.org/quantum-science-conference/',
   4,
   'GRC on quantum science covering photonic quantum systems and quantum information',
   'upcoming',
   'new entry; year roll-over; biennial series, 2028 dates not yet published',
   'https://www.grc.org/quantum-science-conference/'),
ev('icap-2029',
   '30th International Conference on Atomic Physics',
   'ICAP 2029',
   'Conference',
   'quantum optics;nonlinear optics',
   'TBA',
   'TBA',
   'TBA',
   'TBA',
   'TBA',
   'TBA',
   'TBA',
   'https://www.icap29.com/',
   3,
   'Atomic physics conference with quantum optics and light-matter interaction sessions',
   'upcoming',
   'new entry; year roll-over; triennial series, host not yet announced',
   'https://www.icap29.com/'),
ev('iqt-nordics-2027',
   'IQT Nordics 2027',
   'IQT Nordics 2027',
   'Conference',
   'quantum communication;quantum computing hardware;integrated quantum photonics',
   'TBA',
   'TBA',
   'Copenhagen, Denmark',
   'TBA',
   'n/a',
   'TBA',
   'TBA',
   'https://iqtevent.com/nordics/',
   3,
   'Nordic quantum industry conference with hardware and QKD sessions',
   'upcoming',
   'new entry; year roll-over; organizer confirmed Copenhagen return (rotation Copenhagen/Helsinki/Gothenburg/Oslo), exact dates TBA',
   'https://iqtevent.com/nordics/; https://www.insidequantumtechnology.com/news-archive/announcing-the-return-of-iqt-nordics-in-copenhagen-2027/'),
ev('islc-2028',
   '31st International Semiconductor Laser Conference',
   'ISLC 2028',
   'Conference',
   'single-photon sources;III-V on Si;photonic integrated circuits',
   'TBA',
   'TBA',
   'TBA',
   'TBA',
   'TBA',
   'TBA',
   'TBA',
   'https://ieeephotonics.org/conferences/',
   4,
   'III-V semiconductor laser conference — key for quantum light source development',
   'upcoming',
   'new entry; year roll-over; biennial series, host not yet announced',
   'https://ieeephotonics.org/conferences/'),
ev('nrw-nano-2027',
   '12th NRW Nano Conference',
   'NRW Nano 2027',
   'Conference',
   'nanophotonics;photonic integrated circuits',
   'TBA',
   'TBA',
   'North Rhine-Westphalia, Germany',
   'TBA',
   'TBA',
   'TBA',
   'TBA',
   'https://www.nanoconference.de/',
   3,
   'Regional NRW nanotechnology conference; local access',
   'upcoming',
   "renamed from 'nrw-nano-2026' placeholder; confirmed biennial series (11th ed. was Sep 30-Oct 1 2025, Dortmund), 2026 edition does not exist, next expected 2027 dates TBA",
   'original list'),
ev('oecc-2027',
   '32nd OptoElectronics and Communications Conference',
   'OECC 2027',
   'Conference',
   'photonic integrated circuits;silicon photonics;quantum communication',
   'TBA',
   'TBA',
   'TBA',
   'TBA',
   'TBA',
   'TBA',
   'TBA',
   'TBA',
   3,
   'Asia-Pacific optoelectronics and comms conference with PIC sessions',
   'upcoming',
   'new entry; year roll-over; annual, rotating Asia-Pacific host, 2027 not yet announced',
   'original list'),
ev('opic-2027',
   'OPIC 2027 — Optics & Photonics International Congress',
   'OPIC 2027',
   'Conference',
   'integrated quantum photonics;quantum optics;nanophotonics',
   'TBA',
   'TBA',
   'Yokohama, Japan (expected)',
   'TBA',
   'TBA',
   'TBA',
   'TBA',
   'https://opicon.jp/',
   3,
   'Japanese international photonics congress with quantum tracks',
   'upcoming',
   'new entry; annual series (every April, Pacifico Yokohama), 2027 dates not yet announced',
   'https://opicon.jp/'),
ev('optica-quantum-2028',
   'Optica Quantum 2.0 Conference and Exhibition 2028',
   'Optica Quantum 2028',
   'Conference',
   'integrated quantum photonics;quantum optics;single-photon sources;quantum communication;quantum computing hardware',
   'TBA',
   'TBA',
   'TBA',
   'TBA',
   'n/a',
   'TBA',
   'n/a',
   'https://www.optica.org/events/topical_meetings/quantum/',
   5,
   'Premier quantum photonics conference spanning PICs, detectors, QKD, and hardware',
   'upcoming',
   'new entry; year roll-over; biennial series, 2028 not yet announced',
   'https://www.optica.org/events/topical_meetings/quantum/'),
ev('owtnm-2027',
   'OWTNM 2027 — Optical Wave & Waveguide Theory and Modelling Workshop',
   'OWTNM 2027',
   'Workshop',
   'photonic integrated circuits;nanophotonics',
   'TBA',
   'TBA',
   'TBA',
   'TBA',
   'n/a',
   'TBA',
   'n/a',
   'https://www.owtnm.eu/',
   3,
   'Waveguide modelling workshop relevant to PIC simulation',
   'upcoming',
   'new entry; annual series since 1992, 2027 host not yet announced',
   'https://www.owtnm.eu/'),
ev('photonics-north-2027',
   'Photonics North 2027',
   'PN 2027',
   'Conference',
   'silicon photonics;integrated quantum photonics;quantum communication',
   'TBA',
   'TBA',
   'TBA',
   'TBA',
   'TBA',
   'TBA',
   'TBA',
   'https://photonicsnorth.com/en',
   3,
   'Canadian national photonics conference with PIC and quantum sessions',
   'upcoming',
   'new entry; year roll-over; cadence confirmed annual (2024 Vancouver, 2025 Ottawa, 2026 Québec City); 2027 not yet announced',
   'https://photonicsnorth.com/en'),
ev('quantum-korea-2027',
   'Quantum Korea 2027',
   'Quantum Korea 2027',
   'Conference',
   'quantum computing hardware;quantum communication;integrated quantum photonics',
   'TBA',
   'TBA',
   'Seoul, South Korea (expected)',
   'TBA',
   'n/a',
   'TBA',
   'TBA',
   'https://quantum-korea.kr/en/main',
   2,
   'Government-organised Korean quantum technology showcase',
   'upcoming',
   'new entry; year roll-over; annual series since 2023, 2027 not yet announced',
   'https://quantum-korea.kr/en/main'),
ev('spie-pfq-2027',
   'SPIE Photonics for Quantum 2027',
   'PfQ 2027',
   'Conference',
   'integrated quantum photonics;single-photon sources;quantum communication;quantum computing hardware',
   'TBA',
   'TBA',
   'Waterloo, ON, Canada (expected)',
   'TBA',
   'n/a',
   'TBA',
   'TBA',
   'https://spie.org/conferences-and-exhibitions/photonics-for-quantum',
   5,
   'Dedicated quantum photonics conference — bullseye for AG Schuck',
   'upcoming',
   'new entry; year roll-over; annual series at Waterloo, 2027 dates not yet announced',
   'https://spie.org/conferences-and-exhibitions/photonics-for-quantum'),
]  # end EVENTS


# ── helpers ───────────────────────────────────────────────────────────────────
def parse_date(s):
    """Return date object or None for TBA/n/a."""
    if not s or s in ("TBA", "n/a"):
        return None
    try:
        return date.fromisoformat(s)
    except ValueError:
        return None


def days_from_today(s):
    d = parse_date(s)
    if d is None:
        return None
    return (d - TODAY).days


RED   = PatternFill(fill_type="solid", fgColor="FF4444")
AMBER = PatternFill(fill_type="solid", fgColor="FFAA00")

def deadline_fill(s):
    """Return RED/AMBER fill or None based on days until deadline."""
    n = days_from_today(s)
    if n is None:
        return None
    if 0 <= n <= 14:
        return RED
    if 15 <= n <= 60:
        return AMBER
    return None


# ── write TSV ─────────────────────────────────────────────────────────────────
def write_tsv(events, path):
    with open(path, "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=COLS, delimiter="\t",
                           extrasaction="ignore")
        w.writeheader()
        for e in events:
            w.writerow(e)
    print(f"  TSV  -> {path}  ({len(events)} rows)")


# ── write XLSX ────────────────────────────────────────────────────────────────
HEADER_FILL  = PatternFill(fill_type="solid", fgColor="1F4E79")
HEADER_FONT  = Font(bold=True, color="FFFFFF", size=10)
ARCHIVED_FILL = PatternFill(fill_type="solid", fgColor="E8E8E8")
SCORE_COLORS = {5:"D4EDDA", 4:"D1ECF1", 3:"FFF3CD", 2:"F8D7DA", 1:"F5C6CB"}

def write_xlsx(events, path):
    wb = Workbook()
    ws = wb.active
    ws.title = "Conferences"

    # header
    ws.append(COLS)
    for cell in ws[1]:
        cell.fill   = HEADER_FILL
        cell.font   = HEADER_FONT
        cell.alignment = Alignment(horizontal="center", vertical="center",
                                   wrap_text=True)

    ws.row_dimensions[1].height = 28
    ws.freeze_panes = "A2"
    ws.auto_filter.ref = f"A1:{get_column_letter(len(COLS))}1"

    col_idx = {c: i+1 for i, c in enumerate(COLS)}

    for ev in events:
        row_vals = [ev[c] for c in COLS]
        ws.append(row_vals)
        row_num = ws.max_row

        # light-grey background for archived rows
        is_archived = ev["status"] == "archived"
        if is_archived:
            for cell in ws[row_num]:
                cell.fill = ARCHIVED_FILL

        # relevance score colour on that cell
        score_cell = ws.cell(row=row_num, column=col_idx["relevance_score"])
        sc = ev.get("relevance_score")
        if sc and str(sc).isdigit() and int(sc) in SCORE_COLORS:
            score_cell.fill = PatternFill(fill_type="solid",
                                          fgColor=SCORE_COLORS[int(sc)])

        # deadline columns -- conditional colour
        for dcol in DEADLINE_COLS:
            val = ev.get(dcol, "")
            fill = deadline_fill(str(val))
            if fill:
                ws.cell(row=row_num, column=col_idx[dcol]).fill = fill

    # auto-size columns (capped)
    CAP = {
        "id": 28, "name": 55, "acronym": 18, "type": 16, "topic_tags": 55,
        "start_date": 13, "end_date": 13, "location": 28,
        "abstract_deadline": 17, "paper_deadline": 14,
        "registration_deadline": 20, "early_bird_deadline": 18,
        "website": 48, "relevance_score": 9, "relevance_note": 52,
        "status": 14, "last_verified": 14, "last_change": 50, "source_urls": 60,
    }
    for col_name, cap_w in CAP.items():
        ci = col_idx[col_name]
        ws.column_dimensions[get_column_letter(ci)].width = cap_w

    # wrap text in long columns
    for row in ws.iter_rows(min_row=2):
        for cell in row:
            cell.alignment = Alignment(wrap_text=False, vertical="top")

    wb.save(path)
    print(f"  XLSX -> {path}")


# ── main ──────────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    tsv_path  = os.path.join(OUTDIR, f"conferences_{SNAPSHOT}.tsv")
    xlsx_path = os.path.join(OUTDIR, f"conferences_{SNAPSHOT}.xlsx")

    write_tsv(EVENTS, tsv_path)
    write_xlsx(EVENTS, xlsx_path)
    print(f"\nDone. {len(EVENTS)} events written.")

    # summary stats
    from collections import Counter
    stats = Counter(e["status"] for e in EVENTS)
    for s, n in sorted(stats.items()):
        print(f"  {s:15s}: {n}")
