#!/usr/bin/env python3
"""
Build conferences_2026-09-13.tsv  and  conferences_2026-09-13.xlsx
for AG Schuck quantum-photonics conference tracker.
"""

import csv, os
from datetime import date, timedelta
from openpyxl import Workbook
from openpyxl.styles import PatternFill, Font, Alignment, Border, Side, PatternFill
from openpyxl.utils import get_column_letter

TODAY     = date(2026, 9, 13)
SNAPSHOT  = "2026-09-13"
OUTDIR    = "/home/user/conferences"

COLS = [
    "id", "name", "acronym", "type", "topic_tags",
    "start_date", "end_date", "location",
    "abstract_deadline", "paper_deadline",
    "registration_deadline", "early_bird_deadline",
    "website", "relevance_score", "relevance_note",
    "status", "last_verified", "last_change", "source_urls",
]
DEADLINE_COLS = ["abstract_deadline", "paper_deadline",
                 "registration_deadline", "early_bird_deadline"]

# ── Event data ────────────────────────────────────────────────────────────────
# Each entry is a dict keyed by COLS.
# Topic tags drawn from scope vocabulary:
#   integrated quantum photonics | photonic integrated circuits
#   single-photon sources | SNSPDs | quantum optics | nonlinear optics
#   quantum communication | QKD | quantum networking
#   silicon photonics | TFLN | III-V on Si
#   nanophotonics | plasmonics | optomechanics | 2D-material photonics
#   quantum computing hardware | cryogenic electronics

def ev(id, name, acronym, typ, tags, sd, ed, loc,
       abs_dl, pap_dl, reg_dl, eb_dl,
       url, score, note, status, change, srcs):
    return {
        "id": id, "name": name, "acronym": acronym, "type": typ,
        "topic_tags": tags, "start_date": sd, "end_date": ed,
        "location": loc,
        "abstract_deadline": abs_dl, "paper_deadline": pap_dl,
        "registration_deadline": reg_dl, "early_bird_deadline": eb_dl,
        "website": url, "relevance_score": score,
        "relevance_note": note, "status": status,
        "last_verified": SNAPSHOT, "last_change": change,
        "source_urls": srcs,
    }

LV = SNAPSHOT  # last_verified = today for all rows

EVENTS = [

ev("benasque-qnp-2025",
   "Quantum Nanophotonics 2025","Benasque QNP","Workshop",
   "nanophotonics;quantum optics;single-photon sources",
   "2025-03-16","2025-03-22","Benasque, Spain",
   "2025-01-17","n/a","TBA","n/a",
   "https://benasque.org/2025quantumnanophotonics/",5,
   "Directly on nanophotonics and single-photon sources","archived",
   "year roll-over from 2025 edition",
   "https://benasque.org/2025quantumnanophotonics/"),
ev("photonics-north-2025",
   "Photonics North 2025","PN 2025","Conference",
   "silicon photonics;integrated quantum photonics;quantum communication",
   "2025-05-20","2025-05-23","Ottawa, Canada",
   "TBA","TBA","TBA","TBA",
   "TBA",3,
   "Canadian photonics flagship with PIC and quantum sessions","archived",
   "year roll-over from 2025 edition",
   "original list"),
ev("benasque-sqt-2025",
   "Spring School on Superconducting Qubit Technology 2025","Benasque SQT","Summer School",
   "quantum computing hardware;cryogenic electronics",
   "2025-05-21","2025-05-30","Benasque, Spain",
   "TBA","n/a","TBA","n/a",
   "https://benasque.org/2025sqt/",3,
   "Cryogenic electronics for qubit control, adjacent to photonic detector systems","archived",
   "year roll-over from 2025 edition",
   "https://benasque.org/2025sqt/"),
ev("optica-quantum-2025",
   "Optica Quantum 2.0 Conference and Exhibition 2025","Optica Quantum 2025","Conference",
   "integrated quantum photonics;quantum optics;single-photon sources;quantum communication",
   "2025-06-01","2025-06-05","San Francisco, CA, USA",
   "TBA","TBA","TBA","TBA",
   "https://optica.org/events/topical_meetings/quantum/",5,
   "Premier global quantum photonics conference covering PICs, single photons, QKD","archived",
   "year roll-over from 2025 edition",
   "https://optica.org/events/topical_meetings/quantum/"),
ev("icols-2025",
   "26th International Conference on Laser Spectroscopy","ICOLS 2025","Conference",
   "quantum optics;nonlinear optics",
   "2025-06-02","2025-06-07","Elba Island, Italy",
   "2025-01-17","TBA","TBA","TBA",
   "https://icols2025.it/",3,
   "Laser spectroscopy with quantum optics relevance","archived",
   "year roll-over from 2025 edition",
   "https://icols2025.it/"),
ev("ecio-2025",
   "European Conference on Integrated Optics 2025","ECIO 2025","Conference",
   "integrated quantum photonics;photonic integrated circuits;silicon photonics",
   "2025-06-10","2025-06-12","Cardiff, Wales, UK",
   "TBA","TBA","TBA","TBA",
   "https://ecio-conference.org/",5,
   "Largest European dedicated integrated optics conference","archived",
   "year roll-over from 2025 edition",
   "https://ecio-conference.org/"),
ev("benasque-qi-2025",
   "Quantum Information 2025","Benasque QI","Workshop",
   "quantum communication;quantum optics",
   "2025-06-15","2025-07-04","Benasque, Spain",
   "TBA","n/a","TBA","n/a",
   "https://benasque.org/",3,
   "Quantum information including QKD and networking","archived",
   "year roll-over from 2025 edition",
   "https://benasque.org/"),
ev("damop-2025",
   "56th APS Division of Atomic, Molecular and Optical Physics Meeting","DAMOP 2025","Conference",
   "quantum optics;nonlinear optics",
   "2025-06-16","2025-06-20","Portland, OR, USA",
   "2025-01-31","2025-01-31","TBA","TBA",
   "https://aps.org/events/2025/atomic-molecular-optical-physics",3,
   "AMO physics flagship with quantum optics sessions","archived",
   "year roll-over from 2025 edition",
   "https://aps.org/events/2025/atomic-molecular-optical-physics"),
ev("cewqo-2025",
   "29th Central European Workshop on Quantum Optics","CEWQO 2025","Workshop",
   "quantum optics;single-photon sources;quantum communication",
   "2025-06-23","2025-06-27","Vilnius, Lithuania",
   "TBA","n/a","TBA","n/a",
   "https://ucan.physics.utoronto.ca/conferences/cewqo29/",4,
   "Dedicated European workshop on quantum optics and single-photon physics","archived",
   "year roll-over from 2025 edition",
   "https://ucan.physics.utoronto.ca/conferences/cewqo29/"),
ev("cleo-europe-2025",
   "CLEO/Europe-EQEC 2025","CLEO/Europe 2025","Conference",
   "integrated quantum photonics;quantum optics;nonlinear optics;nanophotonics",
   "2025-06-23","2025-06-27","Munich, Germany",
   "2025-01-27","2025-01-27","TBA","TBA",
   "https://cleoeurope.org/",5,
   "Flagship European photonics and quantum optics conference (biennial)","archived",
   "year roll-over from 2025 edition",
   "https://cleoeurope.org/"),
ev("icton-2025",
   "25th International Conference on Transparent Optical Networks","ICTON 2025","Conference",
   "photonic integrated circuits;silicon photonics;quantum communication",
   "2025-07-06","2025-07-10","Barcelona, Spain",
   "TBA","TBA","TBA","TBA",
   "https://icton2025.upc.edu/",3,
   "Transparent optical networks with PIC and quantum photonics tracks","archived",
   "year roll-over from 2025 edition",
   "https://icton2025.upc.edu/"),
ev("ieee-sum-2025",
   "IEEE Summer Topicals Meeting Series 2025","IEEE SUM 2025","Conference",
   "integrated quantum photonics;silicon photonics",
   "2025-07-21","2025-07-23","Berlin, Germany",
   "TBA","TBA","TBA","TBA",
   "https://ieee-sum.org/",3,
   "IEEE topical photonics sessions including PICs","archived",
   "year roll-over from 2025 edition",
   "https://ieee-sum.org/"),
ev("qcrypt-2025",
   "QCrypt 2025","QCrypt 2025","Conference",
   "quantum communication;QKD;quantum networking",
   "2025-08-25","2025-08-29","Sanya, China",
   "TBA","TBA","TBA","TBA",
   "https://qcrypt.net/",4,
   "Premier annual quantum cryptography and QKD conference","archived",
   "year roll-over from 2025 edition",
   "https://qcrypt.net/"),
ev("ecoc-2025",
   "51st European Conference on Optical Communication","ECOC 2025","Conference",
   "photonic integrated circuits;silicon photonics;quantum communication",
   "2025-09-28","2025-10-02","Copenhagen, Denmark",
   "TBA","TBA","TBA","TBA",
   "https://ecoc2025.org/",4,
   "Europe's biggest optical comms conference with PIC and quantum tracks","archived",
   "year roll-over from 2025 edition",
   "https://ecoc2025.org/"),
ev("nrw-nano-2025",
   "NRW NanoConference 2026","NRW Nano 2026","Conference",
   "nanophotonics;photonic integrated circuits",
   "2025-09-30","2025-10-01","Dortmund, Germany",
   "TBA","TBA","TBA","TBA",
   "https://www.nanoconference.de/",3,
   "Regional NRW nanotechnology conference; local access","archived",
   "id/date corrected: no 2026 edition exists; the actual 11th NRW NanoConference was Sep 30-Oct 1 2025 (Westfalenhalle Dortmund), already concluded — archiving under corrected id",
   "https://www.nanoconference.de/"),
ev("moc-2025",
   "30th Microoptics Conference","MOC 2025","Conference",
   "photonic integrated circuits;nanophotonics",
   "2025-10-12","2025-10-15","Tochigi, Japan",
   "2025-05-16","TBA","TBA","TBA",
   "TBA",3,
   "Micro- and nano-optics with PIC sessions","archived",
   "year roll-over from 2025 edition",
   "original list"),
ev("fio-2025",
   "Frontiers in Optics + Laser Science 2025","FiO+LS 2025","Conference",
   "quantum optics;nonlinear optics;nanophotonics",
   "2025-10-27","2025-10-30","Denver, CO, USA",
   "TBA","TBA","TBA","TBA",
   "https://frontiersinoptics.com/",3,
   "Broad US optics conference with quantum photonics components","archived",
   "year roll-over from 2025 edition",
   "https://frontiersinoptics.com/"),
ev("piers-fall-2025",
   "Photonics & Electromagnetics Research Symposium — Fall 2025","PIERS Fall 2025","Symposium",
   "photonic integrated circuits;nanophotonics",
   "2025-11-04","2025-11-08","Chiba, Japan",
   "TBA","TBA","TBA","TBA",
   "TBA",2,
   "General EM/photonics symposium; peripherally relevant","archived",
   "year roll-over from 2025 edition",
   "original list"),
ev("acp-2025",
   "Asia Communications and Photonics Conference 2025","ACP 2025","Conference",
   "photonic integrated circuits;quantum communication",
   "2025-11-05","2025-11-08","Jiangsu, China",
   "2025-08-01","TBA","TBA","TBA",
   "TBA",3,
   "Asia-Pacific photonics flagship with quantum sessions","archived",
   "year roll-over from 2025 edition",
   "original list"),
ev("ipc-2025",
   "IEEE Photonics Conference 2025","IPC 2025","Conference",
   "integrated quantum photonics;photonic integrated circuits;silicon photonics",
   "2025-11-09","2025-11-13","Singapore",
   "TBA","TBA","TBA","TBA",
   "https://ieee-ipc.org/",4,
   "IEEE flagship photonics devices and integrated systems conference","archived",
   "year roll-over from 2025 edition",
   "https://ieee-ipc.org/"),
ev("optima-2025",
   "Optical Communication, Photonics, Telecommunications, and Intelligent Machine Applications","OPTIMA 2025","Conference",
   "photonic integrated circuits",
   "2025-12-04","2025-12-05","Tashkent, Uzbekistan",
   "TBA","TBA","TBA","TBA",
   "TBA",2,
   "Regional optics/photonics conference; limited quantum scope","archived",
   "year roll-over from 2025 edition",
   "original list"),
ev("pgc-2025",
   "Photonics Global Conference 2025","PGC 2025","Conference",
   "photonic integrated circuits;nanophotonics",
   "2025-12-05","2025-12-08","Sanya, China",
   "TBA","TBA","TBA","TBA",
   "TBA",2,
   "Asia-Pacific photonics conference; some PIC tracks","archived",
   "year roll-over from 2025 edition",
   "original list"),
ev("icisct-2025",
   "International Conference on Information Science and Communications Technologies","ICISCT 2025","Conference",
   "quantum communication",
   "2025-12-26","2025-12-27","Kathmandu, Nepal",
   "TBA","TBA","TBA","TBA",
   "TBA",2,
   "Broad ICT conference; limited photonics scope","archived",
   "year roll-over from 2025 edition",
   "original list"),
ev("photonics-west-2026",
   "SPIE Photonics West 2026","PW 2026","Conference",
   "integrated quantum photonics;silicon photonics;nonlinear optics;single-photon sources",
   "2026-01-17","2026-01-22","San Francisco, CA, USA",
   "2025-07-09","TBA","TBA","TBA",
   "https://spie.org/photonics-west",5,
   "SPIE flagship with Quantum West and Si-photonics tracks","archived",
   "year roll-over; Photonics West 2027 now announced (Jan 30–Feb 4)",
   "https://spie.org/photonics-west"),
ev("qip-2026",
   "29th Quantum Information Processing Conference","QIP 2026","Conference",
   "quantum communication;quantum computing hardware;quantum networking",
   "2026-01-26","2026-01-30","Riga, Latvia",
   "2025-09-12","2025-10-10","TBA","TBA",
   "https://qip2026.lu.lv/",4,
   "Premier quantum information conference; networking and photonic hardware sessions","archived",
   "year roll-over; QIP 2027 Singapore announced",
   "https://qip2026.lu.lv/"),
ev("dpg-samop-2026",
   "DPG Frühjahrstagung SAMOP 2026","DPG SAMOP 2026","Conference",
   "quantum optics;nanophotonics;integrated quantum photonics",
   "2026-03-01","2026-03-06","Mainz, Germany",
   "TBA","TBA","TBA","TBA",
   "https://mainz26.dpg-tagungen.de",4,
   "German physics society AMO/photonics spring meeting — easily accessible from Münster","archived",
   "year roll-over; DPG SAMOP 2027 Hannover announced",
   "https://mainz26.dpg-tagungen.de"),
ev("nanolight-2026",
   "Nanolight Conference 2026","Nanolight 2026","Conference",
   "nanophotonics;2D-material photonics;quantum optics;plasmonics",
   "2026-03-02","2026-03-06","Benasque, Spain",
   "2025-12-15","n/a","2026-02-15","n/a",
   "https://benasque.org/2026nanolight/",5,
   "European nanophotonics / near-field / 2D-material flagship","archived",
   "year roll-over",
   "https://benasque.org/2026nanolight/"),
ev("dpg-skm-2026",
   "DPG Frühjahrstagung SKM 2026","DPG SKM 2026","Conference",
   "silicon photonics;nanophotonics;2D-material photonics",
   "2026-03-08","2026-03-13","Dresden, Germany",
   "TBA","TBA","TBA","TBA",
   "https://dresden26.dpg-tagungen.de",3,
   "Condensed matter sessions on photonics materials and devices","archived",
   "year roll-over",
   "https://dresden26.dpg-tagungen.de"),
ev("ofc-2026",
   "Optical Fiber Communication Conference 2026","OFC 2026","Conference",
   "photonic integrated circuits;silicon photonics;quantum communication",
   "2026-03-15","2026-03-19","Los Angeles, CA, USA",
   "TBA","TBA","TBA","TBA",
   "https://ofcconference.org/",4,
   "World's largest optical comms conference with PIC and quantum networking sessions","archived",
   "year roll-over; OFC 2027 Los Angeles Mar 7-11 announced",
   "https://ofcconference.org/"),
ev("aps-march-2026",
   "APS Global Physics Summit 2026","APS 2026","Conference",
   "quantum optics;quantum computing hardware;integrated quantum photonics",
   "2026-03-16","2026-03-20","Denver, CO, USA",
   "2025-10-31","2025-10-31","TBA","TBA",
   "https://summit.aps.org/",4,
   "Largest physics meeting; major quantum photonics and computing sessions","archived",
   "year roll-over; confirmed as joint March+April Global Physics Summit; APS 2027 Atlanta Apr 11-16",
   "https://summit.aps.org/; https://march.aps.org/"),
ev("spie-pe-2026",
   "SPIE Photonics Europe 2026","SPIE PE 2026","Conference",
   "integrated quantum photonics;silicon photonics;nanophotonics",
   "2026-04-12","2026-04-16","Strasbourg, France",
   "TBA","TBA","TBA","TBA",
   "https://spie.org/photonics-europe",5,
   "Major European SPIE photonics conference with quantum integrated sessions","archived",
   "year roll-over",
   "https://spie.org/photonics-europe"),
ev("ieee-siphotonics-2026",
   "IEEE Silicon Photonics Conference 2026","IEEE SiPho 2026","Conference",
   "silicon photonics;photonic integrated circuits;III-V on Si",
   "2026-04-13","2026-04-15","Ottawa, ON, Canada",
   "2025-10-03","TBA","TBA","TBA",
   "https://ieee-siphotonics.org/",5,
   "Dedicated silicon photonics conference — direct relevance to PICs","archived",
   "year roll-over",
   "https://ieee-siphotonics.org/"),
ev("ieee-qpain-2026",
   "IEEE 2nd International Conference on Quantum Photonics, AI & Networking","IEEE QPAIN 2026","Conference",
   "integrated quantum photonics;quantum networking",
   "2026-04-16","2026-04-18","Chattogram, Bangladesh",
   "TBA","TBA","TBA","TBA",
   "https://qpain.org/",3,
   "Quantum photonics and networking conference (IEEE-sponsored)","archived",
   "year roll-over",
   "https://qpain.org/"),
ev("inp-webinar-2026",
   "Webinar on InP platform for NIR and MIR applications","InP Webinar","Seminar",
   "photonic integrated circuits;III-V on Si",
   "2026-04-17","2026-04-17","Online",
   "TBA","n/a","TBA","n/a",
   "https://inphomir.eu/1st-webinar/",4,
   "III-V InP PIC platform — directly relevant to quantum light-source integration","archived",
   "year roll-over",
   "https://inphomir.eu/1st-webinar/"),
ev("eftf-2026",
   "European Frequency and Time Forum 2026","EFTF 2026","Conference",
   "quantum optics;quantum communication",
   "2026-04-20","2026-04-23","Noordwijk, The Netherlands",
   "TBA","TBA","TBA","TBA",
   "https://www.eftf.org/home",2,
   "Frequency/time standards; quantum photonic metrology peripherally relevant","archived",
   "year roll-over",
   "https://www.eftf.org/home"),
ev("spie-ds-2026",
   "SPIE Defense + Security 2026","SPIE D+S 2026","Conference",
   "single-photon sources;quantum communication",
   "2026-04-26","2026-04-30","National Harbor, MD, USA",
   "TBA","TBA","TBA","TBA",
   "https://spie.org/defense-and-commercial-sensing",2,
   "Defense photonics with some single-photon sensing sessions","archived",
   "year roll-over",
   "https://spie.org/defense-and-commercial-sensing"),
ev("bqit-2026",
   "Bristol Quantum Information Technologies Workshop 2026","BQIT 2026","Workshop",
   "integrated quantum photonics;quantum communication;quantum computing hardware",
   "2026-04-27","2026-04-29","Bristol, UK",
   "TBA","n/a","TBA","n/a",
   "https://www.bristol.ac.uk/qet-labs/events/bqit-workshop/",5,
   "UK quantum photonics workshop — PICs, single photons, quantum networking","archived",
   "year roll-over",
   "https://www.bristol.ac.uk/qet-labs/events/bqit-workshop/"),
ev("quantumatter-2026",
   "QUANTUMatter 2026","QUANTU 2026","Conference",
   "quantum computing hardware;quantum optics;nanophotonics",
   "2026-04-27","2026-04-30","Barcelona, Spain",
   "2026-02-11","n/a","2026-03-06","2026-02-23",
   "https://www.quantumconf.eu/2026/",3,
   "Quantum materials and devices, including photonic quantum systems","archived",
   "year roll-over",
   "https://www.quantumconf.eu/2026/"),
ev("ampd-2026",
   "Annual Meeting Photonic Devices 2026","AMPD 2026","Conference",
   "photonic integrated circuits;nanophotonics",
   "2026-04-28","2026-04-30","TBA",
   "TBA","TBA","TBA","TBA",
   "https://www.zib.de/workshop-photonic-devices/",4,
   "German photonic devices annual meeting — directly relevant to group's fabrication work","archived",
   "year roll-over",
   "https://www.zib.de/workshop-photonic-devices/"),
ev("cleo-2026",
   "Conference on Lasers and Electro-Optics 2026","CLEO 2026","Conference",
   "integrated quantum photonics;quantum optics;nonlinear optics;silicon photonics;single-photon sources",
   "2026-05-17","2026-05-21","Charlotte, NC, USA",
   "2025-11-18","n/a","TBA","TBA",
   "https://cleoconference.org/",5,
   "Premier US laser/photonics conference; major IQP, Si-PIC and quantum optics sessions","archived",
   "archived (event concluded)",
   "https://cleoconference.org/; https://cleoconference.org/registration-2026/"),
ev("damop-2026",
   "57th APS Division of Atomic, Molecular and Optical Physics Meeting","DAMOP 2026","Conference",
   "quantum optics;nonlinear optics;single-photon sources",
   "2026-06-01","2026-06-05","Providence, RI, USA",
   "TBA","TBA","TBA","TBA",
   "https://aps.org/events/2026/damop-meeting-2026",3,
   "AMO physics flagship with quantum optics and single-photon sessions","archived",
   "archived (event concluded)",
   "https://aps.org/events/2026/damop-meeting-2026"),
ev("photonics-north-2026",
   "Photonics North 2026","PN 2026","Conference",
   "silicon photonics;integrated quantum photonics;quantum communication",
   "2026-06-01","2026-06-04","TBA",
   "TBA","TBA","TBA","TBA",
   "TBA",3,
   "Canadian national photonics conference with PIC and quantum sessions","archived",
   "archived (event concluded)",
   "original list"),
ev("cargese-qt-2026",
   "Summer School on Quantum Technologies for Computation and Communication","QT4CC 2026","Summer School",
   "quantum communication;quantum computing hardware;quantum networking",
   "2026-06-08","2026-06-20","Cargèse (Corsica), France",
   "TBA","n/a","TBA","n/a",
   "https://qt4cc.sciencesconf.org/",4,
   "PhD summer school on quantum computation and communication — ideal for group's PhD students","archived",
   "archived (event concluded)",
   "https://qt4cc.sciencesconf.org/; https://gdr-teq.cnrs.fr/cevent/629/"),
ev("spie-pfq-2026",
   "SPIE Photonics for Quantum 2026","PfQ 2026","Conference",
   "integrated quantum photonics;single-photon sources;quantum communication;quantum computing hardware",
   "2026-06-08","2026-06-11","Waterloo, ON, Canada",
   "2026-03-01","n/a","TBA","TBA",
   "https://spie.org/conferences-and-exhibitions/photonics-for-quantum",5,
   "Dedicated quantum photonics conference — bullseye for AG Schuck","archived",
   "archived (event concluded)",
   "https://spie.org/PFQ26/conferencedetails/photonics-for-quantum"),
ev("grc-quantum-science-2026",
   "Gordon Research Conference — Quantum Science 2026","GRC QS 2026","Conference",
   "quantum optics;quantum computing hardware;quantum communication;integrated quantum photonics",
   "2026-06-14","2026-06-19","Easton, MA, USA",
   "TBA","n/a","2026-06-28","n/a",
   "https://www.grc.org/quantum-science-conference/2026/",4,
   "GRC on quantum science covering photonic quantum systems and quantum information","archived",
   "archived (event concluded)",
   "https://www.grc.org/quantum-science-conference/2026/"),
ev("icap-2026",
   "29th International Conference on Atomic Physics","ICAP 2026","Conference",
   "quantum optics;nonlinear optics",
   "2026-06-14","2026-06-19","Wuhan, China",
   "TBA","TBA","TBA","TBA",
   "https://www.icap29.com/home.html",3,
   "Atomic physics conference with quantum optics and light-matter interaction sessions","archived",
   "archived (event concluded)",
   "https://www.icap29.com/home.html"),
ev("islc-2026",
   "30th International Semiconductor Laser Conference","ISLC 2026","Conference",
   "single-photon sources;III-V on Si;photonic integrated circuits",
   "2026-06-14","2026-06-17","Tampere, Finland",
   "2026-02-05","TBA","TBA","TBA",
   "https://events.tuni.fi/islc2026/",4,
   "III-V semiconductor laser conference — key for quantum light source development","archived",
   "archived (event concluded)",
   "https://events.tuni.fi/islc2026/; https://ieeephotonics.org/event/2026-30th-international-semiconductor-laser-conference-islc/"),
ev("ecio-2026",
   "European Conference on Integrated Optics 2026","ECIO 2026","Conference",
   "integrated quantum photonics;photonic integrated circuits;silicon photonics;nanophotonics",
   "2026-06-15","2026-06-17","Zürich, Switzerland",
   "TBA","TBA","2026-06-01","2026-05-11",
   "https://ecio-conference.org/",5,
   "Largest European integrated optics conference — core relevance for AG Schuck","archived",
   "archived (event concluded)",
   "https://www.ecio-conference.org/; https://www.ecio-conference.org/deadlines/"),
ev("icop-2026",
   "Italian Conference on Optics and Photonics 2026","ICOP 2026","Conference",
   "integrated quantum photonics;quantum optics;nanophotonics",
   "2026-06-15","2026-06-17","L'Aquila, Italy",
   "TBA","TBA","TBA","TBA",
   "https://www.icop2026.it/",3,
   "Italian national photonics conference with quantum tracks","archived",
   "archived (event concluded)",
   "https://www.icop2026.it/"),
ev("optica-quantum-2026",
   "Optica Quantum 2.0 Conference and Exhibition 2026","Optica Quantum 2026","Conference",
   "integrated quantum photonics;quantum optics;single-photon sources;quantum communication;quantum computing hardware",
   "2026-06-15","2026-06-18","Glasgow, UK",
   "2026-02-10","n/a","2026-05-29","n/a",
   "https://www.optica.org/events/topical_meetings/quantum/",5,
   "Premier quantum photonics conference spanning PICs, detectors, QKD, and hardware","archived",
   "archived (event concluded)",
   "https://www.optica.org/events/topical_meetings/quantum/; https://www.optica.org/events/topical_meetings/quantum/registration/"),
ev("ccw-london-2026",
   "Critical Communications World London 2026","CCW 2026","Conference",
   "quantum communication;quantum networking",
   "2026-06-16","2026-06-18","London, UK",
   "TBA","TBA","TBA","TBA",
   "https://www.critical-communications-world.com/",2,
   "Critical comms industry event; QKD sessions of marginal relevance","archived",
   "archived (event concluded)",
   "https://www.critical-communications-world.com/call-for-content"),
ev("benasque-qsi-2026",
   "Quantum Science: Implementations 2026","Benasque QSI","Workshop",
   "integrated quantum photonics;quantum computing hardware;quantum communication",
   "2026-06-21","2026-07-04","Benasque, Spain",
   "TBA","n/a","TBA","n/a",
   "https://benasque.org/",4,
   "Benasque workshop on quantum implementations including photonic platforms","archived",
   "archived (event concluded)",
   "https://benasque.org/; https://www.benasque.org/new_general/cgi-bin/years.pl?ano=2026"),
ev("egas-2026",
   "57th Conference of the European Group on Atomic Systems","EGAS 2026","Conference",
   "quantum optics;nonlinear optics",
   "2026-06-21","2026-06-25","Toruń, Poland",
   "TBA","TBA","TBA","TBA",
   "https://egas57.org/",3,
   "European atomic systems conference with quantum optics and light-matter sessions","archived",
   "archived (event concluded)",
   "https://egas57.org/"),
ev("iqt-nordics-2026",
   "IQT Nordics 2026 — Quantum Technology in a Changing World","IQT Nordics 2026","Conference",
   "quantum communication;quantum computing hardware;integrated quantum photonics",
   "2026-06-22","2026-06-24","Oslo, Norway",
   "TBA","n/a","TBA","TBA",
   "https://iqtevent.com/nordics/",3,
   "Nordic quantum industry conference with hardware and QKD sessions","archived",
   "archived (event concluded)",
   "https://iqtevent.com/nordics/; https://www.oslomet.no/en/about/events/iqt-nordics-2026"),
ev("les-houches-pa-2026",
   "Photons & Atoms 2026 — Les Houches Doctoral School","Les Houches PA 2026","Summer School",
   "quantum optics;nonlinear optics;integrated quantum photonics;single-photon sources",
   "2026-06-22","2026-07-03","Les Houches, France",
   "TBA","n/a","TBA","n/a",
   "https://photon-atoms-26.leshouches.science/",5,
   "Leading European doctoral school on photons, quantum gases and quantum technologies","archived",
   "archived (event concluded)",
   "https://photon-atoms-26.leshouches.science/; https://first-tf.com/doctoral-training-on-atoms-and-photons-ecole-de-physique-des-houches-france-june-22nd-to-july-3rd-2026/"),
ev("quantum-tech-world-2026",
   "Quantum.Tech World 2026","Q.Tech World 2026","Conference",
   "quantum computing hardware;quantum communication;integrated quantum photonics",
   "2026-06-25","2026-06-26","Boston, MA, USA",
   "TBA","n/a","TBA","TBA",
   "https://www.alphaevents.com/events-quantumtechus",2,
   "Industry quantum technology event; limited deep-science content","archived",
   "archived (event concluded)",
   "https://www.alphaevents.com/events-quantumtechus"),
ev("oecc-2026",
   "31st OptoElectronics and Communications Conference","OECC 2026","Conference",
   "photonic integrated circuits;silicon photonics;quantum communication",
   "2026-06-28","2026-07-02","Busan, South Korea",
   "TBA","TBA","TBA","TBA",
   "TBA",3,
   "Asia-Pacific optoelectronics and comms conference with PIC sessions","archived",
   "archived (event concluded)",
   "original list"),
ev("quantum-korea-2026",
   "Quantum Korea 2026","Quantum Korea 2026","Conference",
   "quantum computing hardware;quantum communication;integrated quantum photonics",
   "2026-07-02","2026-07-04","Seoul, South Korea",
   "TBA","n/a","TBA","TBA",
   "https://quantum-korea.kr/en/main",2,
   "Government-organised Korean quantum technology showcase","archived",
   "archived (event concluded)",
   "https://quantum-korea.kr/en/main"),
ev("spw-2026",
   "12th Single Photon Workshop","SPW 2026","Workshop",
   "single-photon sources;SNSPDs;quantum optics;quantum communication",
   "2026-07-06","2026-07-10","Naples, Italy",
   "TBA","n/a","TBA","TBA",
   "https://spw2026.org/",5,
   "THE dedicated single-photon workshop — central to AG Schuck's detector and source work","archived",
   "archived (event concluded)",
   "https://spw2026.org/; https://iqnhub.org/2026-single-photon-workshop-registration-open/"),
ev("icton-2026",
   "26th International Conference on Transparent Optical Networks","ICTON 2026","Conference",
   "photonic integrated circuits;silicon photonics;quantum communication",
   "2026-07-12","2026-07-16","Prague, Czech Republic",
   "TBA","TBA","TBA","TBA",
   "https://www.gov.pl/web/instytut-lacznosci/icton-2026",3,
   "Transparent optical networks with PIC and quantum photonics tracks","archived",
   "archived (event concluded)",
   "https://www.gov.pl/web/instytut-lacznosci/icton-2026"),
ev("ieee-sum-2026",
   "IEEE Summer Topicals Meeting Series 2026","IEEE SUM 2026","Conference",
   "photonic integrated circuits;silicon photonics;integrated quantum photonics",
   "2026-07-13","2026-07-15","Tulum, Mexico",
   "TBA","TBA","TBA","TBA",
   "https://ieee-sum.org/",3,
   "IEEE focused topical photonics sessions","archived",
   "archived (event concluded)",
   "https://ieee-sum.org/"),
ev("grc-plasmonics-nano-2026",
   "Gordon Research Conference — Plasmonics and Nanophotonics 2026","GRC PNP 2026","Conference",
   "nanophotonics;plasmonics;quantum optics;2D-material photonics",
   "2026-07-19","2026-07-24","Newry, ME, USA",
   "TBA","n/a","2026-06-21","n/a",
   "https://www.grc.org/plasmonics-and-nanophotonics-conference/2026/",5,
   "GRC on quantum nanophotonics, plasmonics and 2D photonics — highly relevant to AG Schuck","archived",
   "archived (event concluded)",
   "https://www.grc.org/plasmonics-and-nanophotonics-conference/2026/"),
ev("cewqo-2026",
   "30th Central European Workshop on Quantum Optics","CEWQO30 2026","Workshop",
   "quantum optics;single-photon sources;nonlinear optics;integrated quantum photonics",
   "2026-07-20","2026-07-24","Erlangen, Germany",
   "TBA","n/a","TBA","n/a",
   "https://www.lightmatter.fau.de/2026/04/cewqo30-the-30th-central-european-workshop-on-quantum-optics-2026/",5,
   "European quantum optics workshop co-hosted by FAU/MPL Erlangen — close to Münster","archived",
   "archived (event concluded)",
   "https://www.lightmatter.fau.de/2026/04/cewqo30-the-30th-central-european-workshop-on-quantum-optics-2026/; https://www.oqt.nat.fau.de/events/"),
ev("apc-2026",
   "Optica Advanced Photonics Congress 2026","APC 2026","Conference",
   "integrated quantum photonics;nonlinear optics;nanophotonics",
   "2026-07-26","2026-07-30","TBA",
   "TBA","TBA","TBA","TBA",
   "https://www.optica.org/events/congress/advanced_photonics_congress/",4,
   "Optica congress including nonlinear photonics, waveguides and integrated circuits","archived",
   "archived (event concluded)",
   "https://www.optica.org/events/congress/advanced_photonics_congress/"),
ev("grc-mech-quant-2026",
   "Gordon Research Conference — Mechanical Systems in the Quantum Regime 2026","GRC MSQR 2026","Conference",
   "optomechanics;quantum computing hardware",
   "2026-07-26","2026-07-31","Lucca (Barga), Italy",
   "TBA","n/a","TBA","n/a",
   "https://www.grc.org/mechanical-systems-in-the-quantum-regime-conference/2026/",4,
   "Optomechanics GRC — relevant to cavity-optomechanical quantum transducers","archived",
   "archived (event concluded)",
   "https://www.grc.org/mechanical-systems-in-the-quantum-regime-conference/2026/"),
ev("lake-como-ufqp-2026",
   "New Frontiers in Ultrafast Quantum Optics — Lake Como School","UFQP 2026","Summer School",
   "quantum optics;nonlinear optics;single-photon sources",
   "2026-07-27","2026-07-31","Como, Italy",
   "2026-05-31","n/a","TBA","n/a",
   "https://ufqp.lakecomoschool.org/",4,
   "Summer school on ultrafast quantum optics — photon correlations and time-frequency entanglement","archived",
   "archived (event concluded)",
   "https://ufqp.lakecomoschool.org/; https://www.quantiki.org/conference/summer-school-new-frontiers-ultrafast-quantum-optics"),
ev("ieee-rapid-2026",
   "IEEE Research and Applications of Photonics in Defense 2026","IEEE RAPID 2026","Conference",
   "single-photon sources;quantum communication",
   "2026-08-05","2026-08-07","Miramar Beach, FL, USA",
   "TBA","TBA","TBA","TBA",
   "https://ieee-rapid.org/",2,
   "Defense photonics; some single-photon sensing sessions","archived",
   "archived (event concluded)",
   "https://ieee-rapid.org/"),
ev("spie-op-2026",
   "SPIE Optics + Photonics 2026","SPIE O+P 2026","Conference",
   "integrated quantum photonics;nanophotonics;quantum optics;single-photon sources",
   "2026-08-23","2026-08-27","San Diego, CA, USA",
   "TBA","TBA","TBA","TBA",
   "https://spie.org/optics-and-photonics",4,
   "SPIE major annual meeting with quantum nanophotonics and quantum technologies tracks","archived",
   "archived (event concluded)",
   "https://spie.org/optics-and-photonics"),
ev("eosam-2026",
   "European Optical Society Annual Meeting 2026","EOSAM 2026","Conference",
   "integrated quantum photonics;nanophotonics;nonlinear optics",
   "2026-08-24","2026-08-28","Tampere, Finland",
   "TBA","TBA","TBA","TBA",
   "https://www.europeanoptics.org/events/eos/eosam2026.html",4,
   "EOS flagship European photonics meeting with strong quantum photonics programme","archived",
   "archived (event concluded)",
   "https://www.europeanoptics.org/events/eos/eosam2026.html"),
ev("qcrypt-2026",
   "QCrypt 2026","QCrypt 2026","Conference",
   "quantum communication;QKD;quantum networking",
   "2026-08-24","2026-08-28","Ottawa, Canada",
   "TBA","TBA","TBA","TBA",
   "https://qcrypt.net/2026/",4,
   "Premier annual QKD and quantum cryptography conference","archived",
   "archived (event concluded)",
   "https://qcrypt.net/2026/"),
ev("tqc-2026",
   "Theory of Quantum Computation, Communication and Cryptography 2026","TQC 2026","Conference",
   "quantum communication;quantum computing hardware;quantum networking",
   "2026-08-31","2026-09-04","Sherbrooke, QC, Canada",
   "TBA","TBA","TBA","TBA",
   "https://tqc-conference.org/2026/",3,
   "Theory conference for quantum communication, computation and cryptography","archived",
   "archived (event concluded)",
   "https://tqc-conference.org/2026/"),
ev("asc-2026",
   "Applied Superconductivity Conference 2026","ASC 2026","Conference",
   "SNSPDs;cryogenic electronics;single-photon sources",
   "2026-09-06","2026-09-11","Pittsburgh, PA, USA",
   "TBA","TBA","TBA","TBA",
   "https://appliedsuperconductivity.org/asc2026/",4,
   "Premier superconductivity conference with major SNSPD and cryogenic electronics sessions","archived",
   "archived (event concluded)",
   "https://appliedsuperconductivity.org/asc2026/"),
ev("inphomir-school-2026",
   "INPHOMIR Photonics School 2026","INPHOMIR School","Summer School",
   "photonic integrated circuits;III-V on Si",
   "2026-09-07","2026-09-11","Bari, Italy",
   "TBA","n/a","TBA","n/a",
   "https://inphomir.eu/inphomir-school-program/",4,
   "Dedicated InP/III-V photonics school for NIR/MIR applications","archived",
   "archived (event concluded)",
   "https://inphomir.eu/inphomir-school-program/"),
ev("opon-2025",
   "OPON 2025 Münster","OPON 2025","Conference",
   "integrated quantum photonics;nanophotonics",
   "TBA","TBA","Münster, Germany",
   "TBA","TBA","TBA","TBA",
   "TBA",4,
   "Local Münster photonics conference — direct access, no travel","archived",
   "confirmed: OPON (8th ed., Optical Properties of Nanostructures workshop) took place April 2025 in Münster (exact day not recoverable); series rotates among Münster/Wrocław/Bayreuth/Warsaw",
   "https://www.uni-muenster.de/Physik.FT/en/opon2025/index.html"),
ev("ieee-qce26",
   "IEEE Quantum Week 2026","QCE26","Conference",
   "quantum computing hardware;quantum communication;integrated quantum photonics",
   "2026-09-13","2026-09-18","Toronto, ON, Canada",
   "TBA","TBA","TBA","TBA",
   "https://qce.quantum.ieee.org/2026/",3,
   "IEEE quantum week with photonic quantum computing and QKD sessions","ongoing",
   "ongoing (in progress as of snapshot date)",
   "https://qce.quantum.ieee.org/2026/"),
ev("photonics-switching-2026",
   "Photonics in Switching and Computing 2026","PiS 2026","Conference",
   "photonic integrated circuits;silicon photonics",
   "2026-09-15","2026-09-18","Valencia, Spain",
   "TBA","TBA","TBA","TBA",
   "https://psc2026.org/",3,
   "Photonic switching and routing conference","upcoming",
   "dates/location confirmed: Photonics in Switching and Computing 2026, Sep 15-18, Valencia (starts in 2 days)",
   "https://psc2026.org/"),
ev("bad-honnef-photonics-2026",
   "Applied Photonics — DPG Physics School","Bad Honnef Photonics","Summer School",
   "nanophotonics;quantum optics;photonic integrated circuits",
   "2026-09-20","2026-09-25","Bad Honnef, Germany",
   "TBA","n/a","TBA","n/a",
   "https://www.appliedphotonics.de/",3,
   "DPG physics school on applied photonics incl. a quantum-systems module","upcoming",
   "new entry",
   "https://www.appliedphotonics.de/; https://www.dpg-physik.de/veranstaltungen/2026/applied_photonics"),
ev("ecoc-2026",
   "European Conference on Optical Communication 2026","ECOC 2026","Conference",
   "photonic integrated circuits;silicon photonics;quantum communication;integrated quantum photonics",
   "2026-09-20","2026-09-24","Málaga, Spain",
   "2026-04-22","2026-04-22","TBA","2026-09-03",
   "https://ecoc2026.org/",4,
   "Europe's flagship optical comms conference with quantum technologies track","cfp_closed",
   "added early-bird registration deadline (2026-09-03, now closed); dates/venue reconfirmed",
   "https://ecoc2026.org/; https://ecoc2026.org/ECOC2026/paper-submission; https://www.ecocexhibition.com/future-dates/"),
ev("mne-2026",
   "International Conference on Micro and Nano Engineering 2026","MNE 2026","Conference",
   "photonic integrated circuits;nanophotonics;2D-material photonics",
   "2026-09-21","2026-09-24","Interlaken, Switzerland",
   "TBA","TBA","TBA","TBA",
   "https://mne2026.imnes.org/",3,
   "Nanofabrication conference relevant to photonic device processing","upcoming",
   "no change",
   "https://mne2026.imnes.org/"),
ev("fio-2026",
   "Frontiers in Optics + Laser Science 2026","FiO+LS 2026","Conference",
   "quantum optics;nonlinear optics;nanophotonics",
   "2026-09-27","2026-10-01","Rochester, NY, USA",
   "TBA","TBA","TBA","TBA",
   "https://frontiersinoptics.com/",3,
   "Broad US photonics conference with quantum optics tracks","upcoming",
   "end date corrected 09-30 -> 10-01 per Optica global calendar (tech conf runs through Oct 1; exhibition Sep29-30)",
   "https://frontiersinoptics.com/; https://www.optica.org/events/global_calendar/events/2026/fio_ls_2026/"),
ev("qps-2026",
   "Quantum Photonics Spotlight 2026","QPS2026","Conference",
   "integrated quantum photonics;single-photon sources;quantum communication",
   "2026-09-28","2026-10-01","Paderborn, Germany",
   "TBA","n/a","TBA","n/a",
   "https://phoqs.uni-paderborn.de/en/veranstaltungen/quantum-photonics-spotlight-2026",5,
   "Hosted by Paderborn's Institute for Photonic Quantum Systems (PhoQS); spans the full photonic quantum tech development chain — bullseye for AG Schuck","upcoming",
   "new entry; end date reported as Oct 1 or Oct 2 in different sources, verify on site",
   "https://phoqs.uni-paderborn.de/en/veranstaltungen/quantum-photonics-spotlight-2026; https://www.idquantique.com/quantum-photonics-spotlight-2026/"),
ev("hdqs-2026",
   "High-Dimensional Quantum Systems Workshop 2026","HDQS 2026","Workshop",
   "quantum optics;quantum communication;integrated quantum photonics",
   "2026-10-04","2026-10-09","Benasque, Spain",
   "TBA","n/a","TBA","n/a",
   "https://benasque.org/2026hdqs/",4,
   "Benasque workshop on high-dimensional quantum photonics and quantum information","upcoming",
   "dates unverified this run (conflicting search snippets: Oct4-9 vs Oct5-8 vs Sep20-Oct3); kept prior Oct 4-9 pending direct check of benasque.org/2026hdqs/",
   "https://benasque.org/2026hdqs/"),
ev("quantum-effects-2026",
   "Quantum Effects 2026","Quantum Effects 2026","Conference",
   "quantum communication;quantum computing hardware",
   "2026-10-06","2026-10-07","Stuttgart, Germany",
   "TBA","n/a","TBA","n/a",
   "https://www.squad-germany.de/en/quantum-effects-2026-2/",3,
   "Germany's leading application-oriented quantum tech conference/trade fair; covers quantum communication pillar","upcoming",
   "new entry",
   "https://www.squad-germany.de/en/quantum-effects-2026-2/"),
ev("photonics-days-2026",
   "Photonics Days Berlin 2026","PDB 2026","Conference",
   "integrated quantum photonics;photonic integrated circuits;nanophotonics",
   "2026-10-07","2026-10-08","Berlin, Germany",
   "TBA","TBA","TBA","TBA",
   "https://photonic-days-berlin.com/",3,
   "German photonics industry and research meeting","upcoming",
   "no change",
   "https://photonic-days-berlin.com/"),
ev("epic-manufacturing-2026",
   "EPIC Workshop on Efficient Manufacturing — Photonics made in Europe","EPIC EM 2026","Workshop",
   "photonic integrated circuits;silicon photonics",
   "2026-10-13","2026-10-14","Milan, Italy",
   "n/a","n/a","TBA","n/a",
   "https://epic-photonics.com/epic-events/",3,
   "European Photonics Industry Consortium workshop on scalable PIC manufacturing","upcoming",
   "new entry",
   "https://epic-photonics.com/epic-events/"),
ev("it-fab-school-2026",
   "It-fab Italian Network for Micro and Nano Fabrication School 2026","It-fab School 2026","Summer School",
   "photonic integrated circuits;nanophotonics",
   "2026-10-27","2026-10-30","Turin, Italy",
   "TBA","n/a","TBA","n/a",
   "https://itfab.bo.imm.cnr.it/",3,
   "Italian nanofabrication school relevant to photonic device processing","upcoming",
   "dates/location confirmed: It-fab Hands-On School, Oct 27-30 2026, INRiM Turin (with STMicroelectronics Italy)",
   "https://itfab.bo.imm.cnr.it/"),
ev("ipc-2026",
   "IEEE Photonics Conference 2026","IPC 2026","Conference",
   "integrated quantum photonics;photonic integrated circuits;silicon photonics",
   "2026-11-08","2026-11-12","Denver, CO, USA",
   "TBA","TBA","TBA","TBA",
   "https://ieee-ipc.org/",4,
   "IEEE flagship photonics devices and integrated systems conference","upcoming",
   "no change",
   "https://ieee-ipc.org/"),
ev("eqtc-2026",
   "European Quantum Technologies Conference 2026","EQTC 2026","Conference",
   "integrated quantum photonics;quantum communication;quantum computing hardware;quantum networking",
   "2026-11-30","2026-12-03","Dublin, Ireland",
   "TBA","TBA","TBA","TBA",
   "https://qt.eu/events/eqtc-2026-european-quantum-technologies-conference",5,
   "EU Quantum Flagship conference — all aspects of quantum technology, high visibility","upcoming",
   "start date corrected 11-29 -> 11-30 per Quantum Flagship + semiconductorcalendar.com; registration now open",
   "https://qt.eu/events/eqtc-2026-european-quantum-technologies-conference"),
ev("q2b-chicago-2026",
   "Q2B Chicago 2026","Q2B Chicago 2026","Conference",
   "quantum computing hardware;quantum communication",
   "2026-12-08","2026-12-10","Chicago, IL, USA",
   "TBA","n/a","TBA","TBA",
   "https://q2b.qcware.com/conference/2026-chicago",2,
   "Industry quantum computing conference; December 2026 US edition of Q2B series","upcoming",
   "new entry",
   "https://q2b.qcware.com/conference/2026-chicago"),
ev("photonics-west-2027",
   "SPIE Photonics West 2027","PW 2027","Conference",
   "integrated quantum photonics;silicon photonics;nonlinear optics;single-photon sources",
   "2027-01-30","2027-02-04","San Francisco, CA, USA",
   "2026-07-22","TBA","TBA","TBA",
   "https://spie.org/conferences-and-exhibitions/photonics-west",5,
   "SPIE flagship with Quantum West and Si-photonics tracks — abstract deadline Jul 22 2026","upcoming",
   "new entry; Jan 30–Feb 4 2027; abstract deadline 2026-07-22",
   "https://spie.org/conferences-and-exhibitions/photonics-west; https://spie.org/conferences-and-exhibitions/photonics-west/program/browse-program"),
ev("qip-2027",
   "30th Quantum Information Processing Conference","QIP 2027","Conference",
   "quantum communication;quantum computing hardware;quantum networking",
   "2027-02-20","2027-02-26","Singapore",
   "2026-09-28","2026-10-05","TBA","TBA",
   "https://qipconference.org/2027/",4,
   "Premier annual quantum information conference; quantum networking and hardware sessions","upcoming",
   "added talk-submission window: registration due 2026-09-28, submission due 2026-10-05",
   "https://qipconference.org/2027/; https://qipconference.org/2027/call/; https://www.cqt.sg/upcoming-events/"),
ev("dpg-samop-2027",
   "DPG Frühjahrstagung SAMOP 2027","DPG SAMOP 2027","Conference",
   "quantum optics;nanophotonics;integrated quantum photonics",
   "2027-02-28","2027-03-05","Hannover, Germany",
   "TBA","TBA","TBA","TBA",
   "https://www.hannover27.dpg-tagungen.de/",4,
   "DPG spring meeting for quantum optics and photonics — easily accessible from Münster","upcoming",
   "official 2027 site located (hannover27.dpg-tagungen.de); submission/registration deadlines not yet published",
   "https://www.dpg-physik.de/veranstaltungen/2027/dpg-fruehjahrstagung-hannover; https://www.hannover27.dpg-tagungen.de/"),
ev("ofc-2027",
   "Optical Fiber Communication Conference 2027","OFC 2027","Conference",
   "photonic integrated circuits;silicon photonics;quantum communication",
   "2027-03-07","2027-03-11","Los Angeles, CA, USA",
   "TBA","TBA","TBA","TBA",
   "https://ofcconference.org/",4,
   "World's largest optical comms conference with PIC and quantum networking sessions","upcoming",
   "new entry; Mar 7-11 2027 Los Angeles",
   "https://ofcconference.org/"),
ev("dpg-skm-2027",
   "DPG Frühjahrstagung SKM 2027 (90th DPG Jahrestagung)","DPG SKM 2027","Conference",
   "silicon photonics;nanophotonics;2D-material photonics",
   "2027-03-14","2027-03-19","Regensburg, Germany",
   "TBA","TBA","TBA","TBA",
   "https://www.dpg-physik.de/veranstaltungen/2027/dpg-fruehjahrstagung-regensburg",3,
   "Condensed matter sessions on photonics materials and devices","upcoming",
   "new entry",
   "https://www.dpg-physik.de/veranstaltungen/2027/dpg-fruehjahrstagung-regensburg"),
ev("benasque-qnp-2027",
   "Quantum Nanophotonics 2027","Benasque QNP 2027","Workshop",
   "nanophotonics;quantum optics;single-photon sources",
   "2027-03-28","2027-04-02","Benasque, Spain",
   "TBA","n/a","TBA","n/a",
   "https://www.benasque.org/2027quantumnanophotonics/",5,
   "Directly on nanophotonics and single-photon sources","upcoming",
   "new entry",
   "https://www.benasque.org/2027quantumnanophotonics/"),
ev("spie-oo-2027",
   "SPIE Optics + Optoelectronics 2027","SPIE O+O 2027","Conference",
   "integrated quantum photonics;quantum optics;nanophotonics",
   "2027-04-05","2027-04-08","Prague, Czech Republic",
   "TBA","TBA","TBA","TBA",
   "TBA",4,
   "SPIE European conference with quantum photonics and nanophotonics tracks","upcoming",
   "location Prague reconfirmed via spie.org (2027-titled page live); abstract deadline not yet published",
   "original list"),
ev("benasque-sqt-2027",
   "Spring School on Superconducting Qubit Technology 2027","Benasque SQT 2027","Summer School",
   "quantum computing hardware;cryogenic electronics",
   "2027-04-06","2027-04-16","Benasque, Spain",
   "TBA","n/a","TBA","n/a",
   "https://www.benasque.org/2027sqt/",3,
   "Cryogenic electronics for qubit control, adjacent to photonic detector systems","upcoming",
   "new entry",
   "https://www.benasque.org/2027sqt/"),
ev("aps-summit-2027",
   "APS Global Physics Summit 2027","APS Summit 2027","Conference",
   "quantum optics;quantum computing hardware;integrated quantum photonics",
   "2027-04-11","2027-04-16","Atlanta, GA, USA",
   "2026-10-22","TBA","TBA","TBA",
   "https://www.aps.org/events/2027/summit",4,
   "Joint APS March+April meeting; major quantum photonics and computing sessions","upcoming",
   "added call-for-abstracts window (opens 2026-09-09, closes 2026-10-22)",
   "https://www.aps.org/events/2027/summit; https://summit.aps.org/attend/abstracts/"),
ev("opic-2027",
   "Optics & Photonics International Congress","OPIC","Conference",
   "integrated quantum photonics;quantum optics;nanophotonics",
   "2027-04-19","2027-04-23","Yokohama, Japan",
   "TBA","TBA","TBA","TBA",
   "https://opicon.jp/",3,
   "Japanese international photonics congress with quantum tracks","upcoming",
   "next edition confirmed: OPIC2027, Apr 19-23 2027, PACIFICO Yokohama (15 co-located conferences incl. OPIE)",
   "https://opicon.jp/"),
ev("cleo-2027",
   "Conference on Lasers and Electro-Optics 2027","CLEO 2027","Conference",
   "integrated quantum photonics;quantum optics;nonlinear optics;silicon photonics;single-photon sources",
   "2027-05-02","2027-05-07","Long Beach, CA, USA",
   "TBA","n/a","TBA","TBA",
   "https://cleoconference.org/",5,
   "Premier US laser/photonics conference; major IQP, Si-PIC and quantum optics sessions","upcoming",
   "new entry",
   "https://cleoconference.org/; https://cleoconference.org/2027-topic-categories/"),
ev("optica-quantum-2027",
   "Optica Quantum 2.0 Conference and Exhibition 2027","Optica Quantum 2027","Conference",
   "integrated quantum photonics;quantum optics;single-photon sources;quantum communication;quantum computing hardware",
   "2027-06-07","2027-06-10","Copenhagen, Denmark",
   "TBA","n/a","TBA","TBA",
   "https://www.optica.org/events/topical_meetings/quantum/",5,
   "Premier global quantum photonics conference covering PICs, single photons, QKD, hardware","upcoming",
   "new entry",
   "https://www.optica.org/events/topical_meetings/quantum/"),
ev("benasque-qi-2027",
   "Quantum Information 2027","Benasque QI 2027","Workshop",
   "quantum communication;quantum optics",
   "2027-06-20","2027-07-09","Benasque, Spain",
   "TBA","n/a","TBA","n/a",
   "https://benasque.org/",3,
   "Quantum information including QKD and networking","upcoming",
   "new entry",
   "https://benasque.org/"),
ev("cleo-europe-2027",
   "CLEO/Europe-EQEC 2027","CLEO/Europe 2027","Conference",
   "integrated quantum photonics;quantum optics;nonlinear optics;nanophotonics",
   "2027-06-20","2027-06-25","Munich, Germany",
   "TBA","TBA","TBA","TBA",
   "https://cleoeurope.org/",5,
   "Flagship European photonics and quantum optics biennial conference","upcoming",
   "dates reconfirmed as part of World of Photonics Congress 2027 (Jun 20-25, Munich); CLEO-specific day range (20 vs 21 start) to be confirmed once cleoeurope.org rolls over to 2027",
   "https://cleoeurope.org/; https://www.photonics-congress.com/en/about/conferences/cleo-eqec/"),
ev("grc-plasmonics-nano-2027",
   "Gordon Research Conference — Plasmonics and Nanophotonics 2027","GRC PNP 2027","Conference",
   "nanophotonics;plasmonics;quantum optics;2D-material photonics",
   "2027-07-25","2027-07-30","TBA, USA",
   "n/a","n/a","TBA","n/a",
   "https://www.grc.org/plasmonics-and-nanophotonics-conference/2027/",5,
   "GRC on quantum nanophotonics, plasmonics and 2D photonics — highly relevant to AG Schuck","upcoming",
   "new entry; exact venue not yet confirmed",
   "https://www.grc.org/plasmonics-and-nanophotonics-conference/2027/"),
ev("grc-qclm-2027",
   "Gordon Research Conference — Quantum Control of Light and Matter 2027 (+GRS)","GRC QCLM 2027","Conference",
   "quantum optics;single-photon sources;quantum communication",
   "2027-07-31","2027-08-06","Newport, RI, USA",
   "n/a","n/a","2027-07-04","n/a",
   "https://www.grc.org/quantum-control-of-light-and-matter-conference/2027/",4,
   "GRC directly on quantum optics/light-matter control; includes associated GRS Jul31-Aug1","upcoming",
   "new entry",
   "https://www.grc.org/quantum-control-of-light-and-matter-conference/2027/"),
ev("ieee-rapid-2027",
   "IEEE Research and Applications of Photonics in Defense 2027","IEEE RAPID 2027","Conference",
   "single-photon sources;quantum communication",
   "2027-08-11","2027-08-13","Miramar Beach, FL, USA",
   "TBA","TBA","TBA","TBA",
   "https://ieee-rapid.org/",2,
   "Defense photonics conference","upcoming",
   "dates unverified this run (sources conflict: Aug11 / Aug11-13 / Sep11-13); kept prior Aug 11-13, recheck ieee-rapid.org once it publishes a 2027 page",
   "https://ieee-rapid.org/"),
ev("qcrypt-2027",
   "QCrypt 2027","QCrypt 2027","Conference",
   "quantum communication;QKD;quantum networking",
   "2027-08-23","2027-08-27","Vienna, Austria",
   "TBA","TBA","TBA","TBA",
   "https://qcrypt.net/2026/2027/",4,
   "Premier annual quantum cryptography and QKD conference","upcoming",
   "new entry",
   "https://qcrypt.net/2026/2027/"),
ev("ecoc-2027",
   "European Conference on Optical Communication 2027 (53rd ECOC)","ECOC 2027","Conference",
   "photonic integrated circuits;silicon photonics;quantum communication;integrated quantum photonics",
   "2027-10-10","2027-10-14","Milano, Italy",
   "TBA","TBA","TBA","TBA",
   "https://ecoc2027.org/",4,
   "Europe's flagship optical comms conference with quantum technologies track","upcoming",
   "new entry",
   "https://ecoc2027.org/; https://www.ecocexhibition.com/exhibitor/ecoc-2027/"),
ev("spw-2027",
   "13th Single Photon Workshop","SPW 2027","Workshop",
   "single-photon sources;SNSPDs;quantum optics;quantum communication",
   "2027-11-15","2027-11-19","Singapore",
   "TBA","n/a","TBA","TBA",
   "https://spw2026.org/",5,
   "THE dedicated single-photon workshop — central to AG Schuck's detector and source work","upcoming",
   "new entry; successor to SPW 2026 Naples",
   "https://spw2026.org/"),
ev("aps-summit-2028",
   "APS Global Physics Summit 2028","APS 2028","Conference",
   "quantum optics;quantum computing hardware;integrated quantum photonics",
   "2028-03-12","2028-03-17","Chicago, IL, USA",
   "TBA","TBA","TBA","TBA",
   "https://www.aps.org/",4,
   "Largest physics meeting; major quantum photonics and computing sessions","upcoming",
   "new entry; dates from secondary sources, verify on aps.org closer to date",
   "https://www.aps.org/"),
ev("ofc-2028",
   "Optical Fiber Communication Conference 2028","OFC 2028","Conference",
   "photonic integrated circuits;silicon photonics;quantum communication",
   "2028-03-26","2028-03-30","Los Angeles, CA, USA",
   "TBA","TBA","TBA","TBA",
   "https://www.ofcconference.org/",4,
   "World's largest optical comms conference with PIC and quantum networking sessions","upcoming",
   "new entry",
   "https://www.ofcconference.org/"),
ev("spie-pe-2028",
   "SPIE Photonics Europe 2028","SPIE PE 2028","Conference",
   "integrated quantum photonics;silicon photonics;nanophotonics",
   "2028-04-02","2028-04-06","Strasbourg, France",
   "TBA","TBA","TBA","TBA",
   "https://spie.org/photonics-europe",5,
   "Major European SPIE photonics conference; biennial — next after 2026 Strasbourg","upcoming",
   "new entry; dates from secondary sources, verify directly on spie.org closer to date",
   "https://spie.org/photonics-europe"),
ev("asc-2028",
   "Applied Superconductivity Conference 2028","ASC 2028","Conference",
   "SNSPDs;cryogenic electronics;single-photon sources",
   "TBA","TBA","TBA",
   "TBA","TBA","TBA","TBA",
   "https://appliedsuperconductivity.org/",4,
   "Premier superconductivity conference with major SNSPD and cryogenic electronics sessions; biennial (even years), next after 2026 Pittsburgh","upcoming",
   "new entry; placeholder, dates not yet announced",
   "https://appliedsuperconductivity.org/"),
ev("benasque-qsi-2027",
   "Quantum Science: Implementations 2027","Benasque QSI 2027","Workshop",
   "integrated quantum photonics;quantum computing hardware;quantum communication",
   "TBA","TBA","Benasque, Spain",
   "TBA","n/a","TBA","n/a",
   "https://benasque.org/",4,
   "Benasque workshop on quantum implementations including photonic platforms","upcoming",
   "new entry; placeholder — not yet posted for 2027, monitor benasque.org",
   "https://benasque.org/"),
ev("cargese-qt-2027",
   "Summer School on Quantum Technologies — next edition","QT4CC 2027","Summer School",
   "quantum communication;quantum computing hardware;quantum networking",
   "TBA","TBA","Cargèse (Corsica), France",
   "TBA","n/a","TBA","n/a",
   "https://iesc.universita.corsica/",4,
   "PhD summer school on quantum computation and communication — ideal for group's PhD students","upcoming",
   "new entry; placeholder — successor to 2026 edition not yet confirmed, series recurrence unclear",
   "https://iesc.universita.corsica/"),
ev("dpg-samop-2028",
   "DPG Frühjahrstagung SAMOP 2028","DPG SAMOP 2028","Conference",
   "quantum optics;nanophotonics;integrated quantum photonics",
   "TBA","TBA","TBA",
   "TBA","TBA","TBA","TBA",
   "https://www.dpg-physik.de/aktivitaeten-und-programme/tagungen/fruehjahrstagungen/2028",4,
   "German physics society AMO/photonics spring meeting","upcoming",
   "new entry; placeholder — DPG spring meeting season window is Mar13-Apr7 2028, SAMOP's specific dates/host TBA",
   "https://www.dpg-physik.de/aktivitaeten-und-programme/tagungen/fruehjahrstagungen/2028"),
ev("ecio-2027",
   "European Conference on Integrated Optics — next edition","ECIO 2027","Conference",
   "integrated quantum photonics;photonic integrated circuits;silicon photonics;nanophotonics",
   "TBA","TBA","TBA",
   "TBA","TBA","TBA","TBA",
   "https://www.ecio-conference.org/",5,
   "Largest European integrated optics conference — core relevance; cadence irregular, no 2027 edition confirmed yet (may be 2028)","upcoming",
   "new entry; placeholder, monitor ecio-conference.org",
   "https://www.ecio-conference.org/"),
ev("grc-mech-quant-2028",
   "Gordon Research Conference — Mechanical Systems in the Quantum Regime 2028","GRC MSQR 2028","Conference",
   "optomechanics;quantum computing hardware",
   "TBA","TBA","TBA",
   "TBA","n/a","TBA","n/a",
   "https://www.grc.org/mechanical-systems-in-the-quantum-regime-conference/",4,
   "Optomechanics GRC — relevant to cavity-optomechanical quantum transducers; biennial (even years), next after 2026 Lucca","upcoming",
   "new entry; placeholder, not yet announced",
   "https://www.grc.org/mechanical-systems-in-the-quantum-regime-conference/"),
ev("grc-quantum-science-2028",
   "Gordon Research Conference — Quantum Science 2028","GRC QS 2028","Conference",
   "quantum optics;quantum computing hardware;quantum communication;integrated quantum photonics",
   "TBA","TBA","TBA",
   "TBA","n/a","TBA","n/a",
   "https://www.grc.org/quantum-science-conference/",4,
   "GRC on quantum science covering photonic quantum systems and quantum information; biennial, next after 2026 Easton MA","upcoming",
   "new entry; placeholder, not yet announced",
   "https://www.grc.org/quantum-science-conference/"),
ev("grc-quantum-sensing-2027",
   "Gordon Research Conference — Quantum Sensing 2027","GRC QSense 2027","Conference",
   "quantum optics;quantum computing hardware",
   "TBA","TBA","Les Diablerets, Switzerland",
   "2027-04-04","n/a","2027-06-13","n/a",
   "https://www.grc.org/quantum-sensing-conference/2027/",3,
   "Adjacent: quantum sensing overlaps photonic quantum sensors","upcoming",
   "new entry; exact conference dates not pinned down (likely Jul 2027), application deadline 2027-06-13",
   "https://www.grc.org/quantum-sensing-conference/2027/"),
ev("icqe",
   "International Conference on Quantum Energy","ICQE","Conference",
   "quantum computing hardware",
   "TBA","TBA","TBA",
   "TBA","TBA","TBA","TBA",
   "TBA",2,
   "Quantum energy applications; adjacent to quantum computing hardware","upcoming",
   "confirmed genuine biennial series (2023 Melbourne, 2025 Padua); organizers say a 2027 update is coming 'soon' but no dates yet",
   "https://icqe.com.au/"),
ev("ieee-siphotonics-2027",
   "IEEE Silicon Photonics Conference 2027","IEEE SiPho 2027","Conference",
   "silicon photonics;photonic integrated circuits;III-V on Si",
   "TBA","TBA","TBA",
   "TBA","TBA","TBA","TBA",
   "http://www.ieee-siphotonics.org/",5,
   "Dedicated silicon photonics conference — direct relevance to PICs; next edition after 2026 Ottawa","upcoming",
   "new entry; placeholder — exact 2027 dates/location not yet published (site still shows stale info)",
   "http://www.ieee-siphotonics.org/"),
ev("ipc-2027",
   "IEEE Photonics Conference 2027","IPC 2027","Conference",
   "integrated quantum photonics;photonic integrated circuits;silicon photonics",
   "TBA","TBA","TBA",
   "TBA","TBA","TBA","TBA",
   "https://ieee-ipc.org/",4,
   "IEEE photonics flagship; European edition in Eindhoven — low travel cost","upcoming",
   "downgraded dates/location to TBA: previously listed Nov 10-14 2027 Eindhoven could not be corroborated by any source this run (aggregators show 'Nov 2027, location TBD'); recheck ieee-ipc.org directly",
   "https://ieee-ipc.org/; https://www.jeppix.eu/event/ieee-photonics-conference-ipc/"),
ev("lake-como-uqo-2027",
   "New Frontiers in Ultrafast Quantum Optics — Lake Como School — next edition","UFQP 2027","Summer School",
   "quantum optics;nonlinear optics;single-photon sources",
   "TBA","TBA","Como, Italy",
   "TBA","n/a","TBA","n/a",
   "https://lakecomoschool.org/schools/",4,
   "Summer school on ultrafast quantum optics — photon correlations and time-frequency entanglement","upcoming",
   "new entry; placeholder — 2027 edition not yet announced (2026 ran Jul27-31)",
   "https://lakecomoschool.org/schools/"),
ev("les-houches-eqs-2027",
   "Engineered Quantum Systems — Les Houches Doctoral School 2027","Les Houches EQS","Summer School",
   "quantum optics;quantum computing hardware;integrated quantum photonics",
   "TBA","TBA","Les Houches, France",
   "TBA","n/a","TBA","n/a",
   "https://www.houches-school-physics.com/program/program-2027/program-2027-1733272.kjsp",4,
   "Doctoral school on adaptive measurements and dissipation engineering across qubit platforms","upcoming",
   "new entry; program page exists, exact dates not yet visible",
   "https://www.houches-school-physics.com/program/program-2027/program-2027-1733272.kjsp"),
ev("les-houches-photonics-ai-2027",
   "Photonics & AI — Les Houches Doctoral School 2027","Les Houches Photonics AI","Summer School",
   "photonic integrated circuits;nanophotonics;integrated quantum photonics",
   "TBA","TBA","Les Houches, France",
   "TBA","n/a","TBA","n/a",
   "https://www.houches-school-physics.com/program/program-2027/program-2027-1733272.kjsp",5,
   "Doctoral school on photonic accelerators, neuromorphic photonics and AI-assisted PIC design","upcoming",
   "new entry; program page exists, exact dates not yet visible",
   "https://www.houches-school-physics.com/program/program-2027/program-2027-1733272.kjsp"),
ev("nanolight-2027",
   "Nanolight Conference 2027","Nanolight 2027","Conference",
   "nanophotonics;2D-material photonics;quantum optics;plasmonics",
   "TBA","TBA","Benasque, Spain",
   "TBA","n/a","TBA","n/a",
   "https://benasque.org/",5,
   "European nanophotonics / near-field / 2D-material flagship","upcoming",
   "new entry; placeholder — not yet posted for 2027, monitor benasque.org",
   "https://benasque.org/"),
ev("nrw-nano-2027",
   "NRW NanoConference — next (12th) edition","NRW Nano 2027","Conference",
   "nanophotonics;photonic integrated circuits",
   "TBA","TBA","North Rhine-Westphalia, Germany",
   "TBA","TBA","TBA","TBA",
   "https://www.nanoconference.de/",3,
   "Regional NRW nanotechnology conference; local access; biennial, next after 2025 Dortmund","upcoming",
   "new entry; placeholder, dates not yet announced",
   "https://www.nanoconference.de/"),
ev("opon-next",
   "OPON — next edition (rotating workshop)","OPON","Workshop",
   "integrated quantum photonics;nanophotonics",
   "TBA","TBA","TBA (rotates Münster/Wrocław/Bayreuth/Warsaw)",
   "TBA","TBA","TBA","TBA",
   "https://www.axt.physik.uni-bayreuth.de/en/OPON/index.html",4,
   "International Workshop on Optical Properties of Nanostructures; rotates among Münster/Wrocław/Bayreuth/Warsaw groups — direct access when hosted in Münster","upcoming",
   "new entry; placeholder for edition after OPON2025 (Münster, Apr 2025, now archived)",
   "https://www.axt.physik.uni-bayreuth.de/en/OPON/index.html"),
ev("owtnm",
   "Optical Wave & Waveguide Theory and Modelling Workshop","OWTNM","Workshop",
   "photonic integrated circuits;nanophotonics",
   "TBA","TBA","TBA",
   "TBA","n/a","TBA","n/a",
   "https://www.owtnm.eu/",3,
   "Waveguide modelling workshop relevant to PIC simulation","upcoming",
   "XXXII edition (Apr 2026, EPFL Lausanne) already concluded; XXXIII/next edition not yet announced; series homepage URL updated",
   "https://www.owtnm.eu/"),
ev("photonics-west-2028",
   "SPIE Photonics West 2028","PW 2028","Conference",
   "integrated quantum photonics;silicon photonics;nonlinear optics;single-photon sources",
   "TBA","TBA","San Francisco, CA, USA",
   "TBA","TBA","TBA","TBA",
   "https://spie.org/conferences-and-exhibitions/photonics-west",5,
   "SPIE flagship with Quantum West and Si-photonics tracks","upcoming",
   "new entry; month confirmed (Jan/Feb 2028) but exact dates not yet published",
   "https://spie.org/conferences-and-exhibitions/photonics-west"),
ev("qip-2028",
   "31st Quantum Information Processing Conference","QIP 2028","Conference",
   "quantum communication;quantum computing hardware;quantum networking",
   "TBA","TBA","TBA",
   "TBA","TBA","TBA","TBA",
   "https://qipconference.org/2027/",4,
   "Premier quantum information conference; networking and photonic hardware sessions","upcoming",
   "new entry; placeholder, not yet announced (2027 edition is Feb 2027 Singapore)",
   "https://qipconference.org/2027/"),

]  # end EVENTS


# ── helpers ───────────────────────────────────────────────────────────────────
def parse_date(s):
    """Return date object or None for TBA/n/a."""
    if not s or s in ("TBA", "n/a"):
        return None
    try:
        return date.fromisoformat(s)
    except ValueError:
        return None


def days_from_today(s):
    d = parse_date(s)
    if d is None:
        return None
    return (d - TODAY).days


RED   = PatternFill(fill_type="solid", fgColor="FF4444")
AMBER = PatternFill(fill_type="solid", fgColor="FFAA00")

def deadline_fill(s):
    """Return RED/AMBER fill or None based on days until deadline."""
    n = days_from_today(s)
    if n is None:
        return None
    if 0 <= n <= 14:
        return RED
    if 15 <= n <= 60:
        return AMBER
    return None


# ── write TSV ─────────────────────────────────────────────────────────────────
def write_tsv(events, path):
    with open(path, "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=COLS, delimiter="\t",
                           extrasaction="ignore")
        w.writeheader()
        for e in events:
            w.writerow(e)
    print(f"  TSV  -> {path}  ({len(events)} rows)")


# ── write XLSX ────────────────────────────────────────────────────────────────
HEADER_FILL  = PatternFill(fill_type="solid", fgColor="1F4E79")
HEADER_FONT  = Font(bold=True, color="FFFFFF", size=10)
ARCHIVED_FILL = PatternFill(fill_type="solid", fgColor="E8E8E8")
SCORE_COLORS = {5:"D4EDDA", 4:"D1ECF1", 3:"FFF3CD", 2:"F8D7DA", 1:"F5C6CB"}

def write_xlsx(events, path):
    wb = Workbook()
    ws = wb.active
    ws.title = "Conferences"

    # header
    ws.append(COLS)
    for cell in ws[1]:
        cell.fill   = HEADER_FILL
        cell.font   = HEADER_FONT
        cell.alignment = Alignment(horizontal="center", vertical="center",
                                   wrap_text=True)

    ws.row_dimensions[1].height = 28
    ws.freeze_panes = "A2"
    ws.auto_filter.ref = f"A1:{get_column_letter(len(COLS))}1"

    col_idx = {c: i+1 for i, c in enumerate(COLS)}

    for ev in events:
        row_vals = [ev[c] for c in COLS]
        ws.append(row_vals)
        row_num = ws.max_row

        # light-grey background for archived rows
        is_archived = ev["status"] == "archived"
        if is_archived:
            for cell in ws[row_num]:
                cell.fill = ARCHIVED_FILL

        # relevance score colour on that cell
        score_cell = ws.cell(row=row_num, column=col_idx["relevance_score"])
        sc = ev.get("relevance_score")
        if sc and str(sc).isdigit() and int(sc) in SCORE_COLORS:
            score_cell.fill = PatternFill(fill_type="solid",
                                          fgColor=SCORE_COLORS[int(sc)])

        # deadline columns — conditional colour
        for dcol in DEADLINE_COLS:
            val = ev.get(dcol, "")
            fill = deadline_fill(str(val))
            if fill:
                ws.cell(row=row_num, column=col_idx[dcol]).fill = fill

    # auto-size columns (capped)
    CAP = {
        "id": 28, "name": 55, "acronym": 18, "type": 16, "topic_tags": 55,
        "start_date": 13, "end_date": 13, "location": 28,
        "abstract_deadline": 17, "paper_deadline": 14,
        "registration_deadline": 20, "early_bird_deadline": 18,
        "website": 48, "relevance_score": 9, "relevance_note": 52,
        "status": 14, "last_verified": 14, "last_change": 50, "source_urls": 60,
    }
    for col_name, cap_w in CAP.items():
        ci = col_idx[col_name]
        ws.column_dimensions[get_column_letter(ci)].width = cap_w

    # wrap text in long columns
    for row in ws.iter_rows(min_row=2):
        for cell in row:
            cell.alignment = Alignment(wrap_text=False, vertical="top")

    wb.save(path)
    print(f"  XLSX -> {path}")


# ── main ──────────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    tsv_path  = os.path.join(OUTDIR, f"conferences_{SNAPSHOT}.tsv")
    xlsx_path = os.path.join(OUTDIR, f"conferences_{SNAPSHOT}.xlsx")

    write_tsv(EVENTS, tsv_path)
    write_xlsx(EVENTS, xlsx_path)
    print(f"\nDone. {len(EVENTS)} events written.")

    # summary stats
    from collections import Counter
    stats = Counter(e["status"] for e in EVENTS)
    for s, n in sorted(stats.items()):
        print(f"  {s:15s}: {n}")
