#!/usr/bin/env python3
"""Generate conferences_2026-06-21.tsv and conferences_2026-06-21.xlsx"""

from datetime import date
import os

TODAY = date(2026, 6, 21)
SNAPSHOT = "2026-06-21"

HEADERS = [
    "id","name","acronym","type","topic_tags",
    "start_date","end_date","location",
    "abstract_deadline","paper_deadline","registration_deadline","early_bird_deadline",
    "website","relevance_score","relevance_note",
    "status","last_verified","last_change","source_urls"
]

def r(id,name,acronym,typ,tags,sd,ed,loc,abst,paper,reg,eb,web,score,note,status,lv,lc,src):
    return dict(zip(HEADERS,[id,name,acronym,typ,tags,sd,ed,loc,abst,paper,reg,eb,web,str(score),note,status,lv,lc,src]))

rows = [
# ── ARCHIVED 2025 ──────────────────────────────────────────────────────────
r("benasque-qnp-2025","Quantum Nanophotonics 2025","Benasque QNP","Workshop",
  "nanophotonics;quantum optics;single-photon sources","2025-03-16","2025-03-22","Benasque, Spain",
  "2025-01-17","n/a","TBA","n/a","https://benasque.org/2025quantumnanophotonics/",5,
  "Directly on nanophotonics and single-photon sources","archived","2026-05-13",
  "year roll-over from 2025 edition","https://benasque.org/2025quantumnanophotonics/"),
r("photonics-north-2025","Photonics North 2025","PN 2025","Conference",
  "silicon photonics;integrated quantum photonics;quantum communication","2025-05-20","2025-05-23","Ottawa, Canada",
  "TBA","TBA","TBA","TBA","TBA",3,"Canadian photonics flagship with PIC and quantum sessions",
  "archived","2026-05-13","year roll-over from 2025 edition","original list"),
r("benasque-sqt-2025","Spring School on Superconducting Qubit Technology 2025","Benasque SQT","Summer School",
  "quantum computing hardware;cryogenic electronics","2025-05-21","2025-05-30","Benasque, Spain",
  "TBA","n/a","TBA","n/a","https://benasque.org/2025sqt/",3,
  "Cryogenic electronics for qubit control, adjacent to photonic detector systems",
  "archived","2026-05-13","year roll-over from 2025 edition","https://benasque.org/2025sqt/"),
r("optica-quantum-2025","Optica Quantum 2.0 Conference and Exhibition 2025","Optica Quantum 2025","Conference",
  "integrated quantum photonics;quantum optics;single-photon sources;quantum communication","2025-06-01","2025-06-05","San Francisco, CA, USA",
  "TBA","TBA","TBA","TBA","https://optica.org/events/topical_meetings/quantum/",5,
  "Premier global quantum photonics conference covering PICs, single photons, QKD",
  "archived","2026-05-13","year roll-over from 2025 edition","https://optica.org/events/topical_meetings/quantum/"),
r("icols-2025","26th International Conference on Laser Spectroscopy","ICOLS 2025","Conference",
  "quantum optics;nonlinear optics","2025-06-02","2025-06-07","Elba Island, Italy",
  "2025-01-17","TBA","TBA","TBA","https://icols2025.it/",3,
  "Laser spectroscopy with quantum optics relevance","archived","2026-05-13","year roll-over from 2025 edition","https://icols2025.it/"),
r("ecio-2025","European Conference on Integrated Optics 2025","ECIO 2025","Conference",
  "integrated quantum photonics;photonic integrated circuits;silicon photonics","2025-06-10","2025-06-12","Cardiff, Wales, UK",
  "TBA","TBA","TBA","TBA","https://ecio-conference.org/",5,
  "Largest European dedicated integrated optics conference","archived","2026-05-13","year roll-over from 2025 edition","https://ecio-conference.org/"),
r("benasque-qi-2025","Quantum Information 2025","Benasque QI","Workshop",
  "quantum communication;quantum optics","2025-06-15","2025-07-04","Benasque, Spain",
  "TBA","n/a","TBA","n/a","https://benasque.org/",3,
  "Quantum information including QKD and networking","archived","2026-05-13","year roll-over from 2025 edition","https://benasque.org/"),
r("damop-2025","56th APS Division of Atomic, Molecular and Optical Physics Meeting","DAMOP 2025","Conference",
  "quantum optics;nonlinear optics","2025-06-16","2025-06-20","Portland, OR, USA",
  "2025-01-31","2025-01-31","TBA","TBA","https://aps.org/events/2025/atomic-molecular-optical-physics",3,
  "AMO physics flagship with quantum optics sessions","archived","2026-05-13","year roll-over from 2025 edition","https://aps.org/events/2025/atomic-molecular-optical-physics"),
r("cleo-europe-2025","CLEO/Europe-EQEC 2025","CLEO/Europe 2025","Conference",
  "integrated quantum photonics;quantum optics;nonlinear optics;nanophotonics","2025-06-23","2025-06-27","Munich, Germany",
  "2025-01-27","2025-01-27","TBA","TBA","https://cleoeurope.org/",5,
  "Flagship European photonics and quantum optics conference (biennial)","archived","2026-05-13","year roll-over from 2025 edition","https://cleoeurope.org/"),
r("cewqo-2025","29th Central European Workshop on Quantum Optics","CEWQO 2025","Workshop",
  "quantum optics;single-photon sources;quantum communication","2025-06-23","2025-06-27","Vilnius, Lithuania",
  "TBA","n/a","TBA","n/a","https://ucan.physics.utoronto.ca/conferences/cewqo29/",4,
  "Dedicated European workshop on quantum optics and single-photon physics","archived","2026-05-13","year roll-over from 2025 edition","https://ucan.physics.utoronto.ca/conferences/cewqo29/"),
r("icton-2025","25th International Conference on Transparent Optical Networks","ICTON 2025","Conference",
  "photonic integrated circuits;silicon photonics;quantum communication","2025-07-06","2025-07-10","Barcelona, Spain",
  "TBA","TBA","TBA","TBA","https://icton2025.upc.edu/",3,
  "Transparent optical networks with PIC and quantum photonics tracks","archived","2026-05-13","year roll-over from 2025 edition","https://icton2025.upc.edu/"),
r("ieee-sum-2025","IEEE Summer Topicals Meeting Series 2025","IEEE SUM 2025","Conference",
  "integrated quantum photonics;silicon photonics","2025-07-21","2025-07-23","Berlin, Germany",
  "TBA","TBA","TBA","TBA","https://ieee-sum.org/",3,
  "IEEE topical photonics sessions including PICs","archived","2026-05-13","year roll-over from 2025 edition","https://ieee-sum.org/"),
r("qcrypt-2025","QCrypt 2025","QCrypt 2025","Conference",
  "quantum communication;QKD;quantum networking","2025-08-25","2025-08-29","Sanya, China",
  "TBA","TBA","TBA","TBA","https://qcrypt.net/",4,
  "Premier annual quantum cryptography and QKD conference","archived","2026-05-13","year roll-over from 2025 edition","https://qcrypt.net/"),
r("ecoc-2025","51st European Conference on Optical Communication","ECOC 2025","Conference",
  "photonic integrated circuits;silicon photonics;quantum communication","2025-09-28","2025-10-02","Copenhagen, Denmark",
  "TBA","TBA","TBA","TBA","https://ecoc2025.org/",4,
  "Europe's biggest optical comms conference with PIC and quantum tracks","archived","2026-05-13","year roll-over from 2025 edition","https://ecoc2025.org/"),
r("moc-2025","30th Microoptics Conference","MOC 2025","Conference",
  "photonic integrated circuits;nanophotonics","2025-10-12","2025-10-15","Tochigi, Japan",
  "2025-05-16","TBA","TBA","TBA","TBA",3,
  "Micro- and nano-optics with PIC sessions","archived","2026-05-13","year roll-over from 2025 edition","original list"),
r("fio-2025","Frontiers in Optics + Laser Science 2025","FiO+LS 2025","Conference",
  "quantum optics;nonlinear optics;nanophotonics","2025-10-27","2025-10-30","Denver, CO, USA",
  "TBA","TBA","TBA","TBA","https://frontiersinoptics.com/",3,
  "Broad US optics conference with quantum photonics components","archived","2026-05-13","year roll-over from 2025 edition","https://frontiersinoptics.com/"),
r("piers-fall-2025","Photonics & Electromagnetics Research Symposium — Fall 2025","PIERS Fall 2025","Symposium",
  "photonic integrated circuits;nanophotonics","2025-11-04","2025-11-08","Chiba, Japan",
  "TBA","TBA","TBA","TBA","TBA",2,
  "General EM/photonics symposium; peripherally relevant","archived","2026-05-13","year roll-over from 2025 edition","original list"),
r("acp-2025","Asia Communications and Photonics Conference 2025","ACP 2025","Conference",
  "photonic integrated circuits;quantum communication","2025-11-05","2025-11-08","Jiangsu, China",
  "2025-08-01","TBA","TBA","TBA","TBA",3,
  "Asia-Pacific photonics flagship with quantum sessions","archived","2026-05-13","year roll-over from 2025 edition","original list"),
r("ipc-2025","IEEE Photonics Conference 2025","IPC 2025","Conference",
  "integrated quantum photonics;photonic integrated circuits;silicon photonics","2025-11-09","2025-11-13","Singapore",
  "TBA","TBA","TBA","TBA","https://ieee-ipc.org/",4,
  "IEEE flagship photonics devices and integrated systems conference","archived","2026-05-13","year roll-over from 2025 edition","https://ieee-ipc.org/"),
r("optima-2025","Optical Communication, Photonics, Telecommunications & Intelligent Machine Applications","OPTIMA 2025","Conference",
  "photonic integrated circuits","2025-12-04","2025-12-05","Tashkent, Uzbekistan",
  "TBA","TBA","TBA","TBA","TBA",2,
  "Regional optics/photonics conference; limited quantum scope","archived","2026-05-13","year roll-over from 2025 edition","original list"),
r("pgc-2025","Photonics Global Conference 2025","PGC 2025","Conference",
  "photonic integrated circuits;nanophotonics","2025-12-05","2025-12-08","Sanya, China",
  "TBA","TBA","TBA","TBA","TBA",2,
  "Asia-Pacific photonics conference; some PIC tracks","archived","2026-05-13","year roll-over from 2025 edition","original list"),
r("icisct-2025","International Conference on Information Science and Communications Technologies","ICISCT 2025","Conference",
  "quantum communication","2025-12-26","2025-12-27","Kathmandu, Nepal",
  "TBA","TBA","TBA","TBA","TBA",2,
  "Broad ICT conference; limited photonics scope","archived","2026-05-13","year roll-over from 2025 edition","original list"),

# ── ARCHIVED 2026 (events passed as of 2026-06-21) ─────────────────────────
r("sheffield-qon-winter-2026","4th Quantum Optics and Nanophotonics Winter School","QONWS 2026","Winter School",
  "quantum optics;nanophotonics;single-photon sources;2D-material photonics","2026-01-27","2026-01-28","Sheffield, UK",
  "2025-12-19","n/a","2026-01-27","2025-12-08",
  "https://sites.google.com/sheffield.ac.uk/quantumopticsnanophotonics2026/home",5,
  "Intensive school on quantum light generation, nanophotonic materials and spin-photon interfaces — ideal for PhDs",
  "archived","2026-06-21","new entry; event passed Jan 27-28",
  "https://sites.google.com/sheffield.ac.uk/quantumopticsnanophotonics2026/home;https://www.idquantique.com/nanophotonics-sheffield/"),
r("photonics-west-2026","SPIE Photonics West 2026","PW 2026","Conference",
  "integrated quantum photonics;silicon photonics;nonlinear optics;single-photon sources","2026-01-17","2026-01-22","San Francisco, CA, USA",
  "2025-07-09","TBA","TBA","TBA","https://spie.org/photonics-west",5,
  "SPIE flagship with Quantum West and Si-photonics tracks","archived","2026-05-13",
  "year roll-over; Photonics West 2027 now announced (Jan 30–Feb 4)","https://spie.org/photonics-west"),
r("qip-2026","29th Quantum Information Processing Conference","QIP 2026","Conference",
  "quantum communication;quantum computing hardware;quantum networking","2026-01-26","2026-01-30","Riga, Latvia",
  "2025-09-12","2025-10-10","TBA","TBA","https://qip2026.lu.lv/",4,
  "Premier quantum information conference; networking and photonic hardware sessions",
  "archived","2026-05-13","year roll-over; QIP 2027 Singapore announced","https://qip2026.lu.lv/"),
r("dpg-samop-2026","DPG Frühjahrstagung SAMOP 2026","DPG SAMOP 2026","Conference",
  "quantum optics;nanophotonics;integrated quantum photonics","2026-03-01","2026-03-06","Mainz, Germany",
  "TBA","TBA","TBA","TBA","https://mainz26.dpg-tagungen.de",4,
  "German physics society AMO/photonics spring meeting — easily accessible from Münster",
  "archived","2026-05-13","year roll-over; DPG SAMOP 2027 Hannover announced","https://mainz26.dpg-tagungen.de"),
r("nanolight-2026","Nanolight Conference 2026","Nanolight 2026","Conference",
  "nanophotonics;2D-material photonics;quantum optics;plasmonics","2026-03-02","2026-03-06","Benasque, Spain",
  "2025-12-15","n/a","2026-02-15","n/a","https://benasque.org/2026nanolight/",5,
  "European nanophotonics / near-field / 2D-material flagship","archived","2026-05-13","year roll-over","https://benasque.org/2026nanolight/"),
r("dpg-skm-2026","DPG Frühjahrstagung SKM 2026","DPG SKM 2026","Conference",
  "silicon photonics;nanophotonics;2D-material photonics","2026-03-08","2026-03-13","Dresden, Germany",
  "TBA","TBA","TBA","TBA","https://dresden26.dpg-tagungen.de",3,
  "Condensed matter sessions on photonics materials and devices","archived","2026-05-13","year roll-over","https://dresden26.dpg-tagungen.de"),
r("ofc-2026","Optical Fiber Communication Conference 2026","OFC 2026","Conference",
  "photonic integrated circuits;silicon photonics;quantum communication","2026-03-15","2026-03-19","Los Angeles, CA, USA",
  "TBA","TBA","TBA","TBA","https://ofcconference.org/",4,
  "World's largest optical comms conference with PIC and quantum networking sessions",
  "archived","2026-05-13","year roll-over; OFC 2027 Los Angeles Mar 7-11 announced","https://ofcconference.org/"),
r("aps-march-2026","APS Global Physics Summit 2026","APS 2026","Conference",
  "quantum optics;quantum computing hardware;integrated quantum photonics","2026-03-16","2026-03-20","Denver, CO, USA",
  "2025-10-31","2025-10-31","TBA","TBA","https://summit.aps.org/",4,
  "Largest physics meeting; major quantum photonics and computing sessions",
  "archived","2026-05-13","year roll-over; APS 2027 Atlanta Apr 11-16","https://summit.aps.org/"),
r("spie-pe-2026","SPIE Photonics Europe 2026","SPIE PE 2026","Conference",
  "integrated quantum photonics;silicon photonics;nanophotonics","2026-04-12","2026-04-16","Strasbourg, France",
  "TBA","TBA","TBA","TBA","https://spie.org/photonics-europe",5,
  "Major European SPIE photonics conference with quantum integrated sessions","archived","2026-05-13","year roll-over","https://spie.org/photonics-europe"),
r("ieee-siphotonics-2026","IEEE Silicon Photonics Conference 2026","IEEE SiPho 2026","Conference",
  "silicon photonics;photonic integrated circuits;III-V on Si","2026-04-13","2026-04-15","Ottawa, ON, Canada",
  "2025-10-03","TBA","TBA","TBA","https://ieee-siphotonics.org/",5,
  "Dedicated silicon photonics conference — direct relevance to PICs","archived","2026-05-13","year roll-over","https://ieee-siphotonics.org/"),
r("ieee-qpain-2026","IEEE 2nd International Conference on Quantum Photonics, AI & Networking","IEEE QPAIN 2026","Conference",
  "integrated quantum photonics;quantum networking","2026-04-16","2026-04-18","Chattogram, Bangladesh",
  "TBA","TBA","TBA","TBA","https://qpain.org/",3,
  "Quantum photonics and networking conference (IEEE-sponsored)","archived","2026-05-13","year roll-over","https://qpain.org/"),
r("inp-webinar-2026","Webinar on InP platform for NIR and MIR applications","InP Webinar","Seminar",
  "photonic integrated circuits;III-V on Si","2026-04-17","2026-04-17","Online",
  "TBA","n/a","TBA","n/a","https://inphomir.eu/1st-webinar/",4,
  "III-V InP PIC platform — directly relevant to quantum light-source integration","archived","2026-05-13","year roll-over","https://inphomir.eu/1st-webinar/"),
r("eftf-2026","European Frequency and Time Forum 2026","EFTF 2026","Conference",
  "quantum optics;quantum communication","2026-04-20","2026-04-23","Noordwijk, The Netherlands",
  "TBA","TBA","TBA","TBA","https://www.eftf.org/home",2,
  "Frequency/time standards; quantum photonic metrology peripherally relevant","archived","2026-05-13","year roll-over","https://www.eftf.org/home"),
r("spie-ds-2026","SPIE Defense + Security 2026","SPIE D+S 2026","Conference",
  "single-photon sources;quantum communication","2026-04-26","2026-04-30","National Harbor, MD, USA",
  "TBA","TBA","TBA","TBA","https://spie.org/defense-and-commercial-sensing",2,
  "Defense photonics with some single-photon sensing sessions","archived","2026-05-13","year roll-over","https://spie.org/defense-and-commercial-sensing"),
r("bqit-2026","Bristol Quantum Information Technologies Workshop 2026","BQIT 2026","Workshop",
  "integrated quantum photonics;quantum communication;quantum computing hardware","2026-04-27","2026-04-29","Bristol, UK",
  "TBA","n/a","TBA","n/a","https://www.bristol.ac.uk/qet-labs/events/bqit-workshop/",5,
  "UK quantum photonics workshop — PICs, single photons, quantum networking","archived","2026-05-13","year roll-over","https://www.bristol.ac.uk/qet-labs/events/bqit-workshop/"),
r("quantumatter-2026","QUANTUMatter 2026","QUANTU 2026","Conference",
  "quantum computing hardware;quantum optics;nanophotonics","2026-04-27","2026-04-30","Barcelona, Spain",
  "2026-02-11","n/a","2026-03-06","2026-02-23","https://www.quantumconf.eu/2026/",3,
  "Quantum materials and devices, including photonic quantum systems","archived","2026-05-13","year roll-over","https://www.quantumconf.eu/2026/"),
r("ampd-2026","Annual Meeting Photonic Devices 2026","AMPD 2026","Conference",
  "photonic integrated circuits;nanophotonics","2026-04-28","2026-04-30","TBA",
  "TBA","TBA","TBA","TBA","https://www.zib.de/workshop-photonic-devices/",4,
  "German photonic devices annual meeting — directly relevant to group's fabrication work","archived","2026-05-13","year roll-over","https://www.zib.de/workshop-photonic-devices/"),
r("talent-photonics-summer-2026","3rd Photonics TALENT International Summer School","TALENT Photonics 2026","Summer School",
  "integrated quantum photonics;nonlinear optics;photonic integrated circuits","2026-06-15","2026-06-19","Bordeaux, France",
  "TBA","n/a","TBA","n/a","https://talentphotonic3.sciencesconf.org/",3,
  "European photonics school for Master/PhD students covering extreme-light and quantum applications",
  "archived","2026-06-21","new entry; event passed Jun 15-19",
  "https://talentphotonic3.sciencesconf.org/;https://www.alphanov.com/en/agenda/photonics-talent-summer-school-2026"),
r("cleo-2026","Conference on Lasers and Electro-Optics 2026","CLEO 2026","Conference",
  "integrated quantum photonics;quantum optics;nonlinear optics;silicon photonics;single-photon sources","2026-05-17","2026-05-21","Charlotte, NC, USA",
  "2025-11-18","n/a","TBA","TBA","https://cleoconference.org/",5,
  "Premier US laser/photonics conference; major IQP, Si-PIC and quantum optics sessions",
  "archived","2026-06-21","event passed May 17-21","https://cleoconference.org/"),
r("damop-2026","57th APS Division of Atomic, Molecular and Optical Physics Meeting","DAMOP 2026","Conference",
  "quantum optics;nonlinear optics;single-photon sources","2026-06-01","2026-06-05","Providence, RI, USA",
  "TBA","TBA","TBA","TBA","https://aps.org/events/2026/damop-meeting-2026",3,
  "AMO physics flagship with quantum optics and single-photon sessions",
  "archived","2026-06-21","event passed Jun 1-5","https://aps.org/events/2026/damop-meeting-2026"),
r("photonics-north-2026","Photonics North 2026","PN 2026","Conference",
  "silicon photonics;integrated quantum photonics;quantum communication","2026-06-01","2026-06-04","TBA",
  "TBA","TBA","TBA","TBA","TBA",3,
  "Canadian national photonics conference with PIC and quantum sessions",
  "archived","2026-06-21","event passed Jun 1-4","original list"),
r("cargese-qt-2026","Summer School on Quantum Technologies for Computation and Communication","QT4CC 2026","Summer School",
  "quantum communication;quantum computing hardware;quantum networking","2026-06-08","2026-06-20","Cargèse (Corsica), France",
  "TBA","n/a","TBA","n/a","https://qt4cc.sciencesconf.org/",4,
  "PhD summer school on quantum computation and communication — ideal for group's PhD students",
  "archived","2026-06-21","event passed Jun 8-20","https://qt4cc.sciencesconf.org/"),
r("spie-pfq-2026","SPIE Photonics for Quantum 2026","PfQ 2026","Conference",
  "integrated quantum photonics;single-photon sources;quantum communication;quantum computing hardware","2026-06-08","2026-06-11","Waterloo, ON, Canada",
  "2026-03-01","n/a","TBA","TBA","https://spie.org/conferences-and-exhibitions/photonics-for-quantum",5,
  "Dedicated quantum photonics conference — bullseye for AG Schuck",
  "archived","2026-06-21","event passed Jun 8-11","https://spie.org/PFQ26/conferencedetails/photonics-for-quantum"),
r("islc-2026","30th International Semiconductor Laser Conference","ISLC 2026","Conference",
  "single-photon sources;III-V on Si;photonic integrated circuits","2026-06-14","2026-06-17","Tampere, Finland",
  "2026-02-05","TBA","TBA","TBA","https://events.tuni.fi/islc2026/",4,
  "III-V semiconductor laser conference — key for quantum light source development",
  "archived","2026-06-21","event passed Jun 14-17","https://events.tuni.fi/islc2026/"),
r("grc-quantum-science-2026","Gordon Research Conference — Quantum Science 2026","GRC QS 2026","Conference",
  "quantum optics;quantum computing hardware;quantum communication;integrated quantum photonics","2026-06-14","2026-06-19","Easton, MA, USA",
  "TBA","n/a","TBA","n/a","https://www.grc.org/quantum-science-conference/2026/",4,
  "GRC on quantum science covering photonic quantum systems and quantum information",
  "archived","2026-06-21","event passed Jun 14-19","https://www.grc.org/quantum-science-conference/2026/"),
r("icap-2026","29th International Conference on Atomic Physics","ICAP 2026","Conference",
  "quantum optics;nonlinear optics","2026-06-14","2026-06-19","Wuhan, China",
  "TBA","TBA","TBA","TBA","https://www.icap29.com/home.html",3,
  "Atomic physics conference with quantum optics and light-matter interaction sessions",
  "archived","2026-06-21","event passed Jun 14-19","https://www.icap29.com/home.html"),
r("ecio-2026","European Conference on Integrated Optics 2026","ECIO 2026","Conference",
  "integrated quantum photonics;photonic integrated circuits;silicon photonics;nanophotonics","2026-06-15","2026-06-17","Zürich, Switzerland",
  "TBA","TBA","2026-06-01","2026-05-11","https://ecio-conference.org/",5,
  "Largest European integrated optics conference — core relevance for AG Schuck",
  "archived","2026-06-21","event passed Jun 15-17","https://www.ecio-conference.org/"),
r("optica-quantum-2026","Optica Quantum 2.0 Conference and Exhibition 2026","Optica Quantum 2026","Conference",
  "integrated quantum photonics;quantum optics;single-photon sources;quantum communication;quantum computing hardware","2026-06-15","2026-06-18","Glasgow, UK",
  "2026-02-10","n/a","2026-05-29","n/a","https://www.optica.org/events/topical_meetings/quantum/",5,
  "Premier quantum photonics conference spanning PICs, detectors, QKD, and hardware",
  "archived","2026-06-21","event passed Jun 15-18 (ended today)","https://www.optica.org/events/topical_meetings/quantum/"),
r("icop-2026","Italian Conference on Optics and Photonics 2026","ICOP 2026","Conference",
  "integrated quantum photonics;quantum optics;nanophotonics","2026-06-15","2026-06-17","L'Aquila, Italy",
  "TBA","TBA","TBA","TBA","https://www.icop2026.it/",3,
  "Italian national photonics conference with quantum tracks","archived","2026-06-21","event passed Jun 15-17","https://www.icop2026.it/"),
r("ccw-london-2026","Critical Communications World London 2026","CCW 2026","Conference",
  "quantum communication;quantum networking","2026-06-16","2026-06-18","London, UK",
  "TBA","TBA","TBA","TBA","https://www.critical-communications-world.com/",2,
  "Critical comms industry event; QKD sessions of marginal relevance",
  "archived","2026-06-21","event passed Jun 16-18","https://www.critical-communications-world.com/"),

# ── ONGOING (started today 2026-06-21) ─────────────────────────────────────
r("egas-2026","57th Conference of the European Group on Atomic Systems","EGAS 2026","Conference",
  "quantum optics;nonlinear optics","2026-06-21","2026-06-25","Toruń, Poland",
  "TBA","TBA","TBA","TBA","https://egas57.org/",3,
  "European atomic systems conference with quantum optics and light-matter sessions",
  "ongoing","2026-06-21","now ongoing — started today Jun 21","https://egas57.org/"),
r("benasque-qsi-2026","Quantum Science: Implementations 2026","Benasque QSI","Workshop",
  "integrated quantum photonics;quantum computing hardware;quantum communication","2026-06-21","2026-07-04","Benasque, Spain",
  "TBA","n/a","TBA","n/a","https://benasque.org/",4,
  "Benasque workshop on quantum implementations including photonic platforms",
  "ongoing","2026-06-21","now ongoing — started today Jun 21","https://benasque.org/"),

# ── UPCOMING ───────────────────────────────────────────────────────────────
r("les-houches-pa-2026","Photons & Atoms 2026 — Les Houches Doctoral School","Les Houches PA 2026","Summer School",
  "quantum optics;nonlinear optics;integrated quantum photonics;single-photon sources","2026-06-22","2026-07-03","Les Houches, France",
  "TBA","n/a","TBA","n/a","https://photon-atoms-26.leshouches.science/",5,
  "Leading European doctoral school on photons, quantum gases and quantum technologies",
  "upcoming","2026-06-21","no change; starts tomorrow Jun 22","https://photon-atoms-26.leshouches.science/"),
r("iqt-nordics-2026","IQT Nordics 2026 — Quantum Technology in a Changing World","IQT Nordics 2026","Conference",
  "quantum communication;quantum computing hardware;integrated quantum photonics","2026-06-22","2026-06-24","Oslo, Norway",
  "TBA","n/a","TBA","TBA","https://iqtevent.com/nordics/",3,
  "Nordic quantum industry conference with hardware and QKD sessions",
  "upcoming","2026-06-21","no change; starts tomorrow","https://iqtevent.com/nordics/"),
r("quantum-tech-world-2026","Quantum.Tech World 2026","Q.Tech World 2026","Conference",
  "quantum computing hardware;quantum communication;integrated quantum photonics","2026-06-25","2026-06-26","Boston, MA, USA",
  "TBA","n/a","TBA","TBA","https://www.alphaevents.com/events-quantumtechus",2,
  "Industry quantum technology event; limited deep-science content",
  "upcoming","2026-05-13","no change","https://www.alphaevents.com/events-quantumtechus"),
r("oecc-2026","31st OptoElectronics and Communications Conference","OECC 2026","Conference",
  "photonic integrated circuits;silicon photonics;quantum communication","2026-06-28","2026-07-02","Busan, South Korea",
  "TBA","TBA","TBA","TBA","TBA",3,
  "Asia-Pacific optoelectronics and comms conference with PIC sessions",
  "upcoming","2026-05-13","no change","original list"),
r("la-ricotta-2026","La Ricotta Summer School: The Quantum in the Haystack","La Ricotta 2026","Summer School",
  "quantum computing hardware;quantum communication","2026-06-29","2026-07-10","As Barreiras, Spain",
  "TBA","n/a","TBA","n/a","https://indico.global/event/16456/",2,
  "Theory-focused quantum information school in informal setting; limited photonics scope",
  "upcoming","2026-06-21","new entry; informal school Jun 29–Jul 10 for grad students and early postdocs","https://indico.global/event/16456/"),
r("quantum-korea-2026","Quantum Korea 2026","Quantum Korea 2026","Conference",
  "quantum computing hardware;quantum communication;integrated quantum photonics","2026-07-02","2026-07-04","Seoul, South Korea",
  "TBA","n/a","TBA","TBA","https://quantum-korea.kr/en/main",2,
  "Government-organised Korean quantum technology showcase",
  "upcoming","2026-05-13","no change","https://quantum-korea.kr/en/main"),
r("eq-tech-summer-amsterdam-2026","European Quantum Technology Summer School 2026","EQTSS 2026","Summer School",
  "quantum communication;quantum computing hardware;integrated quantum photonics","2026-07-04","2026-07-11","Amsterdam, Netherlands",
  "TBA","n/a","TBA","n/a","https://www.amsterdamuas.com/events/2026/3/european-quantum-technology-summer-school",4,
  "Free residential school (75 places) covering quantum computing, comms and sensing — cost-free for PhD students",
  "upcoming","2026-06-21","new entry; free residential school Jul 4-11 Amsterdam; MSc/early PhD level",
  "https://www.amsterdamuas.com/events/2026/3/european-quantum-technology-summer-school"),
r("spw-2026","12th Single Photon Workshop","SPW 2026","Workshop",
  "single-photon sources;SNSPDs;quantum optics;quantum communication","2026-07-06","2026-07-10","Naples, Italy",
  "2026-03-25","n/a","TBA","n/a","https://spw2026.org/",5,
  "THE dedicated single-photon workshop — central to AG Schuck detector and source work",
  "cfp_closed","2026-06-21","abstract deadline was Mar 25 (closed); registration open; programme confirmed Jul 6-10 Naples",
  "https://spw2026.org/;https://iqnhub.org/2026-single-photon-workshop-registration-open/"),
r("icton-2026","26th International Conference on Transparent Optical Networks","ICTON 2026","Conference",
  "photonic integrated circuits;silicon photonics;quantum communication","2026-07-12","2026-07-16","Prague, Czech Republic",
  "TBA","TBA","TBA","TBA","https://www.gov.pl/web/instytut-lacznosci/icton-2026",3,
  "Transparent optical networks with PIC and quantum photonics tracks",
  "upcoming","2026-05-13","no change","https://www.gov.pl/web/instytut-lacznosci/icton-2026"),
r("ieee-sum-2026","IEEE Summer Topicals Meeting Series 2026","IEEE SUM 2026","Conference",
  "photonic integrated circuits;silicon photonics;integrated quantum photonics","2026-07-13","2026-07-15","Tulum, Mexico",
  "TBA","TBA","TBA","TBA","https://ieee-sum.org/",3,
  "IEEE focused topical photonics sessions","upcoming","2026-05-13","no change","https://ieee-sum.org/"),
r("grc-plasmonics-nano-2026","Gordon Research Conference — Plasmonics and Nanophotonics 2026","GRC PNP 2026","Conference",
  "nanophotonics;plasmonics;quantum optics;2D-material photonics","2026-07-19","2026-07-24","Newry, ME, USA",
  "TBA","n/a","2026-06-21","n/a","https://www.grc.org/plasmonics-and-nanophotonics-conference/2026/",5,
  "GRC on quantum nanophotonics, plasmonics and 2D photonics — highly relevant to AG Schuck",
  "upcoming","2026-06-21","APPLICATION DEADLINE IS TODAY (2026-06-21) — apply immediately at GRC website",
  "https://www.grc.org/plasmonics-and-nanophotonics-conference/2026/"),
r("cewqo-2026","30th Central European Workshop on Quantum Optics","CEWQO30 2026","Workshop",
  "quantum optics;single-photon sources;nonlinear optics;integrated quantum photonics","2026-07-20","2026-07-24","Erlangen, Germany",
  "TBA","n/a","TBA","n/a",
  "https://www.lightmatter.fau.de/2026/04/cewqo30-the-30th-central-european-workshop-on-quantum-optics-2026/",5,
  "European quantum optics workshop co-hosted by FAU/MPL Erlangen — close to Münster",
  "upcoming","2026-06-21","no change; hosted by Chekhova/Marquardt groups Jul 20-24",
  "https://www.lightmatter.fau.de/2026/04/cewqo30-the-30th-central-european-workshop-on-quantum-optics-2026/"),
r("apc-2026","Optica Advanced Photonics Congress 2026","APC 2026","Conference",
  "integrated quantum photonics;nonlinear optics;nanophotonics","2026-07-26","2026-07-30","Long Beach, CA, USA",
  "2026-07-07","TBA","TBA","TBA","https://www.optica.org/events/congress/advanced_photonics_congress/",4,
  "Optica congress including nonlinear photonics, waveguides and integrated circuits",
  "cfp_open","2026-06-21","location confirmed Long Beach CA; abstract deadline Jul 7 (2 weeks away)",
  "https://www.optica.org/events/congress/advanced_photonics_congress/;https://10times.com/e1h1-7p53-zkfd-k"),
r("grc-mech-quant-2026","Gordon Research Conference — Mechanical Systems in the Quantum Regime 2026","GRC MSQR 2026","Conference",
  "optomechanics;quantum computing hardware","2026-07-26","2026-07-31","Lucca (Barga), Italy",
  "TBA","n/a","TBA","n/a","https://www.grc.org/mechanical-systems-in-the-quantum-regime-conference/2026/",4,
  "Optomechanics GRC — relevant to cavity-optomechanical quantum transducers",
  "upcoming","2026-05-13","no change","https://www.grc.org/mechanical-systems-in-the-quantum-regime-conference/2026/"),
r("lake-como-ufqp-2026","New Frontiers in Ultrafast Quantum Optics — Lake Como School","UFQP 2026","Summer School",
  "quantum optics;nonlinear optics;single-photon sources","2026-07-27","2026-07-31","Como, Italy",
  "2026-05-31","n/a","TBA","n/a","https://ufqp.lakecomoschool.org/",4,
  "Summer school on ultrafast quantum optics — photon correlations and time-frequency entanglement",
  "cfp_closed","2026-06-21","application deadline May 31 closed; school Jul 27-31 (40 participants max)",
  "https://ufqp.lakecomoschool.org/"),
r("ieee-rapid-2026","IEEE Research and Applications of Photonics in Defense 2026","IEEE RAPID 2026","Conference",
  "single-photon sources;quantum communication","2026-08-05","2026-08-07","Miramar Beach, FL, USA",
  "TBA","TBA","TBA","TBA","https://ieee-rapid.org/",2,
  "Defense photonics; some single-photon sensing sessions","upcoming","2026-05-13","no change","https://ieee-rapid.org/"),
r("qkd-summer-school-2026","Quantum Key Distribution Summer School 2026","QKD School 2026","Summer School",
  "quantum communication;QKD;quantum networking","2026-08-16","2026-08-21","Les Diablerets, Switzerland",
  "n/a","n/a","2026-04-15","n/a","https://indico.global/event/9672/",4,
  "PhD-level school on theoretical and experimental QKD — ideal for quantum comms PhDs",
  "cfp_closed","2026-06-21",
  "new entry; registration deadline was Apr 15 (closed); CHF 450/students; speakers incl. Renner, Lütkenhaus, Diamanti",
  "https://indico.global/event/9672/;https://www.quantiki.org/conference/quantum-key-distribution-summer-school-2026"),
r("spie-op-2026","SPIE Optics + Photonics 2026","SPIE O+P 2026","Conference",
  "integrated quantum photonics;nanophotonics;quantum optics;single-photon sources","2026-08-23","2026-08-27","San Diego, CA, USA",
  "TBA","TBA","TBA","TBA","https://spie.org/optics-and-photonics",4,
  "SPIE major annual meeting with quantum nanophotonics and quantum technologies tracks",
  "upcoming","2026-05-13","no change","https://spie.org/optics-and-photonics"),
r("qcrypt-2026","QCrypt 2026","QCrypt 2026","Conference",
  "quantum communication;QKD;quantum networking","2026-08-24","2026-08-28","Ottawa, Canada",
  "2026-03-13","n/a","TBA","n/a","https://qcrypt.net/2026/",4,
  "Premier annual QKD and quantum cryptography conference",
  "cfp_closed","2026-06-21","talk deadline Mar 13; poster deadline May 1; both closed; registration now open",
  "https://qcrypt.net/2026/;https://qcrypt.net/2026/attend/registration/"),
r("eosam-2026","European Optical Society Annual Meeting 2026","EOSAM 2026","Conference",
  "integrated quantum photonics;nanophotonics;nonlinear optics","2026-08-24","2026-08-28","Tampere, Finland",
  "2026-04-14","TBA","TBA","TBA","https://www.europeanoptics.org/events/eos/eosam2026.html",4,
  "EOS flagship European photonics meeting with strong quantum photonics programme",
  "cfp_closed","2026-06-21","abstract deadline was Apr 14 (closed); Nobel laureate Anne L'Huillier keynote confirmed",
  "https://www.europeanoptics.org/events/eos/eosam2026.html"),
r("tqc-2026","Theory of Quantum Computation, Communication and Cryptography 2026","TQC 2026","Conference",
  "quantum communication;quantum computing hardware;quantum networking","2026-08-31","2026-09-04","Sherbrooke, QC, Canada",
  "TBA","TBA","TBA","TBA","https://tqc-conference.org/2026/",3,
  "Theory conference for quantum communication, computation and cryptography","upcoming","2026-05-13","no change","https://tqc-conference.org/2026/"),
r("asc-2026","Applied Superconductivity Conference 2026","ASC 2026","Conference",
  "SNSPDs;cryogenic electronics;single-photon sources","2026-09-06","2026-09-11","Pittsburgh, PA, USA",
  "2026-02-02","TBA","TBA","n/a","https://appliedsuperconductivity.org/asc2026/",4,
  "Premier superconductivity conference with major SNSPD and cryogenic electronics sessions",
  "cfp_closed","2026-06-21","abstract deadline was Feb 2 (extended, closed); abstract edits accepted until Aug 3; registration open",
  "https://www.appliedsuperconductivity.org/asc2026/;https://www.appliedsuperconductivity.org/asc2026/important-dates/"),
r("inphomir-school-2026","INPHOMIR Photonics School 2026","INPHOMIR School","Summer School",
  "photonic integrated circuits;III-V on Si","2026-09-07","2026-09-11","Bari, Italy",
  "TBA","n/a","TBA","n/a","https://inphomir.eu/inphomir-school-program/",4,
  "Dedicated InP/III-V photonics school for NIR/MIR applications","upcoming","2026-05-13","no change","https://inphomir.eu/inphomir-school-program/"),
r("ieee-qce26","IEEE Quantum Week 2026","QCE26","Conference",
  "quantum computing hardware;quantum communication;integrated quantum photonics","2026-09-13","2026-09-18","Toronto, ON, Canada",
  "2026-06-22","2026-06-29","TBA","TBA","https://qce.quantum.ieee.org/2026/",3,
  "IEEE quantum week with photonic quantum computing and QKD sessions",
  "cfp_open","2026-06-21","workshop paper abstract due TOMORROW (Jun 22), full paper Jun 29 — URGENT; registration open",
  "https://qce.quantum.ieee.org/2026/;https://qce.quantum.ieee.org/2026/submission-deadlines/"),
r("ecoc-2026","European Conference on Optical Communication 2026","ECOC 2026","Conference",
  "photonic integrated circuits;silicon photonics;quantum communication;integrated quantum photonics","2026-09-20","2026-09-24","Málaga, Spain",
  "2026-04-22","2026-04-22","TBA","n/a","https://ecoc2026.org/",4,
  "Europe's flagship optical comms conference with quantum technologies track",
  "cfp_closed","2026-06-21","paper deadline closed Apr 22; demo paper deadline May 31 (closed); registration open",
  "https://ecoc2026.org/;https://ecoc2026.org/ECOC2026/paper-submission"),
r("mne-2026","International Conference on Micro and Nano Engineering 2026","MNE 2026","Conference",
  "photonic integrated circuits;nanophotonics;2D-material photonics","2026-09-21","2026-09-24","Interlaken, Switzerland",
  "TBA","TBA","TBA","TBA","https://mne2026.imnes.org/",3,
  "Nanofabrication conference relevant to photonic device processing","upcoming","2026-05-13","no change","https://mne2026.imnes.org/"),
r("fio-2026","Frontiers in Optics + Laser Science 2026","FiO+LS 2026","Conference",
  "quantum optics;nonlinear optics;nanophotonics","2026-09-27","2026-10-01","Rochester, NY, USA",
  "2026-07-07","TBA","TBA","TBA","https://frontiersinoptics.com/",3,
  "Broad US photonics conference with quantum optics tracks",
  "cfp_open","2026-06-21","abstract deadline confirmed Jul 7 (16 days away); venue Joseph A. Floreano Rochester Riverside Convention Center",
  "https://frontiersinoptics.com/;https://www.frontiersinoptics.com/submissions/author-timeline"),
r("hdqs-2026","High-Dimensional Quantum Systems Workshop 2026","HDQS 2026","Workshop",
  "quantum optics;quantum communication;integrated quantum photonics","2026-10-04","2026-10-09","Benasque, Spain",
  "TBA","n/a","TBA","n/a","https://benasque.org/2026hdqs/",4,
  "Benasque workshop on high-dimensional quantum photonics and quantum information",
  "upcoming","2026-05-13","no change","https://benasque.org/2026hdqs/"),
r("photonics-days-2026","Photonics Days Berlin 2026","PDB 2026","Conference",
  "integrated quantum photonics;photonic integrated circuits;nanophotonics","2026-10-07","2026-10-08","Berlin, Germany",
  "TBA","TBA","TBA","TBA","https://photonic-days-berlin.com/",3,
  "German photonics industry and research meeting","upcoming","2026-05-13","no change","https://photonic-days-berlin.com/"),
r("ipc-2026","IEEE Photonics Conference 2026","IPC 2026","Conference",
  "integrated quantum photonics;photonic integrated circuits;silicon photonics","2026-11-08","2026-11-12","Denver, CO, USA",
  "2026-09-30","TBA","TBA","TBA","https://ieee-ipc.org/",4,
  "IEEE flagship photonics devices and integrated systems conference",
  "upcoming","2026-06-21","abstract deadline ~Sep 30 per submission portal (ipc2026.exordo.com)",
  "https://ieee-ipc.org/;https://ipc2026.exordo.com/"),
r("eqtc-2026","European Quantum Technologies Conference 2026","EQTC 2026","Conference",
  "integrated quantum photonics;quantum communication;quantum computing hardware;quantum networking","2026-11-29","2026-12-03","Dublin, Ireland",
  "TBA","TBA","TBA","TBA","https://www.eqtc2026.eu/",5,
  "EU Quantum Flagship conference — all aspects of quantum technology, high visibility",
  "upcoming","2026-06-21","confirmed Nov 29–Dec 3 Dublin; registration interest now open",
  "https://qt.eu/events/eqtc-2026-european-quantum-technologies-conference;https://www.eqtc2026.eu/"),

# ── 2027 ENTRIES ────────────────────────────────────────────────────────────
r("photonics-west-2027","SPIE Photonics West 2027","PW 2027","Conference",
  "integrated quantum photonics;silicon photonics;nonlinear optics;single-photon sources","2027-01-30","2027-02-04","San Francisco, CA, USA",
  "2026-07-22","TBA","TBA","TBA","https://spie.org/conferences-and-exhibitions/photonics-west",5,
  "SPIE flagship with Quantum West and Si-photonics tracks — abstract deadline Jul 22 2026",
  "upcoming","2026-06-21","abstract deadline Jul 22 2026 confirmed (~31 days away)",
  "https://spie.org/conferences-and-exhibitions/photonics-west;https://spie.org/conferences-and-exhibitions/photonics-west/program/browse-program"),
r("qip-2027","30th Quantum Information Processing Conference","QIP 2027","Conference",
  "quantum communication;quantum computing hardware;quantum networking","2027-02-20","2027-02-26","Singapore",
  "TBA","TBA","TBA","TBA","https://qipconference.org/2027/",4,
  "Premier annual quantum information conference; quantum networking and hardware sessions",
  "upcoming","2026-05-13","no change","https://qipconference.org/2027/"),
r("dpg-samop-2027","DPG Frühjahrstagung SAMOP 2027","DPG SAMOP 2027","Conference",
  "quantum optics;nanophotonics;integrated quantum photonics","2027-02-28","2027-03-05","Hannover, Germany",
  "TBA","TBA","TBA","TBA","https://dpg-physik.de/",4,
  "DPG spring meeting for quantum optics and photonics — easily accessible from Münster",
  "upcoming","2026-05-13","no change","https://dpg-physik.de/"),
r("ofc-2027","Optical Fiber Communication Conference 2027","OFC 2027","Conference",
  "photonic integrated circuits;silicon photonics;quantum communication","2027-03-07","2027-03-11","Los Angeles, CA, USA",
  "TBA","TBA","TBA","TBA","https://ofcconference.org/",4,
  "World's largest optical comms conference with PIC and quantum networking sessions",
  "upcoming","2026-05-13","no change","https://ofcconference.org/"),
r("spie-oo-2027","SPIE Optics + Optoelectronics 2027","SPIE O+O 2027","Conference",
  "integrated quantum photonics;quantum optics;nanophotonics","2027-04-05","2027-04-08","Prague, Czech Republic",
  "TBA","TBA","TBA","TBA","TBA",4,
  "SPIE European conference with quantum photonics and nanophotonics tracks","upcoming","2026-05-13","no change","original list"),
r("aps-summit-2027","APS Global Physics Summit 2027","APS Summit 2027","Conference",
  "quantum optics;quantum computing hardware;integrated quantum photonics","2027-04-11","2027-04-16","Atlanta, GA, USA",
  "TBA","TBA","TBA","TBA","https://www.aps.org/events/2027/summit",4,
  "Joint APS March+April meeting; major quantum photonics and computing sessions","upcoming","2026-05-13","no change","https://www.aps.org/events/2027/summit"),
r("qpain-2027","IEEE 3rd International Conference on Quantum Photonics, AI & Networking","QPAIN 2027","Conference",
  "integrated quantum photonics;quantum networking","2027-04-16","2027-04-18","Chattogram, Bangladesh",
  "TBA","TBA","TBA","TBA","https://qpain.org/",3,
  "Quantum photonics and networking conference (IEEE-sponsored, 3rd edition)",
  "upcoming","2026-06-21","new entry; 3rd edition confirmed","https://qpain.org/"),
r("cleo-2027","Conference on Lasers and Electro-Optics 2027","CLEO 2027","Conference",
  "integrated quantum photonics;quantum optics;nonlinear optics;silicon photonics;single-photon sources","2027-05-02","2027-05-07","Long Beach, CA, USA",
  "TBA","TBA","TBA","TBA","https://cleoconference.org/",5,
  "Premier US laser/photonics conference; IQP, Si-PIC and quantum optics flagship",
  "upcoming","2026-06-21","new entry; May 2-7 2027 Long Beach Convention Center confirmed",
  "https://cleoconference.org/;https://cleoconference.org/2027-topic-categories/"),
r("cleo-europe-2027","CLEO/Europe-EQEC 2027","CLEO/Europe 2027","Conference",
  "integrated quantum photonics;quantum optics;nonlinear optics;nanophotonics","2027-06-20","2027-06-25","Munich, Germany",
  "TBA","TBA","TBA","TBA","https://cleoeurope.org/",5,
  "Flagship European photonics and quantum optics biennial conference",
  "upcoming","2026-06-21","confirmed Jun 20-25 2027 as part of World of Photonics Congress (Laser WoP Jun 22-25)",
  "https://cleoeurope.org/;https://world-of-photonics.com/en/congress/program/"),
r("ieee-rapid-2027","IEEE Research and Applications of Photonics in Defense 2027","IEEE RAPID 2027","Conference",
  "single-photon sources;quantum communication","2027-08-11","2027-08-13","Miramar Beach, FL, USA",
  "TBA","TBA","TBA","TBA","https://ieee-rapid.org/",2,
  "Defense photonics conference","upcoming","2026-05-13","no change","https://ieee-rapid.org/"),
r("ipc-2027","IEEE Photonics Conference 2027","IPC 2027","Conference",
  "integrated quantum photonics;photonic integrated circuits;silicon photonics","2027-11-10","2027-11-14","Eindhoven, Netherlands",
  "TBA","TBA","TBA","TBA","https://ieee-ipc.org/",4,
  "IEEE photonics flagship; European edition in Eindhoven — low travel cost","upcoming","2026-05-13","no change","https://ieee-ipc.org/"),

# ── PLACEHOLDERS (TBA) ────────────────────────────────────────────────────
r("photonics-switching-2026","Photonics in Switching and Computing 2026","PiS 2026","Conference",
  "photonic integrated circuits;silicon photonics","TBA","TBA","TBA",
  "TBA","TBA","TBA","TBA","TBA",3,
  "Photonic switching and routing conference","upcoming","2026-05-13","no change; dates TBA (expected summer 2026)","original list"),
r("it-fab-school-2026","It-fab Italian Network for Micro and Nano Fabrication School 2026","It-fab School 2026","Summer School",
  "photonic integrated circuits;nanophotonics","TBA","TBA","TBA",
  "TBA","n/a","TBA","n/a","TBA",3,
  "Italian nanofabrication school relevant to photonic device processing","upcoming","2026-05-13","no change; dates TBA (expected Oct 2026)","original list"),
r("opic","Optics & Photonics International Congress","OPIC","Conference",
  "integrated quantum photonics;quantum optics;nanophotonics","TBA","TBA","TBA",
  "TBA","TBA","TBA","TBA","TBA",3,
  "Japanese international photonics congress with quantum tracks","upcoming","2026-05-13","placeholder; next edition dates TBA","original list"),
r("owtnm","Optical Wave & Waveguide Theory and Modelling Workshop","OWTNM","Workshop",
  "photonic integrated circuits;nanophotonics","TBA","TBA","TBA",
  "TBA","n/a","TBA","n/a","TBA",3,
  "Waveguide modelling workshop relevant to PIC simulation","upcoming","2026-05-13","placeholder; next edition dates TBA","original list"),
r("opon-2025","OPON 2025 Münster","OPON 2025","Conference",
  "integrated quantum photonics;nanophotonics","TBA","TBA","Münster, Germany",
  "TBA","TBA","TBA","TBA","TBA",4,
  "Local Münster photonics conference — direct access, no travel","upcoming","2026-05-13","no change; dates TBA","original list"),
r("nrw-nano-2026","NRW NanoConference 2026","NRW Nano 2026","Conference",
  "nanophotonics;photonic integrated circuits","TBA","TBA","North Rhine-Westphalia, Germany",
  "TBA","TBA","TBA","TBA","TBA",3,
  "Regional NRW nanotechnology conference; local access","upcoming","2026-05-13","no change; dates TBA","original list"),
r("icqe","International Conference on Quantum Energy","ICQE","Conference",
  "quantum computing hardware","TBA","TBA","TBA",
  "TBA","TBA","TBA","TBA","TBA",2,
  "Quantum energy applications; adjacent to quantum computing hardware","upcoming","2026-05-13","placeholder; next edition TBA","original list"),
]

# ── Write TSV ──────────────────────────────────────────────────────────────
tsv_path = f"/home/user/conferences/conferences_{SNAPSHOT}.tsv"
with open(tsv_path, "w", encoding="utf-8") as f:
    f.write("\t".join(HEADERS) + "\n")
    for row in rows:
        f.write("\t".join(row[h] for h in HEADERS) + "\n")
print(f"Wrote {len(rows)} rows → {tsv_path}")

# ── Write XLSX ─────────────────────────────────────────────────────────────
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment
from openpyxl.utils import get_column_letter

RED   = PatternFill("solid", fgColor="FF4444")
AMBER = PatternFill("solid", fgColor="FFBB33")
HEADER_FILL = PatternFill("solid", fgColor="2C3E50")

DEADLINE_COLS = ["abstract_deadline","paper_deadline","registration_deadline","early_bird_deadline"]

def parse_date(s):
    try:
        return date.fromisoformat(s)
    except:
        return None

wb = Workbook()
ws = wb.active
ws.title = "Conferences"

# Header row
for ci, h in enumerate(HEADERS, 1):
    cell = ws.cell(row=1, column=ci, value=h)
    cell.font = Font(bold=True, color="FFFFFF")
    cell.fill = HEADER_FILL
    cell.alignment = Alignment(horizontal="center", wrap_text=True)

ws.freeze_panes = "A2"
ws.auto_filter.ref = f"A1:{get_column_letter(len(HEADERS))}1"

# Data rows
for ri, row in enumerate(rows, 2):
    for ci, h in enumerate(HEADERS, 1):
        val = row[h]
        cell = ws.cell(row=ri, column=ci, value=val)
        cell.alignment = Alignment(wrap_text=True, vertical="top")
        # Conditional colour on deadline columns
        if h in DEADLINE_COLS:
            d = parse_date(val)
            if d is not None:
                delta = (d - TODAY).days
                if 0 <= delta <= 14:
                    cell.fill = RED
                elif 15 <= delta <= 60:
                    cell.fill = AMBER

# Auto-size columns (cap at 60)
for ci, h in enumerate(HEADERS, 1):
    max_len = len(h)
    for ri in range(2, len(rows)+2):
        v = ws.cell(row=ri, column=ci).value or ""
        max_len = max(max_len, min(len(str(v)), 60))
    ws.column_dimensions[get_column_letter(ci)].width = min(max_len + 2, 62)

xlsx_path = f"/home/user/conferences/conferences_{SNAPSHOT}.xlsx"
wb.save(xlsx_path)
print(f"Wrote XLSX → {xlsx_path}")
